In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
import datetime

In [2]:
END_DATE = '2026-01-01'

In [3]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [4]:
hours = (365 * 11 + 3) * 24
base = datetime.datetime(2015, 1, 1)
date_list = [base + datetime.timedelta(hours=x) for x in range(0, hours)]
COMPLETE = pd.DataFrame(data={'produced_at': date_list})
COMPLETE.produced_at = pd.to_datetime(COMPLETE.produced_at)

In [5]:
date_list[-1]

datetime.datetime(2025, 12, 31, 23, 0)

In [6]:
#COMPLETE

In [7]:
base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end=END_DATE, freq='1h')})

In [8]:
base_df.dtypes

produced_at    datetime64[ns]
dtype: object

In [9]:
files = [f for f in os.listdir("combined")]

In [10]:
#files

In [11]:
COMPLETE.dtypes

produced_at    datetime64[ns]
dtype: object

In [12]:
def gen_power3(files):
    zero = pd.DataFrame()
    result = COMPLETE
    for f in files[0:6]:
        final = pd.DataFrame()
        df = pd.read_csv("./combined/" + f, parse_dates=["produced_at"])
        #print(f)
        df2 = pd.DataFrame()
        try:
            df2 = df.merge(COMPLETE, on='produced_at', how='right')
        except ValueError:
            print(f)
        if final.empty:
            final = df2
        else:
            final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [13]:
start = datetime.datetime.now()

In [14]:
#cdf = gen_power3(files)

In [15]:
end = datetime.datetime.now()

In [16]:
duration = end - start
duration_in_s = duration.total_seconds()

In [17]:
duration_in_s

0.678175

In [18]:
fls = os.listdir("combined")
fls.remove('.ipynb_checkpoints')

In [19]:
fls.sort()

In [20]:
fls

['06-02-B10117A007.csv',
 '06-05-100-0431554.csv',
 '06-05-100-0853075.csv',
 'BB23020490.csv',
 'BB45025564.csv',
 'BB45025611.csv',
 'BE166928.csv',
 'BE169709.csv',
 'BE172654.csv',
 'BE172656.csv',
 'BWpf-450-1020129-00000000.csv',
 'BWpf-450-1195689-00000000.csv',
 'BWpf-450-1741292-00000000.csv',
 'BWpf-450-2142201-00000000.csv',
 'BWpf-450-2797933-00000000.csv',
 'BWpf-450-2948214-00000000.csv',
 'BWpf-450.csv',
 'BYS00009.csv',
 'BYS00041.csv',
 'BYS00044.csv',
 'BYS00048.csv',
 'BYS00114.csv',
 'BYS00727.csv',
 'HE30001045.csv',
 'HE50001960.csv',
 'MV30000226.csv',
 'NI01010098080.csv',
 'NI01012110180.csv',
 'NI01241117210.csv',
 'NI06060316030.csv',
 'NI09000237910.csv',
 'NI10257673950.csv',
 'NW100-0081105.csv',
 'NW100-0167182.csv',
 'NW100-0229264.csv',
 'NW100-0248923.csv',
 'NW100-0365906.csv',
 'NW300-0326774.csv',
 'NW300-0370387.csv',
 'NW300-0877384.csv',
 'NW300-0923949.csv',
 'NW300-9002708.csv',
 'NW300-9046030.csv',
 'NW500-0342658.csv',
 'NW500-0915123.csv',
 'NW700-0105516.csv',
 'NW900-0045033.csv',
 'NW900-0079017.csv',
 'NW900-0080266.csv',
 'NW900-0125939.csv',
 'NW900-0205103.csv',
 'NW900-0327252.csv',
 'NW900-0865327.csv',
 'NW900-0884101.csv',
 'NW900-9140178.csv',
 'NW900-9141660.csv',
 'RP5000671.csv',
 'SD661-06.csv',
 'SD661-18.csv',
 'SD661-94.csv',
 'SD666-12.csv',
 'SD666-16.csv',
 'SD666-17.csv',
 'SD666-18.csv',
 'SD669-01.csv',
 'SH50080412.csv',
 'SL0100999-G.csv',
 'SL0101000-G.csv',
 'SL0101003-G.csv',
 'SL0105352-G.csv',
 'SN70015796.csv',
 'SN80011256.csv',
 'SN80011277.csv',
 'ST100125.csv']

In [21]:
#cdf

In [24]:
def combine2cdf():
    base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end=END_DATE, freq='1h')})
    #base_df['produced_at'] = base_df['produced_at'].astype(str)
    pdlist = [base_df]
    fls = os.listdir("combined")
    fls.remove('.ipynb_checkpoints')
    for f in fls:
        #final = pd.DataFrame()
        tmp = pd.read_csv("combined/" + f, na_values='-')
        final = tmp.drop(columns=['produced_at'], axis=1)
        print(tmp.shape)
        #if final.empty:
        #    final = result
        #else:
        #    print("DEBUG!")
        #df['produced_at'] = df['produced_at'].astype(str)
        #df = pd.merge(base_df, df, on="produced_at", how='outer')
        pdlist.append(final)
        #result = pd.merge(result, result, how='left', on=['produced_at'])
        
    
    result = pd.concat(pdlist, axis=1)
        
        #df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
    return result

In [25]:
cdf = combine2cdf()

(87672, 2)
(385728, 7)
(87672, 2)
(35064, 3)
(52608, 2)
(87672, 8)
(385728, 4)
(385728, 7)
(61368, 3)
(87672, 2)
(87672, 2)
(87672, 3)
(87672, 6)
(87672, 4)
(385728, 4)
(87672, 4)
(87672, 2)
(87672, 3)
(385728, 4)
(87672, 2)
(87672, 9)
(385728, 6)
(26311, 14)
(385728, 5)
(87672, 2)
(385728, 4)
(87672, 6)
(385728, 6)
(385728, 7)
(61368, 6)
(26304, 3)
(87672, 3)
(87672, 3)
(87672, 3)
(385728, 6)
(70128, 3)
(385728, 4)
(385728, 10)
(87672, 2)
(385728, 2)
(61368, 2)
(385728, 5)
(35064, 4)
(385728, 7)
(87672, 2)
(78888, 2)
(43824, 2)
(78888, 2)
(87672, 5)
(87672, 3)
(35064, 2)
(87672, 3)
(385728, 3)
(87682, 2)
(385728, 5)
(87672, 4)
(315552, 5)
(43824, 2)
(87672, 4)
(35064, 2)
(78888, 2)
(385728, 3)
(87672, 3)
(87672, 3)
(87672, 2)
(122712, 4)
(87672, 10)
(385728, 4)
(35064, 2)
(385243, 2)
(26304, 3)
(78888, 3)
(87672, 3)
(385435, 3)

In [24]:
#cdf = combine2cdf()

In [26]:
cdf = cdf.loc[:, ~cdf.columns.str.contains('^Unnamed')]
cdfa = cdf.dropna(subset=['produced_at'])
cdf2 = cdfa.fillna(0.0)

In [27]:
cdf2

,produced_at,SEE954971534470,SEE963541517812,SEE948129095272,SEE915432109163,SEE915883553447,SEE924780675428,SEE973737205324,SEE905192478234,BNA0619,...,SEE970425279599,SEE961029163353,BNA0991,BNA0992,SEE932621971301,SEE925631744058,SEE922855765289,SEE964745752825,SEE966331411864,SEE998199911088
0,2015-01-01 00:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96428,2025-12-31 20:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96429,2025-12-31 21:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96430,2025-12-31 22:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96431,2025-12-31 23:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96432,2026-01-01 00:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0

In [28]:
cdf2

,produced_at,SEE954971534470,SEE963541517812,SEE948129095272,SEE915432109163,SEE915883553447,SEE924780675428,SEE973737205324,SEE905192478234,BNA0619,...,SEE970425279599,SEE961029163353,BNA0991,BNA0992,SEE932621971301,SEE925631744058,SEE922855765289,SEE964745752825,SEE966331411864,SEE998199911088
0,2015-01-01 00:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96428,2025-12-31 20:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96429,2025-12-31 21:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96430,2025-12-31 22:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96431,2025-12-31 23:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0
96432,2026-01-01 00:00:00,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0

In [29]:
#cdf['produced_at'] = cdf['produced_at'].astype(pd.datetime64)
cdf2['produced_at'] = pd.to_datetime(cdf2['produced_at'])

In [30]:
list(cdf2.dtypes)

[dtype('<M8[ns]'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64')]

In [31]:
gm = cdf2.resample('1ME', on='produced_at').sum()

In [32]:
gm

,SEE954971534470,SEE963541517812,SEE948129095272,SEE915432109163,SEE915883553447,SEE924780675428,SEE973737205324,SEE905192478234,BNA0619,BNA0618,...,SEE970425279599,SEE961029163353,BNA0991,BNA0992,SEE932621971301,SEE925631744058,SEE922855765289,SEE964745752825,SEE966331411864,SEE998199911088
produced_at,,,,,,,,,,,,,,,,,,,,,
2015-01-31,0.0,0,0,0,0,0,0,17830.0,0.0,0.0,...,0.0,57164.0,72670.0,0.0,0.0,0.0,11041.0,0.0,69048.0,68480.0
2015-02-28,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,40708.0,0.0,0.0,0.0,0.0,0.0,0.0,106008.0,32024.0
2015-03-31,0.0,1588,3688,0,0,0,0,0.0,0.0,0.0,...,0.0,104616.0,0.0,0.0,0.0,0.0,0.0,0.0,155372.0,117940.0
2015-04-30,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,139768.0,114540.0
2015-05-31,50947.0,0,0,0,0,0,0,0.0,64.0,12765.0,...,0.0,0.0,51767.0,61830.0,0.0,0.0,0.0,0.0,150648.0,150220.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-09-30,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,114024.0,0.0,0.0,0.0,0.0,0.0,0.0,149552.0,141676.0
2025-10-31,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,81464.0,0.0,0.0,0.0,0.0,0.0,0.0,109812.0,123160.0
2025-11-30,0.0,0,3792,0,0,0,0,0.0,0.0,0.0,...,0.0,125792.0,0.0,0.0,0.0,0.0,0.0,0.0,155508.0,154284.0
2025-12-31,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,67656.0,0.0,0.0,0.0,0.0,0.0,0.0,160628.0,158372.0
2026-01-31,0.0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0

In [33]:
gm2 = gm.reset_index()
#gm2['year'] = gm2['produced_at2']
#gm2['month'] = gm2['produced_at3']

In [34]:
def gen_power3(files):
    result = COMPLETE
    for plant, files in FILES_DICT.items():
        final = pd.DataFrame()
        for idx, f in enumerate(files):
            f = "fix/" + f
            df = pd.read_csv(f, parse_dates=["produced_at"])
            df2 = df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
            if final.empty:
                final = df2
            else:
                final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [34]:
gm2

,produced_at,SEE954971534470,SEE963541517812,SEE948129095272,SEE915432109163,SEE915883553447,SEE924780675428,SEE973737205324,SEE905192478234,BNA0619,...,SEE970425279599,SEE961029163353,BNA0991,BNA0992,SEE932621971301,SEE925631744058,SEE922855765289,SEE964745752825,SEE966331411864,SEE998199911088
0,2015-01-31,0.0,0,0,0,0,0,0,17830.0,0.0,...,0.0,57164.0,72670.0,0.0,0.0,0.0,11041.0,0.0,69048.0,68480.0
1,2015-02-28,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,40708.0,0.0,0.0,0.0,0.0,0.0,0.0,106008.0,32024.0
2,2015-03-31,0.0,1588,3688,0,0,0,0,0.0,0.0,...,0.0,104616.0,0.0,0.0,0.0,0.0,0.0,0.0,155372.0,117940.0
3,2015-04-30,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,139768.0,114540.0
4,2015-05-31,50947.0,0,0,0,0,0,0,0.0,64.0,...,0.0,0.0,51767.0,61830.0,0.0,0.0,0.0,0.0,150648.0,150220.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,2025-09-30,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,114024.0,0.0,0.0,0.0,0.0,0.0,0.0,149552.0,141676.0
129,2025-10-31,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,81464.0,0.0,0.0,0.0,0.0,0.0,0.0,109812.0,123160.0
130,2025-11-30,0.0,0,3792,0,0,0,0,0.0,0.0,...,0.0,125792.0,0.0,0.0,0.0,0.0,0.0,0.0,155508.0,154284.0
131,2025-12-31,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,67656.0,0.0,0.0,0.0,0.0,0.0,0.0,160628.0,158372.0
132,2026-01-31,0.0,0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,217.0,214.0