In [5]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
from sqlalchemy import create_engine, inspect, text, DateTime
from sqlalchemy.orm import Session
import psycopg
import time
from psycopg import DataError

In [6]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512
mapper = get_mapper('newestmapper_v2.json')
newmapper = get_mapper('newestmapper_v2.json')

In [8]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [20]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

/tmp/ipykernel_3560985/2092039524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [37]:
def get_plant_from_prod_name2(prodname):
    tmp = ""
    try:
        tmp = newmapper[prodname]
    except KeyError:
        #print("plant " + prodname + " not found!")
        return None, None
    seelist = tmp['list']
    block = seelist[0]
    blockid = tmp[block]
    
    try:
        plantidx = seem.loc[seem.sseid == blockid, 'plantid'].item()
    except ValueError:
        return blockid, np.nan
    
    return blockid, plantidx

In [38]:
def get_files_from_folder(folder):
    onlyfiles = [folder + "/" + f for f in listdir(folder) if isfile(join(folder, f))]
    onlyfiles.sort()
    files = [f for f in onlyfiles if stat(f).st_size > MIN_SIZE]
    return files

In [39]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-4]
FILES_L = [get_files_from_folder(f) for f in FOLDERS]
FILES = [item for sublist in FILES_L for item in sublist]

In [ ]:
with Session(engine2) as sess:
    sess.execute(text("TRUNCATE TABLE power4"))
    sess.commit()

In [41]:
ret_code = df.to_sql('power4', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})

NameError: name 'df' is not defined

In [55]:
def get_smard_name(f):
    return f.rsplit("/")[2].rsplit("_", 4)[0].strip()

def get_year2(fn):
    return int(fn.rsplit("_", 3)[1][0:4])

def extract_blockidf2(fullname, plantname):
    return fullname.split("Generation_DE ")[1].rsplit('[MW]')[0].strip().removeprefix(plantname + " ")

def convert2plantid(df, plantname):
    oldcols = list(df.columns)
    newcols = [extract_blockidf2(x, plantname) for x in list(df.columns)[1:]]
    #print(plantname + ":" + str(newcols))
    try:
        newcols2 = ['produced_at'] + [mapper[plantname][x] for x in newcols]
    except KeyError:
        newcols2 = ['produced_at'] + [mapper[plantname][x.split(" ")[-1]] for x in newcols]
    test = dict(zip(oldcols, newcols2))
    result = df.rename(columns=test)
    #print(oldcols)
    #print(newcols2)
    return result

In [56]:
prod_mapper = []
for f in FILES:
    fn = get_smard_name(f)
    f = f.replace("\\","/", 2)
    #print(fn)
    blockid, plantid = get_plant_from_prod_name2(fn)
    #print(fn or "" + ":" + blockid or "" + "->" + plantid or "")
    year = 2015
    try:
        year = get_year2(f)
    except IndexError:
        print(fn)
        pass
    prod_mapper.append([f, blockid, plantid, year])

In [57]:
FOLDERS

['./2015',
 './2016',
 './2017',
 './2018',
 './2019',
 './2020',
 './2021',
 './2022',
 './2023',
 './2024',
 './2025']

In [58]:
prd_df = pd.DataFrame(prod_mapper, columns = ['file', 'blockid', 'plantid', 'year'])
dedup = prd_df.dropna(subset=['blockid', 'plantid'])

In [72]:
def fix_date(noDate):
    try:
        return datetime.strptime(noDate, "%Y-%m-%d %H:%M:%S")
    except ValueError:
        #print(noDate)
        return datetime.strptime(noDate, "%d.%m.%Y %H:%M")

In [80]:
with Session(engine2) as sess:
    sess.execute(text("TRUNCATE TABLE power4"))
    sess.commit()

In [81]:
starttime = datetime.now()

In [82]:
for index, row in list(dedup.iterrows()):
    dfname = row.iloc[0]
    plantid = str(row.iloc[2])
    year = str(int(row.iloc[3]))
    smardname = get_smard_name(dfname)
    try:
        df = pd.read_csv(dfname, delimiter=";", na_values=['-'], thousands='.', decimal=',', parse_dates=["Datum von"], on_bad_lines='skip', engine="python")
        df['Datum von'] = pd.to_datetime(df['Datum von'], format='%d.%m.%Y %H:%M')
        df = df.drop('Datum bis', axis=1)
    except ValueError:
        df = pd.read_csv(dfname, delimiter=";", na_values=['-'], thousands='.', decimal=',', parse_dates=["Datum von"], on_bad_lines='skip', engine="python")
        df = df.drop('Datum bis', axis=1)
    try:
    #print(smardname)            
        newdf = convert2plantid(df, smardname)
    except (KeyError):
        print(year + ': ' + smardname)
        continue
        
    try:
        newdf.fillna(0, inplace=True)
        newdf[newdf.columns[1:]] = newdf[newdf.columns[1:]].astype(int)
        newdf['produced_at'] = pd.to_datetime(newdf['produced_at'])
        df2 = newdf
    except (ValueError, KeyError, IndexError):
        df2 = newdf[newdf.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
        df2['produced_at'] = df2['produced_at'].map(fix_date)
        df2['produced_at'] = pd.to_datetime(df2['produced_at'])
        df2.drop_duplicates(subset='produced_at', inplace=True)

    try:
        melt = df2.melt(id_vars='produced_at')
        result = melt.to_sql('power4', con=engine2, if_exists='append', index=False, dtype={'produced_at': DateTime})
        #newdf.to_csv("./by_plantid/" + year + "/" + plantid + '.csv', index=False)
        if (smardname == 'M_nchen_Nord_2'):
            print('success')
        if (smardname == "Kraftwerk_Lippendorf"):
            irschdf = newdf
    except (ValueError, KeyError, IndexError, DataError):
        print(year + ': ' + smardname)
        continue

2015: Kraftwerk_Burghausen
2015: Kraftwerk_Emsland
2015: Kraftwerk_Neurath
2015: Kraftwerk_R_merbr_cke
2015: Kraftwerk_Scholven
2015: Kraftwerk_Walsum
2016: Kraftwerk_Burghausen
2016: Kraftwerk_Emsland
2016: Kraftwerk_Neurath
2016: Kraftwerk_R_merbr_cke
2016: Kraftwerk_Scholven
2016: Kraftwerk_Walsum
2017: Kraftwerk_Burghausen
2017: Kraftwerk_Emsland
2017: Kraftwerk_Neurath
2017: Kraftwerk_R_merbr_cke
2017: Kraftwerk_Scholven
2017: Kraftwerk_Walsum
2018: Kraftwerk_Burghausen
2018: Kraftwerk_Emsland
2018: Kraftwerk_Neurath
2018: Kraftwerk_R_merbr_cke
2018: Kraftwerk_Scholven
2018: Kraftwerk_Walsum
2019: Heizkraftwerk_West
2019: Kraftwerk_Burghausen
2019: Kraftwerk_Emsland
2019: Kraftwerk_Neurath
2019: Kraftwerk_R_merbr_cke
2019: Kraftwerk_Scholven
2019: Kraftwerk_Walsum
2020: Heizkraftwerk_West
2020: Kraftwerk_Burghausen
2020: Kraftwerk_Emsland
2020: Kraftwerk_Neurath
2020: Kraftwerk_R_merbr_cke
2020: Kraftwerk_Scholven
2020: Kraftwerk_Walsum
2021: Heizkraftwerk_West
2021: Kraftwerk_Burghausen
2021: Kraftwerk_Emsland
2021: Kraftwerk_Neurath
2021: Kraftwerk_R_merbr_cke
2021: Kraftwerk_Scholven
2021: Kraftwerk_Walsum
2022: Heizkraftwerk_West
2022: Kraftwerk_Burghausen
2022: Kraftwerk_Emsland
2022: Kraftwerk_Neurath
2022: Kraftwerk_R_merbr_cke
2022: Kraftwerk_Scholven
2022: Kraftwerk_Walsum
2023: Heizkraftwerk_West
2023: Kraftwerk_Burghausen
2023: Kraftwerk_Emsland
2023: Kraftwerk_Neurath
2023: Kraftwerk_R_merbr_cke
2023: Kraftwerk_Scholven
2023: Kraftwerk_Walsum
2024: Heizkraftwerk_West
2024: Kraftwerk_Burghausen
2024: Kraftwerk_Emsland
2024: Kraftwerk_Neurath
2024: Kraftwerk_R_merbr_cke
2024: Kraftwerk_Scholven
2024: Kraftwerk_Walsum
2025: Heizkraftwerk_West
2025: Kraftwerk_Burghausen
2025: Kraftwerk_Emsland

/tmp/ipykernel_1514113/1751099284.py:26: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = newdf[newdf.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_1514113/1751099284.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_1514113/1751099284.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_1514113/1751099284.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)
/tmp/ipykernel_1514113/1751099284.py:26: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df2 = newdf[newdf.produced_at.str.contains('(^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})|(^[0-9]{2}.[0-9]{2}.[0-9]{4} [0-9]{2}:[0-9]{2}$)', regex=True)]
/tmp/ipykernel_1514113/1751099284.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = df2['produced_at'].map(fix_date)
/tmp/ipykernel_1514113/1751099284.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['produced_at'] = pd.to_datetime(df2['produced_at'])
/tmp/ipykernel_1514113/1751099284.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop_duplicates(subset='produced_at', inplace=True)

2025: Kraftwerk_Neurath
2025: Kraftwerk_R_merbr_cke
2025: Kraftwerk_Scholven

In [86]:
endtime = datetime.now()
duration = endtime - starttime

In [87]:
duration

datetime.timedelta(seconds=1248, microseconds=632580)

In [84]:
melt = irschdf.melt(id_vars='produced_at')

In [85]:
melt

            produced_at         variable  value
0      01.01.2025 00:00  SEE966331411864      0
1      01.01.2025 00:15  SEE966331411864      0
2      01.01.2025 00:30  SEE966331411864      0
3      01.01.2025 00:45  SEE966331411864      0
4      01.01.2025 01:00  SEE966331411864      0
...                 ...              ...    ...
69489  31.12.2025 22:45  SEE998199911088      0
69490  31.12.2025 23:00  SEE998199911088      0
69491  31.12.2025 23:15  SEE998199911088      0
69492  31.12.2025 23:30  SEE998199911088      0
69493  31.12.2025 23:45  SEE998199911088      0

[69494 rows x 3 columns]

In [9]:
starttime2 = datetime.now()
CDF = pd.read_sql_table('power4', engine2)
endtime2 = datetime.now()
duration2 = endtime2 - starttime2

In [10]:
duration2

datetime.timedelta(seconds=229, microseconds=257498)

In [11]:
#CDF.to_csv("CDF-direct.csv", index=False)

In [12]:
CDF9a = CDF.fillna(0)

In [13]:
CDF9b = CDF9a.loc[~(CDF9a.variable == "")]

In [14]:
(len(CDF9a) - len(CDF9b)) / len(CDF)

0.010827172416758787

In [15]:
CDF9b['produced_at'] = pd.to_datetime(CDF9b['produced_at']) #, errors='coerce'

/tmp/ipykernel_3560985/850073426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CDF9b['produced_at'] = pd.to_datetime(CDF9b['produced_at']) #, errors='coerce'

In [16]:
CDF2 = CDF9b.groupby('variable').resample('1ME', on='produced_at').sum()

/tmp/ipykernel_3560985/2823503854.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  CDF2 = CDF9b.groupby('variable').resample('1ME', on='produced_at').sum()

In [17]:
gm2 = CDF2.drop(columns="variable").reset_index()

In [18]:
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [21]:
bpm = seem.copy()

In [22]:
gm8.sort_values('power', ascending=False)

      year  month          blockid   power
2371  2017      3  SEE983252937631  675444
3843  2018      7  SEE983252937631  673284
3935  2018      8  SEE983252937631  668744
2555  2017      5  SEE983252937631  663324
951   2015     11  SEE983252937631  651764
...    ...    ...              ...     ...
7337  2021      9  SEE980327120226       0
7336  2021      9  SEE978207781308       0
7335  2021      9  SEE976850689781       0
7334  2021      9  SEE976219797843       0
7330  2021      9  SEE973737205324       0

[12060 rows x 4 columns]

In [29]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

ym1 = pm4.copy()
#ym1.drop_duplicates(['year', 'plantid'], inplace=True)
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1.drop_duplicates(['year', 'plantid'])
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [30]:
ym4.loc[ym4.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [year, plantid, yearpower]
Index: []

In [31]:
ym4.to_csv("yearly-direct.csv", index=False)
ym4.to_csv("yearly_pg-direct.csv", header=False)
gm8.to_csv("monthly-direct.csv", header=False)