In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
FOLDERS = [os.path.join(BASE_DIR, o) for o in os.listdir(BASE_DIR) if os.path.isdir(os.path.join(BASE_DIR,o))]
FOLDERS.sort()
FOLDERS = FOLDERS[1:-4]
YEARS = ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [4]:
FOLDERS

['./2015',
 './2016',
 './2017',
 './2018',
 './2019',
 './2020',
 './2021',
 './2022',
 './2023',
 './2024',
 './2025']

In [5]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
#ssem = pd.read_csv("../basic/plant_sse_mapper.csv")
#ssem['plantid'] = ssem['plantid'].apply(lambda x: str(x).replace('/', '_'))

raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

plantslist = list(set(seem['plantid'].to_list()))

/tmp/ipykernel_1467851/4204571207.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [6]:
seem

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [7]:
#plantslist

In [8]:
def save2combined(df, plantname):
    df.to_csv("./combined/" + plantname + ".csv", index=False)

In [9]:
def squash_production(plantslist):
    emptyplants = []
    for plant in plantslist:
        #print(plant)
        dflist = []
        for year in YEARS:
            try:
                df = pd.read_csv("./by_plantid/" + year + "/" + plant + ".csv")
                #df.fillna(0, inplace=True)
                df[df.columns[1:]] = df[df.columns[1:]].astype(int)
            except FileNotFoundError:
                #print("./by_plantid/" + year + "/" + plant + ".csv")
                df = pd.DataFrame({'produced_at': []})
    
            testdf = df.dropna()
            if testdf.empty:
                emptyplants.append(plant)
            else:
                dflist.append(df)
                
        if len(dflist) > 0:
            newdf = pd.concat(dflist)
            save2combined(newdf, plant)

    return list(set(emptyplants))

In [10]:
a = squash_production(plantslist)

In [11]:
len(plantslist)

355

In [12]:
len(a)

332

In [13]:
errorset = []
for plant in plantslist:
    dflist = []
    for year in YEARS:
        df = pd.DataFrame()
        try:
            df = pd.read_csv("./by_plantid/" + year + "/" + plant + ".csv", na_values=['-'])
        except FileNotFoundError:
            if (plant not in errorset):
                errorset.append(plant)
            pass
        
        dflist.append(df)
    newdf = pd.concat(dflist)
    #print(newdf.shape)
print(errorset)

['HE20000115', 'BWpf-450-2951606-00000000', 'NW100-9021016', 'DE.EEA46609', 'BWpf-450-4124448-00000000', 'RP5000656', 'BYS00869', 'NW300-0079450', 'SH50082038', 'NW300-0181417', 'HE50002167', 'HB06-04-11_2000122_0_0', 'ST100032', 'NW500-9981505', 'ST100876', 'SD662-18', 'SD661-85', 'NI31000005008', 'SD661-98', 'BYS00035', 'SD661-94', 'BYS00323', 'ST100850', 'SD661-82', 'NI06277201660', 'BYS00104', 'ST100344', 'MV60004935', 'NW300-0054298', 'MV90031941', 'BWpf-450-3042693-00000000', 'NW100-0030712', 'ST102622', 'HE30001045', 'SD666-13', 'NW700-0020290', 'NW500-0338944', 'SD666-11', 'HE20000004', 'BWpf-450-2719371-00000000', 'NW900-0021170', 'SD666-15', 'NW300-0215520', 'NI01211092310', 'NI05050072350', 'SD661-109', 'BE222276', 'NI10100029340', 'DE.EEA44484', 'SD661-65', 'NW500-0875785', 'ST18046', 'BWpf-450-34064722-00000000', 'HH12273', 'SD661-12', 'NI09261732970', 'SD661-107', 'SD661-39', 'NW100-0387357', 'RP5000031', 'NI04224004080', 'SH10000140', 'ST100609', 'NI01227041760', 'SD661-29', 'BYS00041', 'BYS00149', 'NW700-0008683', 'ST100419', 'BYS00894', 'SD661-75', 'NW900-9140178', 'SD666-12', 'RP1000136', 'SD661-80', 'SD661-112', 'NI08271405180', 'SD661-11', 'SD666-14', 'SD661-113', 'BYS00045', 'NW500-0915123', 'BB45026985', 'NI05231382180', 'ST100864', 'SD661-13', 'SN70015959', 'NI09000237910', 'SD661-09', 'NI02020049510', 'BYS00291', 'SD662-01', 'TH62013494', 'NI10285139970', 'NW300-9046797', 'SL0105352-G', '06-05-100-0853075', 'SD661-86', 'SD662-09', 'BYS00282', 'SD661-100', 'NW900-0080266', 'NW100-0229264', 'HH12275', 'SD661-54', 'NW900-0271161', 'SN70015792', 'BYS00235', 'BWpf-450-4666496-00000000', 'SD661-59', 'SD661-66', 'SN80011250', 'BWpf-450-1383701-00000000', 'HE30000963', 'NI01012110180', 'SH10039818', 'NW700-0104479', 'NW500-0342658', 'TH30013152', 'SD661-43', 'NW900-0001413', 'NW900-0079017', 'NW100-0154540', 'SD661-83', 'DE.EEA255206', 'BWpf-450-3610519-00000000', 'NI07244141350', 'MV60004960', 'NW100-0036701', 'BYS00108', 'BE173145', 'NI02221253020', 'SN70015917', 'NW300-0072412', 'SD666-18', 'BE172656', 'SD661-38', 'BWpf-450-1574906-00000000', 'SD669-01', 'SN60018636', 'BYS00845', 'BB16018798', 'SD662-06', 'BYS01153', 'RP4000021', 'SD661-78', 'HE50000118', 'SD661-77', 'NI09281337040', 'SD662-99', 'DE.EEA255737', 'NW100-0501870', 'NI07244473830', 'SD661-37', 'SD661-106', 'NI04247180070', 'NI01010098080', 'BB16012651', 'RP4000041', 'DE.EEA43267', 'SD661-111', 'NI10257673950', 'SD662-14', 'SD661-88', 'BWpf-450-1371304-00000000', 'SL0101000-G', 'NI06060116320', 'DE.EEA44322', 'DE.EEA46983', 'HE50001960', 'SL0101003-G', 'DE.EEA43436', 'SD661-96', 'SD661-110', 'SD661-44', 'BYS00925', 'MV40000004', 'NW900-0884101', 'NI01010959490', 'RP5000221', 'NW100-0031758', 'BE166927', 'BYS00311', 'SD661-63', 'SL0075248-G', 'NW300-0213768', 'NW300-0215443', 'SD664-02', 'SD662-20', 'SD661-16', 'BE173097', 'BE181711', 'BYS00860', 'BYS00135', 'NW700-9073419', 'NW900-0125939', 'NW300-0890760', 'BWpf-450-2948214-00000000', 'SD661-93', 'NW100-0046639', 'SD661-79', 'BYS00758', 'BYS00114', 'MV30000298', 'SD661-99', 'NW100-0081105', 'SD662-03', 'SD661-28', 'NW300-9046030', 'NI10101531850', 'NI10257401440', 'NW700-0105516', 'SD661-95', 'SD661-64', 'SL0100999-G', 'BWpf-450-9840001-00000000', 'SD662-22', 'SD662-10', 'SD661-84', 'SD661-14', 'BWpf-450-1479296-00000000', '06-02-B10117A007', 'BYS00998', 'SD662-17', 'TH72012874', 'BE169709', 'NW100-0888309', 'SD661-97', 'NW700-9073508', 'BYS00334', 'DE.EEA44408', 'BB45026224', 'SD661-91', 'SD661-115', 'SD661-89', 'SD662-11', 'ST101071', 'HE50002126', 'HE50002119', 'BYS00064', 'BB23022811', 'DE.EEA2514', 'SD661-19', 'ST100674', 'NI01241117210', 'BWpf-450-80920445-00000000', 'SH50080603', 'RP5000152', 'BE132279', 'SD661-15', 'MV50000071', 'TH86012942', 'NI03267770260', 'NW100-0018507', 'BYS00233', 'BE172368', 'SD661-108', 'NW800-0197054', 'HE50002124', 'HE30000036', 'NW100-0042820', 'SD661-87', 'SD661-67', 'NW100-9020309', 'SD661-101', 'NW300-0838652', 'BYS00471', 'HE50000213', 'BYS00727', 'SD661-102', 'SD661-17', 'NW100-0365906', '16-30-31400103005', 'NW300-0370387', 'HE80000333', 'ST100498', 'BB45025611', 'SD662-12', 'NW300-0907015', 'HE30000030', 'SH50080412', 'BB45025575', 'HE30000163', 'DE.EEA46617', 'SD661-105', 'RP4000050', 'SN80011256', 'SD661-103', 'SD661-06', 'NW300-0877384', 'SD664-07', '06-05-100-0431554', 'SD662-28', 'SD661-42', 'NI01244641360', 'SN80011266', 'BYS00904', 'NW900-0045033', 'BYS00719', 'SD661-81', 'HH4383', 'SD661-92', 'SD661-36', 'SD661-18', 'DE.EEA44708', 'BYS00995', 'BYS00708', 'NW900-0235121', 'NW900-0865327', 'NI01010157480', 'BYS00009', 'SD666-16', 'NW100-0989137', '06-05-100-0030723', 'SH50083712', 'BB23020389', 'NW900-0205103', 'NW100-0990908', 'NI09281566110', 'DE.EEA46679', 'BYS00505', 'HH11643', 'SD661-53', 'NW900-0888950', 'BYS00056', 'NW100-0248923', 'ST101086', 'SD662-98', 'NI03030273580', 'SD661-90', 'SN60015149', 'SD666-17']

In [14]:
newdf

              produced_at  SEE944567587799
0     2015-01-01 00:00:00                0
1     2015-01-01 01:00:00                0
2     2015-01-01 02:00:00                0
3     2015-01-01 03:00:00                0
4     2015-01-01 04:00:00                0
...                   ...              ...
8755  2023-12-31 19:00:00                0
8756  2023-12-31 20:00:00                0
8757  2023-12-31 21:00:00                0
8758  2023-12-31 22:00:00                0
8759  2023-12-31 23:00:00                0

[78888 rows x 2 columns]

In [15]:
True if '06-05-500-0915123' in errorset else False

False