In [9]:
import pandas as pd
from datetime import datetime
#from pandas.io.parsers import ParserError
import numpy as np
import json
import os
import re
from sqlalchemy import create_engine, inspect, text, DateTime
from sqlalchemy.orm import Session
import psycopg
import time

In [27]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))
bpm = seem.copy()

/tmp/ipykernel_3538565/3639595966.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [10]:
engine2 = create_engine('postgresql+psycopg://plantwatch:N0m1596.@127.0.0.1/plantwatch')

In [11]:
starttime2 = datetime.now()
CDF = pd.read_csv("CDF-direct.csv")#pd.read_sql_table('power4', engine2)
endtime2 = datetime.now()
duration2 = endtime2 - starttime2

In [12]:
duration2

datetime.timedelta(seconds=9, microseconds=584649)

In [13]:
CDF['produced_at'] = pd.to_datetime(CDF['produced_at'])

In [14]:
CDF2 = CDF.groupby('variable').resample('1ME', on='produced_at').sum()

/tmp/ipykernel_3538565/2910496379.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  CDF2 = CDF.groupby('variable').resample('1ME', on='produced_at').sum()

In [15]:
gm2 = CDF2.drop(columns="variable").reset_index()

In [17]:
real_cdf = pd.read_csv("CDF.csv")

In [18]:
real_cdf['produced_at'] = pd.to_datetime(real_cdf['produced_at'])

In [19]:
real_cdf2 = real_cdf.groupby('variable').resample('1ME', on='produced_at').sum()

/tmp/ipykernel_3538565/3064651339.py:1: FutureWarning: DataFrameGroupBy.resample operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  real_cdf2 = real_cdf.groupby('variable').resample('1ME', on='produced_at').sum()

In [21]:
real_gm = real_cdf2.drop(columns="variable").reset_index()

In [16]:
gm2.loc[gm2.variable == 'SEE998199911088']

              variable produced_at   value
11796  SEE998199911088  2015-01-31  347848
11797  SEE998199911088  2015-02-28  495932
11798  SEE998199911088  2015-03-31  427360
11799  SEE998199911088  2015-04-30  339184
11800  SEE998199911088  2015-05-31  583308
...                ...         ...     ...
11923  SEE998199911088  2025-08-31  194648
11924  SEE998199911088  2025-09-30  260456
11925  SEE998199911088  2025-10-31  255308
11926  SEE998199911088  2025-11-30  393749
11927  SEE998199911088  2025-12-31   48584

[132 rows x 3 columns]

In [22]:
real_gm.loc[real_gm.variable == 'SEE998199911088']

              variable produced_at     value
23544  SEE998199911088  2015-01-31  347848.0
23545  SEE998199911088  2015-02-28  495932.0
23546  SEE998199911088  2015-03-31  427360.0
23547  SEE998199911088  2015-04-30  339184.0
23548  SEE998199911088  2015-05-31  583308.0
...                ...         ...       ...
23671  SEE998199911088  2025-08-31  194648.0
23672  SEE998199911088  2025-09-30  260456.0
23673  SEE998199911088  2025-10-31  255308.0
23674  SEE998199911088  2025-11-30  393749.0
23675  SEE998199911088  2025-12-31   48584.0

[132 rows x 3 columns]

In [23]:
gm2['year'] = gm2['produced_at']
gm2['month'] = gm2['produced_at']
gm2['year'] = gm2['year'].apply(lambda x: str(x).split("-")[0])
gm2['month'] = gm2['month'].apply(lambda x: int(str(x).split("-")[1]))
gm2['month'] = gm2['month'].astype(int)
gm3 = gm2.sort_values(by=["year", 'month'])
gm4 = gm3.drop(columns='produced_at')
gm5 = gm4.reindex(columns=['year', "month", "variable", "value"])
gm6 = gm5.sort_values(by=["year", 'month'])
gm7 = gm6.rename(columns={"variable":"blockid", "value": "power"})
gm8 = gm7.reset_index(drop=True)

In [32]:
pm1 = gm7.merge(bpm, left_on="blockid", right_on="sseid")
pm2 = pm1.drop('sseid', axis=1)
pm2['plantpower'] = pm2.groupby(['plantid', 'month', 'year'])['power'].transform('sum')
pm3 = pm2.drop_duplicates(['month', 'year', 'plantid'])
pm4 = pm3.drop(['blockid', 'power'], axis=1)

ym1 = pm4.copy()
#ym1.drop_duplicates(['year', 'plantid'], inplace=True)
ym1['yearpower'] = ym1.groupby(['plantid', 'year'])['plantpower'].transform('sum')
ym2 = ym1
ym3 = ym2.drop(['month', 'plantpower'], axis=1)
ym4 = ym3.reset_index(drop=True)

In [33]:
ym4.loc[ym4.plantid == "SN80011277"]

      year     plantid  yearpower
20    2015  SN80011277   10796120
42    2015  SN80011277   10796120
64    2015  SN80011277   10796120
86    2015  SN80011277   10796120
108   2015  SN80011277   10796120
...    ...         ...        ...
2926  2025  SN80011277    7394435
2950  2025  SN80011277    7394435
2974  2025  SN80011277    7394435
2998  2025  SN80011277    7394435
3022  2025  SN80011277    7394435

[132 rows x 3 columns]