In [1]:
import pandas as pd
import numpy as np

In [4]:
pl0 = pd.read_csv("plants_next.csv")

In [5]:
# pl0

In [6]:
pl0.loc[pl0["ersetzt?"] == "Nein"].groupby("ersetzt?").count()

          plantid  name  KWK  Ersatz  Weiterbetrieb  Sonderfall  Unnamed: 7
ersetzt?
Nein            9     9    9       0              1           1           1

In [7]:
pl1 = pl0.groupby(["Ersatz"]).count().reset_index()

In [8]:
pl2 = pl1.rename(columns={ "plantid": "count"})
cols = [2, 3, 4, 5, 6, 7]
pl3 = pl2.drop(pl2.columns[cols],axis=1)

In [9]:
pl3.dtypes

Ersatz    object
count      int64
dtype: object

In [10]:
pl4 = pl3.loc[:]

In [11]:
pl4.loc[pl4.Ersatz=="800x1", 'netpower'] = 80.7
pl4.loc[pl4.Ersatz=="800x2", 'netpower'] = 161.1
pl4.loc[pl4.Ersatz=="9000x1", 'netpower'] = 837.9
pl4.loc[pl4.Ersatz=="9000x2", 'netpower'] = 1675.8

In [12]:
pl4.loc[pl4.Ersatz=="800x1", 'cost'] = 100
pl4.loc[pl4.Ersatz=="800x2", 'cost'] = 200
pl4.loc[pl4.Ersatz=="9000x1", 'cost'] = 450
pl4.loc[pl4.Ersatz=="9000x2", 'cost'] = 800

In [13]:
pl4.dtypes

Ersatz       object
count         int64
netpower    float64
cost        float64
dtype: object

In [14]:
pl5 = pl4.loc[:]

In [15]:
# pl5.loc["totalpower"] = pl5.loc["netpower"] * pl5.loc["count"]
pl5['totalpower'] = pl5["netpower"] * pl5["count"]
pl5['totalcost'] = pl5["cost"] * pl5["count"]
#pl5['totalpower'] =

In [16]:
pl6 = pl5.loc[:]

In [30]:
#pl6['1500'] = (pl6["totalpower"] * 1500) / 10**6
pl6['3000'] = (pl6["totalpower"] * 3000) / 10**6
pl6['4500'] = (pl6["totalpower"] * 4500) / 10**6
#pl6['6000'] = (pl6["totalpower"] * 6000) / 10**6

In [18]:
#pl7 = pl6.loc[:, ["count","netpower","totalpower","1500", "3000", "6000"]]

In [19]:
#pl7

In [22]:
#pl6.append(pl6.sum(numeric_only=True), ignore_index=True)

In [23]:
# newdf['Stilllegung'] = newdf['Stilllegung'].astype(int)
#newdf['Stilllegung'] = newdf['Stilllegung'].apply(lambda x: int(x) if x == x else None)

In [24]:
sgt5_800 = pl0.loc[np.logical_or(pl0.Ersatz == "800x1", pl0.Ersatz == "800x2")]
#sgt5_800 = sgt5_800.loc[sgt5_800.Weiterbetrieb != "Ja"]

In [25]:
#sgt5_800

In [26]:
sgt5_9000 = pl0.loc[np.logical_or(pl0.Ersatz == "9000x1", pl0.Ersatz == "9000x2")]
#sgt5_800 = sgt5_800.loc[sgt5_800.Weiterbetrieb != "Ja"]

In [27]:
#sgt5_9000

In [28]:
#for row in sgt5_9000.iterrows():
    #print(row == pl0.iloc[0])
    #print(type(row[1]))
    #print("\n")
    #print(sgt5_9000.iloc[0])
    #break

In [31]:
sgt5_800

,plantid,name,KWK,ersetzt?,Ersatz,Weiterbetrieb,Sonderfall,Unnamed: 7
0,00-50-56050192711,Wedel,Ja,Ja,800x2,NaN,Ja,NaN
1,06-05-900-0884101,KW Lünen,Ja,Ja,800x2,NaN,NaN,NaN
2,06-05-300-9046796,G Kraftwerk,Ja,Ja,800x1,NaN,NaN,NaN
3,06-10-0075248,Ensdorf,Ja,Ja,800x1,NaN,NaN,NaN
5,06-05-300-0326774,Niederaußem,Ja,Ja,800x2,NaN,Ja,NaN
7,06-05-100-0081105,Frimmersdorf,Teil,Ja,800x1,NaN,NaN,NaN
8,06-05-900-0327252,KW Herne,Ja,Ja,800x2,NaN,NaN,NaN
14,06-05-100-9021016,Kraftwerk L/N,Ja,Ja,800x1,NaN,NaN,NaN
15,06-05-100-0248923,Neurath,Ja,Ja,800x2,NaN,Ja,NaN
17,14-70-46630660001,Boxberg,Teil,Ja,800x2,NaN,Ja,NaN
18,06-09-500-0112-0001,HKW Erlangen,Ja,Ja,800x1,NaN,NaN,NaN
19,06-05-900-0205103,Bergkamen,Ja,Ja,800x1,NaN,NaN,NaN
27,03-01-01010157480,HKW Mitte,Ja,Ja,800x1,NaN,NaN,NaN
28,06-05-500-0338944,Ibbenbüren,Ja,Ja,800x1,NaN,NaN,NaN
30,06-08-1741292,HKW Altbach/Deizau,Ja,Ja,800x2,Ja,NaN,NaN
31,06-05-100-0031758,HKW 1,Ja,Ja,800x1,NaN,NaN,NaN
34,06-11-01-1105609,Reuter West,Ja,Ja,800x2,NaN,NaN,NaN
35,06-05-100-0365906,KW Walsum,Ja,Ja,800x2,Ja,NaN,NaN
36,14-60-48821410003,HWK Chemnitz Nord,Ja,Ja,800x2,NaN,NaN,NaN
37,06-14600010611,FKK,Ja,Ja,800x1,NaN,NaN,NaN
38,03-06-06060316030,GKH,Ja,Ja,800x2,NaN,NaN,NaN
39,06-05-100-0030723,HKW Elberfeld,Ja,Ja,800x1,NaN,NaN,NaN
41,06-08-3042693,HKW Pforzheim,Ja,Ja,800x1,NaN,NaN,NaN
43,06-00176010435,Staudinger,Ja,Ja,800x1,NaN,NaN,NaN
45,06-05-800-0203946,Goldenberg,Ja,Ja,800x1,NaN,NaN,NaN
46,13-30-1010101,Rostock,Ja,Ja,800x1,NaN,NaN,NaN
47,12358,Schkopau,Ja,Ja,800x1,NaN,Ja,NaN
48,07-05-8030815,HKW Karcherstr.,Ja,Ja,800x1,NaN,NaN,NaN
50,12-30532000000,HKW FFO,Ja,Ja,800x1,NaN,NaN,NaN
51,14-80-00009560000,Lippendorf,Ja,Ja,800x2,NaN,Ja,NaN

In [29]:
sgt5_9000

,plantid,name,KWK,ersetzt?,Ersatz,Weiterbetrieb,Sonderfall,Unnamed: 7
4,06-05-300-0877384,Weisweiler,Ja,Ja,9000x1,NaN,NaN,NaN
6,06-08-1020129,HKW Heilbronn,Ja,Ja,9000x1,NaN,NaN,NaN
20,12-40710010000,KW Jänschwalde,Ja,Ja,9000x2,NaN,Ja,NaN
23,06-08-2948214,GKM,Ja,Ja,9000x1,NaN,Ja,NaN
32,06-09-100-0003-0003,Zolling,Ja,Ja,9000x1,NaN,NaN,NaN
42,06-09-100-0088-0001,Nord 2,Ja,Ja,9000x1,NaN,NaN,NaN
49,12-40716440000,Schwarze Pumpe,Ja,Ja,9000x1,NaN,Ja,NaN