In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
import json
import os
import re
from sqlalchemy import create_engine
import sqlite3

In [2]:
cnx = sqlite3.connect('../data/plantwatch2.db')

df = pd.read_sql_query("SELECT * FROM blocks", cnx)

In [3]:
df

,blockid,plantid,blockname,federalstate,energysource,initialop,chp,netpower,state,endop,company,reserveyear
0,SEE970820981745,,"Kraftwerk VI, Block 62, DT620",Nordrhein-Westfalen,Erdgas,2022,Ja,36.900,in Betrieb,,Evonik Operations GmbH,
1,SEE969511682320,12-30532000000,HKW FFO GM2,Brandenburg,Erdgas,2022,Ja,10.100,in Betrieb,,Stadtwerke Frankfurt (Oder) GmbH,
2,SEE948351715917,06-05-900-0327252,GuD Herne,Nordrhein-Westfalen,Erdgas,2022,Nein,657.000,in Betrieb,,GuD Herne,
3,SEE965660903200,,Gasmotoren-Heizkraftwerk Dresden-Reick - Aggre...,Sachsen,Erdgas,2022,Nein,11.300,in Betrieb,,DREWAG - Stadtwerke Dresden GmbH,
4,SEE911129038174,,BHKW-Anlage,Brandenburg,Erdgas,2022,Ja,53.481,in Betrieb,,Stadtwerke Cottbus GmbH,
...,...,...,...,...,...,...,...,...,...,...,...,...
1437,SEE996946209945,,P12,Baden-Württemberg,Erdgas,1939,Nein,4.315,in Betrieb,,Caterpillar Energy Solutions,
1438,SEE936364054154,,P18,Baden-Württemberg,Erdgas,1939,Nein,4.315,in Betrieb,,Caterpillar Energy Solutions,
1439,SEE999977738880,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,1936,Ja,67.000,stillgelegt KVBG,2021,,
1440,SEE957723162266,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,1900,Ja,25.000,in Betrieb,,SWK Stadtwerke Kaiserslautern Versorgungs-AG,
1441,BNA1337a,06-09-661-0020-0001,Heizkraftwerk,Bayern,Erdgas,,Ja,27.000,stillgelegt,2012,,

In [4]:
df3 = df[['plantid', 'blockid']]

In [5]:
df4 = df3.replace(r'', np.nan)

In [6]:
df5 = df4.dropna(subset=['plantid'])

In [7]:
df5.sort_values('plantid').reset_index(drop=True)

               plantid          blockid
0    01-50-01000004838          BNA0269
1    01-50-01000004838  SEE990438768378
2    01-50-01000004838  SEE957285549260
3    01-50-01000004838          BNA0274
4    01-50-01000004838          BNA0273
..                 ...              ...
936             666-16  SEE943690268513
937             666-17  SEE944567587799
938             666-18  SEE985577062814
939             669-01  SEE950675787617
940             669-01  SEE983645175053

[941 rows x 2 columns]

In [8]:
df5.duplicated()

1       False
2       False
5       False
6       False
10      False
        ...
1421    False
1431    False
1439    False
1440    False
1441    False
Length: 941, dtype: bool

In [9]:
df5.to_csv("../basic/plant_sse_mapper.csv", index=False)