In [22]:
import pandas as pd
import psycopg
from sqlalchemy import create_engine, inspect, DateTime
from datetime import datetime

In [23]:
engine2 = create_engine('postgresql+psycopg://smardlog:N0m1596.@127.0.0.1/smardlog')
smardlog = pd.read_sql_table('smardlog', engine2)

In [24]:
datetime.now()

datetime.datetime(2025, 5, 2, 22, 44, 41, 202979)

In [25]:
dt = pd.read_csv("Datteln_202503010000_202504302359_Stunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
dt.fillna(0.0, inplace=True)

In [26]:
avg_power = dt["Generation_DE Datteln 4 [MW] Originalauflösungen"].sum() / len(dt)
avg_price = (smardlog["price"].sum() / len(smardlog)) or 120

In [27]:
avg_price

np.float64(66.6506306620209)

In [28]:
revenue_per_hour = avg_power * avg_price

In [29]:
revenue_per_hour or 35496.23

np.float64(27864.792712316106)

In [30]:
revenue_per_hour * 24 * 30 / 1000000

np.float64(20.062650752867597)

In [31]:
coal_cost_per_t = 103.5

In [32]:
coal_per_co2 = 1/2.68 # https://www.bund-nrw.de/braunkohle/hintergruende-und-publikationen/braunkohlenkraftwerke-contra-klimaschutz/

In [33]:
co2s = 2945000

In [34]:
(co2s  / 12) * coal_per_co2 * coal_cost_per_t / 1000000 * 12

113.73414179104475

In [108]:
co2cert_price = 70

In [109]:
co2cert_cost = co2cert_price * (co2s - 631)

In [110]:
co2cert_cost / 1000000 / 12

17.175485833333333

In [111]:
smardlog

      id           timestamp    price
0      3 2025-03-06 18:00:00  148.950
1      4 2025-03-06 19:00:00  165.360
2      5 2025-03-14 14:00:00  104.590
3      6 2025-03-19 10:00:00   79.500
4      7 2025-03-19 15:00:00    0.990
..   ...                 ...      ...
256  251 2025-05-01 08:00:00   73.020
257  177 2025-04-28 05:00:00   92.450
258  216 2025-04-29 20:00:00  138.375
259  262 2025-05-01 19:00:00   96.140
260  263 2025-05-01 20:00:00  129.870

[261 rows x 3 columns]

In [112]:
dt2 = dt[["Datum von", "Generation_DE Datteln 4 [MW] Originalauflösungen"]]

In [113]:
dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))

/tmp/ipykernel_24964/1434537718.py:1: UserWarning: Parsing dates in %d.%m.%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))
/tmp/ipykernel_24964/1434537718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))

In [114]:
dt2

               Datum von  Generation_DE Datteln 4 [MW] Originalauflösungen
0    2025-01-03 00:00:00                                               0.0
1    2025-01-03 01:00:00                                               0.0
2    2025-01-03 02:00:00                                               0.0
3    2025-01-03 03:00:00                                               0.0
4    2025-01-03 04:00:00                                               0.0
...                  ...                                               ...
1458 2025-04-30 19:00:00                                               0.0
1459 2025-04-30 20:00:00                                               0.0
1460 2025-04-30 21:00:00                                               0.0
1461 2025-04-30 22:00:00                                               0.0
1462 2025-04-30 23:00:00                                               0.0

[1463 rows x 2 columns]

In [115]:
df1 = pd.merge(smardlog, right=dt2, left_on="timestamp", right_on="Datum von")

In [116]:
df1["Generation_DE Datteln 4 [MW] Originalauflösungen"] = df1["Generation_DE Datteln 4 [MW] Originalauflösungen"].apply(lambda x: int(x))

In [117]:
df1["revenue"] = df1.price * df1["Generation_DE Datteln 4 [MW] Originalauflösungen"]

In [118]:
df1["revenue"].sum()

np.float64(5199809.0600000005)