In [36]:
import pandas as pd
import psycopg
from sqlalchemy import create_engine, inspect, DateTime
from datetime import datetime

In [37]:
engine2 = create_engine('postgresql+psycopg://smardlog:N0m1596.@127.0.0.1/smardlog')
smardlog = pd.read_sql_table('smardlog', engine2)

In [38]:
datetime.now()

datetime.datetime(2025, 4, 29, 11, 38, 36, 195159)

In [39]:
dt = pd.read_csv("Datteln_202503010000_202504242359_Stunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
dt.fillna(0.0, inplace=True)

In [40]:
avg_power = dt["Generation_DE Datteln 4 [MW] Originalauflösungen"].sum() / len(dt)

In [41]:
avg_price = (smardlog["price"].sum() / len(smardlog)) or 120

In [42]:
avg_price

np.float64(69.7132780487805)

In [43]:
revenue_per_hour = avg_power * avg_price

In [44]:
revenue_per_hour or 35496.23

np.float64(29669.52717127166)

In [45]:
revenue_per_hour * 24 * 30 / 1000000

np.float64(21.362059563315594)

In [46]:
coal_cost_per_t = 103.5

In [47]:
coal_per_co2 = 1/2.68 # https://www.bund-nrw.de/braunkohle/hintergruende-und-publikationen/braunkohlenkraftwerke-contra-klimaschutz/

In [48]:
co2s = 2945000

In [49]:
(co2s  / 12) * coal_per_co2 * coal_cost_per_t / 1000000 * 12

113.73414179104475

In [50]:
co2cert_price = 70

In [196]:
co2cert_cost = co2cert_price * (co2s - 631)

In [197]:
co2cert_cost / 1000000 / 12

17.175485833333333

In [85]:
smardlog

      id           timestamp   price
0      3 2025-03-06 18:00:00  148.95
1      4 2025-03-06 19:00:00  165.36
2      5 2025-03-14 14:00:00  104.59
3      6 2025-03-19 10:00:00   79.50
4      7 2025-03-19 15:00:00    0.99
..   ...                 ...     ...
154  157 2025-04-27 09:00:00   34.95
155  158 2025-04-27 10:00:00    0.04
156  159 2025-04-27 11:00:00   -3.00
157  160 2025-04-27 12:00:00  -33.88
158  161 2025-04-27 13:00:00 -101.04

[159 rows x 3 columns]

In [19]:
dt2 = dt[["Datum von", "Generation_DE Datteln 4 [MW] Originalauflösungen"]]

In [20]:
dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))

/tmp/ipykernel_835797/1434537718.py:1: UserWarning: Parsing dates in %d.%m.%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))
/tmp/ipykernel_835797/1434537718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt2["Datum von"] = dt2["Datum von"].apply(lambda x: pd.to_datetime(x))

In [21]:
dt2

               Datum von  Generation_DE Datteln 4 [MW] Originalauflösungen
0    2025-01-03 00:00:00                                               0.0
1    2025-01-03 01:00:00                                               0.0
2    2025-01-03 02:00:00                                               0.0
3    2025-01-03 03:00:00                                               0.0
4    2025-01-03 04:00:00                                               0.0
...                  ...                                               ...
1314 2025-04-24 19:00:00                                               0.0
1315 2025-04-24 20:00:00                                               0.0
1316 2025-04-24 21:00:00                                               0.0
1317 2025-04-24 22:00:00                                               0.0
1318 2025-04-24 23:00:00                                               0.0

[1319 rows x 2 columns]

In [22]:
df1 = pd.merge(smardlog, right=dt2, left_on="timestamp", right_on="Datum von")

In [23]:
df1["Generation_DE Datteln 4 [MW] Originalauflösungen"] = df1["Generation_DE Datteln 4 [MW] Originalauflösungen"].apply(lambda x: int(x))

In [24]:
df1["revenue"] = df1.price * df1["Generation_DE Datteln 4 [MW] Originalauflösungen"]

In [25]:
df1["revenue"].sum()

np.float64(3762599.8499999996)