In [1]:
import pandas as pd
from helpers import get_factor, get_price
pd.options.mode.chained_assignment = None

In [2]:
CDF = pd.read_csv("../production-v2/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
#CDF.sort_values(by=["produced_at", "variable"])

In [4]:
smard = pd.read_csv("Gro_handelspreise_202301010000_202401010000_Viertelstunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [5]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [6]:
CDF2 = CDF.loc[CDF.produced_at > "2022-12-31 23:50"].loc[CDF.produced_at < "2024-01-01 00:00"]

In [7]:
CDF3 = CDF2.loc[~(CDF.variable == "Unnamed: 3")]

In [8]:
#CDF3 = CDF2.dropna()

In [9]:
len(CDF2) - len(CDF3)

35036

In [10]:
len(CDF2.groupby('produced_at').sum())

35036

In [11]:
dataset = CDF3.merge(seem, left_on="variable", right_on="sseid")

In [12]:
magic = dataset.groupby(["produced_at", "plantid"]).sum()

In [13]:
#magic

In [14]:
magic2 = magic[["value"]]

In [15]:
#magic2.sort_values(["produced_at", "value"])

In [16]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [17]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")
merged["revenue"] = merged["value"] * merged["price"]

In [18]:
#merged

In [19]:
#production.sort_values(by=["plantid", "produced_at"])

In [20]:
#merged1a

In [21]:

#merged_tmp = merged.drop(columns=["timestamp"])
#merged1a = merged_tmp.set_index("produced_at", drop=True)

In [22]:
#merged1a = merged_tmp.set_index(['plantid']).sort_values(['plantid', 'produced_at'])

In [23]:
#merged2 = merged1a.resample("1h", on="produced_at").agg({'value':'sum', 'price':'sum', 'revenue': 'sum' })

In [24]:
#merged1a

In [25]:
#tmp1 = merged2.copy()
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [26]:
tmp1.reset_index(inplace=True)

In [27]:
revenue = tmp1[["plantid", "revenue"]]

In [28]:
tmp1

                      plantid       value       price       revenue
0            06-02-B10117A007    707521.0   833736.96  6.933753e+07
1                  BB23020490   1163264.0  3334947.84  1.106459e+08
2                  BB45025564  11579284.0  3334947.84  1.180307e+09
3                  BB45025611   8443056.0   833736.96  8.770335e+08
4                    BE166928   1269720.0  3334947.84  1.269227e+08
5                    BE169709    347644.0   833736.96  3.511908e+07
6                    BE172654   1365724.0  3334947.84  1.427438e+08
7                    BE172656   1135173.0   833736.96  1.200585e+08
8   BWpf-450-1020129-00000000    306092.0  3334947.84  4.390331e+07
9   BWpf-450-1195689-00000000    186372.0  3334947.84  1.825098e+07
10  BWpf-450-1741292-00000000    540072.0  3334947.84  5.635460e+07
11  BWpf-450-2142201-00000000     13692.0  3334947.84  2.273751e+06
12  BWpf-450-2797933-00000000   2548124.0  3334947.84  2.658222e+08
13  BWpf-450-2948214-00000000   2328411.0   833736.96  2.478733e+08
14                   BYS00009   1273335.0   833736.96  1.481345e+08
15                   BYS00041   1145668.0   833736.96  1.135340e+08
16                   BYS00044    792612.0  3334947.84  8.894644e+07
17                   BYS00048   2846692.0  3334947.84  3.412782e+08
18                   BYS00114    167731.0   833736.96  1.665064e+07
19                   BYS00727     60018.0   833736.96  7.220972e+06
20                 HE30001045   1018041.0   833736.96  1.140684e+08
21                 HE50001960    357840.0   833736.96  4.669283e+07
22                 MV30000226   1141292.0  3334947.84  1.354623e+08
23              NI01010098080    609549.0   833736.96  7.624635e+07
24              NI01241117210   1191734.0   833736.96  1.188421e+08
25              NI06060316030   1117000.0  3334947.84  1.140893e+08
26              NI10257673950   3820312.0   833736.96  4.314819e+08
27              NW100-0167182   2384732.0  3334947.84  2.663114e+08
28              NW100-0229264    395406.0   833736.96  4.550117e+07
29              NW100-0248923  15022470.0   833736.96  1.581932e+09
30              NW100-0365906   1229773.0   833736.96  1.503140e+08
31              NW300-0326774  11693868.0  3334947.84  1.245726e+09
32              NW300-0370387   1999677.0   833736.96  2.165069e+08
33              NW300-0877384   7312424.0   833736.96  7.860647e+08
34              NW300-0923949         0.0  3334947.84  0.000000e+00
35              NW300-9002708    902660.0  3334947.84  1.025774e+08
36              NW300-9046030    587200.0   833736.96  6.915468e+07
37              NW500-0342658   1198168.0   833736.96  1.186812e+08
38              NW500-0915123   3397300.0  3334947.84  3.616583e+08
39              NW700-0105516   1116943.0   833736.96  1.406075e+08
40              NW900-0125939    565667.0   833736.96  6.969710e+07
41              NW900-0205103    834744.0   833736.96  1.078629e+08
42              NW900-0327252    584248.0   833736.96  6.487863e+07
43              NW900-0865327     10623.0   833736.96  1.625273e+06
44              NW900-9140178    918998.0   833736.96  1.073103e+08
45                  RP5000671   2143988.0  3334947.84  2.182205e+08
46                   SD661-06     18948.0   833736.96  2.738489e+06
47                   SD661-18    270939.0   833736.96  2.671743e+07
48                   SD666-16   2831770.0   833736.96  2.920567e+08
49                   SD666-17   2103067.0   833736.96  2.017425e+08
50                   SD666-18   1778014.0   833736.96  1.867304e+08
51                SL0100999-G    833290.0   833736.96  9.471677e+07
52                SL0101000-G    111729.0   833736.96  1.451570e+07
53                SL0101003-G    634532.0   833736.96  7.181150e+07
54                SL0105352-G    141928.0   833736.96  1.597176e+07
55                 SN70015796  11807600.0  3334947.84  1.202545e+09
56                   ST100125   3047500.0  3334947.84  3.309365e+08

In [29]:
#dataset.sort_values(["plantid", "produced_at"])

In [30]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [31]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [32]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2023].loc[co2s.pollutant == "CO2"]

In [33]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [34]:
co2s2

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
52,2023,BB16018798,CO2,Air,2.850000e+08,9,Mio. t,0.285,CO2 [Mio. t]
84,2023,BB23020389,CO2,Air,4.340000e+08,9,Mio. t,0.434,CO2 [Mio. t]
163,2023,BB23020490,CO2,Air,3.015000e+09,9,Mio. t,3.015,CO2 [Mio. t]
369,2023,BB23022811,CO2,Air,1.500000e+08,9,Mio. t,0.150,CO2 [Mio. t]
411,2023,BB45025564,CO2,Air,1.413400e+10,9,Mio. t,14.134,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
15336,2023,ST18046,CO2,Air,2.210000e+08,9,Mio. t,0.221,CO2 [Mio. t]
15459,2023,TH30013152,CO2,Air,2.620000e+08,9,Mio. t,0.262,CO2 [Mio. t]
15490,2023,TH62013494,CO2,Air,1.290000e+08,9,Mio. t,0.129,CO2 [Mio. t]
15566,2023,TH72012874,CO2,Air,1.770000e+08,9,Mio. t,0.177,CO2 [Mio. t]
15599,2023,TH86012942,CO2,Air,1.110000e+08,9,Mio. t,0.111,CO2 [Mio. t]

In [35]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [36]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [37]:
tmp2 = pd.merge(tmp1, production, on="plantid")

In [38]:
tmp2 = tmp1

In [39]:
coal_cost_per_t = 103.5# or 120
co2_cost = 70
#electricity_price = 78.50

In [40]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [41]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [42]:
#tmp2.sort_values(by="free_co2s", ascending=False)

In [43]:
profit = tmp2[["plantid", "plantname", "revenue", "profit"]]
profit["revenue"] = profit["revenue"].apply(lambda x: x / 10**6)

In [44]:
#profit.to_csv("profit.csv", index=False)

In [46]:
profit.sort_values("profit", ascending=True)

,plantid,plantname,revenue,profit
42,RP5000671,GuD Mitte DT10,218.220516,-265.692818
0,BB23020490,1MKA,110.645937,-198.719281
12,BWpf-450-2948214-00000000,GKM Block 6,247.873328,-139.366872
35,NW500-0342658,Scholven 1 DT,118.681204,-106.696332
11,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,265.822193,-99.739748
14,BYS00041,SWM HKW Nord 2 T20,113.533971,-88.499362
20,MV30000226,Kraftwerk Rostock Block A,135.462265,-61.858110
9,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,56.354601,-46.208461
3,BE166928,HKW Reuter West Dampfturbine D,126.922714,-46.158883
22,NI01241117210,DT30 GuD Süd Wolfsburg,118.842134,-45.172941
17,BYS00114,Gasturbinenanlage 12,16.650636,-42.992697
23,NI06060316030,GKH 1,114.089336,-33.512753
8,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,18.250977,-33.168725
40,NW900-0327252,GuD Herne,64.878627,-22.695552
32,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-21.150769
10,BWpf-450-2142201-00000000,Kraftwerk Walheim Block 2,2.273751,-10.695950
7,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,43.903306,-4.876545
45,SL0101003-G,Weiher 3,71.811503,-3.137303
44,SL0101000-G,Gasmotor 1 Mod.,14.515700,-0.634748
4,BE169709,HKW Klingenberg Dampfturbine 1,35.119077,1.584554
18,HE30001045,Staudinger 4,114.068429,3.079921
46,SL0105352-G,Dampfturbinenanlage DT3,15.971755,6.015088
43,SL0100999-G,Bexbach,94.716769,8.060799
28,NW100-0365906,Walsum 10,150.313953,8.673461
21,NI01010098080,KWM Block 3,76.246352,9.790979
13,BYS00009,Kraftwerk Zolling,148.134540,14.994242
39,NW900-0205103,Bergkamen A,107.862887,15.156963
37,NW700-0105516,Heyden 4,140.607513,20.551693
36,NW500-0915123,Datteln 4,361.658330,23.686828
26,NW100-0229264,HKW III Block A,45.501172,26.009595
19,HE50001960,G20,46.692828,32.386161
34,NW300-9046030,Knapsack I - Dampfturbine - DT 10,69.154685,32.711351
48,ST100125,Schkopau A,330.936473,34.231357
33,NW300-9002708,Dormagen DT,102.577362,34.671523
38,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,69.697102,46.400435
15,BYS00044,SWM HKW Sued GuD1 GT2,88.946444,51.536444
6,BE172656,GuD Marzahn Dampfturbine,120.058472,65.202539
41,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,107.310336,74.057003
5,BE172654,HKW Mitte Dampfturbine,142.743825,80.999075
31,NW300-0877384,Weisweiler F,786.064712,81.693246
1,BB45025564,Kraftwerk Jänschwalde Block A,1180.306888,113.483473
30,NW300-0370387,DT Niehl 2 RheinEnergie,216.506863,117.616863
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,877.033454,157.876547
25,NW100-0167182,SWD KWF GTKW,266.311410,179.601410
47,SN70015796,Boxberg Block N,1202.545192,214.323757
16,BYS00048,Irsching 5 DT,341.278167,232.044833
29,NW300-0326774,Niederaußem G,1245.726455,242.056864
24,NI10257673950,Emsland B DT,431.481929,295.721155
27,NW100-0248923,Neurath F,1581.931513,336.890044