In [1]:
import pandas as pd
from helpers import get_factor, get_price
pd.options.mode.chained_assignment = None

In [2]:
CDF = pd.read_csv("../production-v2/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [3]:
#CDF.sort_values(by=["produced_at", "variable"])

In [4]:
smard = pd.read_csv("Gro_handelspreise_202401010000_202501010000_Viertelstunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [5]:
smardlog.dtypes

timestamp    datetime64[ns]
price               float64
dtype: object

In [6]:
smardlog.to_excel("GHP_2023.xlsx")

In [7]:
smardlog.describe()

                           timestamp         price
count                          35136  35136.000000
mean   2024-07-02 00:26:55.573770496     78.512033
min              2024-01-01 00:00:00   -135.450000
25%              2024-04-01 12:56:15     55.560000
50%              2024-07-02 00:52:30     79.585000
75%              2024-10-01 12:48:45    101.340000
max              2024-12-31 23:45:00    936.280000
std                              NaN     52.724158

In [8]:
smardlog.sort_values('price')

                timestamp   price
12721 2024-12-05 13:15:00 -135.45
12722 2024-12-05 13:30:00 -135.45
12723 2024-12-05 13:45:00 -135.45
12720 2024-12-05 13:00:00 -135.45
12725 2024-12-05 14:15:00 -132.85
...                   ...     ...
29831 2024-06-11 17:45:00  820.11
33287 2024-12-12 17:45:00  936.28
33286 2024-12-12 17:30:00  936.28
33285 2024-12-12 17:15:00  936.28
33284 2024-12-12 17:00:00  936.28

[35136 rows x 2 columns]

In [9]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [10]:
#co2s['year'] = co2s['year'] + 1

In [11]:
#co2s

In [12]:
CDF2 = CDF.loc[CDF.produced_at > "2023-12-31 23:50"].loc[CDF.produced_at < "2025-01-01 00:00"]

In [13]:
CDF2['produced_at'] = pd.to_datetime(CDF2['produced_at'])

In [14]:
CDF2

                 produced_at         variable  value
78879    2024-01-01 00:00:00  SEE913896693631    0.0
78880    2024-01-01 01:00:00  SEE913896693631    0.0
78881    2024-01-01 02:00:00  SEE913896693631    0.0
78882    2024-01-01 03:00:00  SEE913896693631    0.0
78883    2024-01-01 04:00:00  SEE913896693631    0.0
...                      ...              ...    ...
43493831 2024-12-31 22:45:00  SEE960652233358    0.0
43493832 2024-12-31 23:00:00  SEE960652233358    0.0
43493833 2024-12-31 23:15:00  SEE960652233358    0.0
43493834 2024-12-31 23:30:00  SEE960652233358    0.0
43493835 2024-12-31 23:45:00  SEE960652233358    0.0

[3899652 rows x 3 columns]

In [15]:
CDF2a = CDF2.copy()#loc[~(CDF2.variable.str.contains("Unnamed"))]

In [16]:
#CDF2b = CDF2a.groupby('variable').resample('1h', on='produced_at').mean()

In [17]:
CDF3 = CDF2a

In [18]:
#CDF3 = CDF2.dropna()

In [19]:
len(CDF2) - len(CDF3)

0

In [20]:
len(CDF2.groupby('produced_at').sum())

35132

In [21]:
dataset = CDF3.merge(seem, left_on="variable", right_on="sseid", how="inner")

In [22]:
dataset2 = dataset.drop_duplicates(subset=['produced_at', 'variable'])

In [23]:
len(dataset)

3750341

In [24]:
dataset

,produced_at,variable,value,plantid,sseid
0,2024-01-01 00:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
1,2024-01-01 01:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
2,2024-01-01 02:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
3,2024-01-01 03:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
4,2024-01-01 04:00:00,SEE913896693631,0.0,06-02-B10117A007,SEE913896693631
...,...,...,...,...,...
3750336,2024-12-31 22:45:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750337,2024-12-31 23:00:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750338,2024-12-31 23:15:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750339,2024-12-31 23:30:00,SEE960652233358,0.0,ST100125,SEE960652233358
3750340,2024-12-31 23:45:00,SEE960652233358,0.0,ST100125,SEE960652233358

In [25]:
magic = dataset2.groupby(["produced_at", "plantid"]).sum()

In [26]:
#magic

In [27]:
magic2 = magic[["value"]]

In [28]:
#magic2.sort_values(["produced_at", "value"])

In [29]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [30]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")
merged["revenue"] = merged["value"] * merged["price"]

In [31]:
merged_mytmp = merged[['produced_at', 'plantid', 'value', 'price', 'revenue']]

In [32]:
merged_mytmp.loc[merged_mytmp.plantid == "BB45025564"].sort_values('revenue').resample('1YE', on='produced_at').sum()

,plantid,value,price,revenue
produced_at,,,,
2024-12-31,BB45025564BB45025564BB45025564BB45025564BB4502...,9559700.0,2758598.8,8.005455e+08

In [33]:
#merged1a = merged.groupby('plantid').resample('1h', on='produced_at').mean().reset_index()

In [34]:
#merged1a.sort_values('revenue')

In [35]:
#merged

In [36]:
#production.sort_values(by=["plantid", "produced_at"])

In [37]:
#merged1a

In [38]:

#merged_tmp = merged.drop(columns=["timestamp"])
#merged1a = merged_tmp.set_index("produced_at", drop=True)

In [39]:
#merged1a = merged_tmp.set_index(['plantid']).sort_values(['plantid', 'produced_at'])

In [40]:
#merged2 = merged1a.resample("1h", on="produced_at").agg({'value':'sum', 'price':'sum', 'revenue': 'sum' })

In [41]:
#merged1a

In [42]:
#tmp1 = merged2.copy()
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [43]:
tmp1.reset_index(inplace=True)

In [44]:
revenue = tmp1[["plantid", "revenue"]]

In [45]:
tmp1

                      plantid       value      price       revenue
0            06-02-B10117A007    637346.0   689649.7  5.288343e+07
1                  BB23020490   1376356.0  2758598.8  1.086602e+08
2                  BB45025564   9559700.0  2758598.8  8.005455e+08
3                  BB45025611   7007511.0   689649.7  6.055226e+08
4                    BE166928   1171476.0  2758598.8  9.504822e+07
5                    BE169709    362015.0   689649.7  3.070577e+07
6                    BE172654   1297508.0  2758598.8  1.158482e+08
7                    BE172656    962853.0   689649.7  8.590997e+07
8   BWpf-450-1020129-00000000    593836.0  2758598.8  6.110538e+07
9   BWpf-450-1195689-00000000    205400.0  2758598.8  1.626545e+07
10  BWpf-450-1741292-00000000    487424.0  2758598.8  4.878585e+07
11  BWpf-450-2142201-00000000     20988.0  2758598.8  3.107986e+06
12  BWpf-450-2797933-00000000   2077640.0  2758598.8  1.949110e+08
13  BWpf-450-2948214-00000000   1927636.0   689649.7  1.721634e+08
14                   BYS00009    996180.0   689649.7  1.027118e+08
15                   BYS00041    758068.0   689649.7  6.431633e+07
16                   BYS00044   1075856.0  2758598.8  9.900856e+07
17                   BYS00048   3458496.0  2758598.8  3.595232e+08
18                   BYS00114    141668.0   689649.7  1.151014e+07
19                   BYS00727    154566.0   689649.7  2.284722e+07
20                 HE30001045    291623.0   689649.7  2.140724e+07
21                 MV30000226    641708.0  2758598.8  7.165928e+07
22              NI01010098080    498280.0   689649.7  4.114252e+07
23              NI01241117210    467977.0   689649.7  3.552431e+07
24              NI06060316030    934480.0  2758598.8  8.169654e+07
25              NI10257673950   2981610.0   689649.7  2.827623e+08
26              NW100-0167182   2640068.0  2758598.8  2.456223e+08
27              NW100-0229264    336060.0   689649.7  3.269475e+07
28              NW100-0248923  12631284.0   689649.7  1.093000e+09
29              NW100-0365906    392952.0   689649.7  3.694577e+07
30              NW300-0326774  10407704.0  2758598.8  9.262812e+08
31              NW300-0370387   2247607.0   689649.7  1.942240e+08
32              NW300-0877384   8193258.0   689649.7  7.522053e+08
33              NW300-0923949         0.0  2758598.8  0.000000e+00
34              NW300-9002708   1401460.0  2758598.8  1.310311e+08
35              NW300-9046030   1136896.0   689649.7  1.241809e+08
36              NW500-0342658    353192.0   689649.7  2.653052e+07
37              NW500-0915123   1999908.0  2758598.8  1.615442e+08
38              NW700-0105516    212496.0   689649.7  1.775971e+07
39              NW900-0125939    782046.0   689649.7  8.414225e+07
40              NW900-0205103    232316.0   689649.7  2.082932e+07
41              NW900-0327252    143684.0   689649.7  1.109757e+07
42              NW900-0865327      8569.0   689649.7  1.338652e+06
43              NW900-9140178   1287514.0   689649.7  1.370171e+08
44              NW900-9141660   2557468.0  2758598.8  2.492269e+08
45                  RP5000671   1868048.0  2758598.8  1.576855e+08
46                   SD661-06     16012.0   689649.7  2.357491e+06
47                   SD661-18    300566.0   689649.7  2.398127e+07
48                   SD661-94    864190.0   689649.7  7.387270e+07
49                SL0100999-G    262692.0   689649.7  2.155009e+07
50                SL0101000-G     17196.0   689649.7  1.556536e+06
51                SL0101003-G    160123.0   689649.7  1.084055e+07
52                SL0105352-G    137404.0   689649.7  1.230613e+07
53                 SN70015796  12664788.0  2758598.8  1.069532e+09
54                 SN80011277   5887548.0  2758598.8  5.327062e+08
55                   ST100125   3309276.0  2758598.8  3.006925e+08

In [46]:
#dataset.sort_values(["plantid", "produced_at"])

In [47]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [48]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [49]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2023].loc[co2s.pollutant == "CO2"]

In [50]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [51]:
co2s2

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
56,2023,BB16018798,CO2,Air,2.850000e+08,9,Mio. t,0.285,CO2 [Mio. t]
92,2023,BB23020389,CO2,Air,4.340000e+08,9,Mio. t,0.434,CO2 [Mio. t]
181,2023,BB23020490,CO2,Air,3.015000e+09,9,Mio. t,3.015,CO2 [Mio. t]
388,2023,BB23022811,CO2,Air,1.500000e+08,9,Mio. t,0.150,CO2 [Mio. t]
443,2023,BB45025564,CO2,Air,1.413400e+10,9,Mio. t,14.134,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
16135,2023,ST18046,CO2,Air,2.210000e+08,9,Mio. t,0.221,CO2 [Mio. t]
16260,2023,TH30013152,CO2,Air,2.620000e+08,9,Mio. t,0.262,CO2 [Mio. t]
16293,2023,TH62013494,CO2,Air,1.290000e+08,9,Mio. t,0.129,CO2 [Mio. t]
16371,2023,TH72012874,CO2,Air,1.770000e+08,9,Mio. t,0.177,CO2 [Mio. t]
16405,2023,TH86012942,CO2,Air,1.110000e+08,9,Mio. t,0.111,CO2 [Mio. t]

In [52]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [53]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [54]:
tmp2 = pd.merge(tmp1, production, on="plantid")

In [55]:
tmp2 = tmp1

In [56]:
coal_cost_per_t = 103.5# or 120
co2_cost = 65 # https://icapcarbonaction.com/system/files/ets_pdfs/icap-etsmap-factsheet-43.pdf
#electricity_price = 78.50

In [57]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [58]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [59]:
#tmp2

In [60]:
#tmp2.sort_values(by="free_co2s", ascending=False)

In [61]:
profit = tmp2[["plantid", "plantname", "revenue", "profit"]]
profit["revenue"] = profit["revenue"].apply(lambda x: x / 10**6)

In [62]:
profit.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
16,BYS00048,Irsching 5 DT,359.523220,255.939887
24,NW100-0167182,SWD KWF GTKW,245.622271,163.397271
23,NI10257673950,Emsland B DT,282.762309,153.963495
47,SN70015796,Boxberg Block N,1069.532421,146.720561
40,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,137.017067,105.483734
29,NW300-0370387,DT Niehl 2 RheinEnergie,194.223969,100.448969
30,NW300-0877384,Weisweiler F,752.205333,94.452751
33,NW300-9046030,Knapsack I - Dampfturbine - DT 10,124.180906,89.622573
32,NW300-9002708,Dormagen DT,131.031108,66.681108
15,BYS00044,SWM HKW Sued GuD1 GT2,99.008555,63.533555
37,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,84.142254,62.050587
5,BE172654,HKW Mitte Dampfturbine,115.848185,57.188060
6,BE172656,GuD Marzahn Dampfturbine,85.909965,33.859932
49,ST100125,Schkopau A,300.692454,23.621089
7,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,61.105379,14.450528
25,NW100-0229264,HKW III Block A,32.694750,14.178083
41,NW900-9141660,Trianel Kohlekraftwerk Lünen,249.226927,13.755405
48,SN80011277,Kraftwerk Lippendorf Block S,532.706238,10.513174
46,SL0105352-G,Dampfturbinenanlage DT3,12.306129,2.864462
4,BE169709,HKW Klingenberg Dampfturbine 1,30.705767,-1.208671
10,BWpf-450-2142201-00000000,Kraftwerk Walheim Block 2,3.107986,-9.296715
28,NW300-0326774,Niederaußem G,926.281167,-10.963629
44,SL0101000-G,Gasmotor 1 Mod.,1.556536,-12.933911
31,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-19.750769
20,NI01010098080,KWM Block 3,41.142516,-22.417857
13,BYS00009,Kraftwerk Zolling,102.711849,-24.628450
8,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,16.265449,-32.914253
17,BYS00114,Gasturbinenanlage 12,11.510145,-45.048189
9,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,48.785854,-49.342532
22,NI06060316030,GKH 1,81.696539,-59.475551
45,SL0101003-G,Weiher 3,10.840551,-60.843255
43,SL0100999-G,Bexbach,21.550094,-61.330876
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,605.522644,-66.108418
38,NW900-0205103,Bergkamen A,20.829323,-67.838971
26,NW100-0248923,Neurath F,1092.999930,-69.631543
3,BE166928,HKW Reuter West Dampfturbine D,95.048222,-70.618165
39,NW900-0327252,GuD Herne,11.097568,-72.661611
18,HE30001045,Staudinger 4,21.407240,-84.746268
36,NW700-0105516,Heyden 4,17.759709,-97.066112
27,NW100-0365906,Walsum 10,36.945773,-98.556219
19,MV30000226,Kraftwerk Rostock Block A,71.659282,-117.093432
21,NI01241117210,DT30 GuD Süd Wolfsburg,35.524314,-121.345761
14,BYS00041,SWM HKW Nord 2 T20,64.316332,-127.267001
11,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,194.910993,-154.725947
35,NW500-0915123,Datteln 4,161.544215,-161.705441
0,BB23020490,1MKA,108.660223,-185.629995
34,NW500-0342658,Scholven 1 DT,26.530522,-189.122819
1,BB45025564,Kraftwerk Jänschwalde Block A,800.545529,-195.667687
12,BWpf-450-2948214-00000000,GKM Block 6,172.163429,-198.386905
42,RP5000671,GuD Mitte DT10,157.685550,-301.197784

In [61]:
profit_combined = pd.concat([profit, profit2])

NameError: name 'profit2' is not defined

In [77]:
profit_final = profit_combined.drop_duplicates(subset="plantid", keep="first").sort_values('profit')

NameError: name 'profit_combined' is not defined

In [63]:
profit.to_csv("profit.csv", index=False)

In [189]:
pd.concat([profit2, profit, profit]).drop_duplicates(keep=False)

          plantid                     plantname     revenue      profit
9        BYS00044         SWM HKW Sued GuD1 GT2   89.847656   52.437656
18  NW900-9141660  Trianel Kohlekraftwerk Lünen  290.568831   44.375619
21     SN80011277  Kraftwerk Lippendorf Block S  845.592635  286.401855

In [193]:
#profit_final.reset_index()

In [196]:
pd.concat([profit, profit2, profit2]).drop_duplicates(keep=False).sort_values('profit', ascending=False)

,plantid,plantname,revenue,profit
27,NW100-0248923,Neurath F,1581.931513,336.890044
24,NI10257673950,Emsland B DT,431.481929,295.721155
2,BB45025611,Kraftwerk Schwarze Pumpe Block A,877.033454,157.876547
30,NW300-0370387,DT Niehl 2 RheinEnergie,216.506863,117.616863
31,NW300-0877384,Weisweiler F,786.064712,81.693246
41,NW900-9140178,Trianel Gaskraftwerk Hamm Block 10,107.310336,74.057003
6,BE172656,GuD Marzahn Dampfturbine,120.058472,65.202539
15,BYS00044,SWM HKW Sued GuD1 GT2,88.946444,51.536444
38,NW900-0125939,Cuno Heizkraftwerk Herdecke BHKW1,69.697102,46.400435
34,NW300-9046030,Knapsack I - Dampfturbine - DT 10,69.154685,32.711351
19,HE50001960,G20,46.692828,32.386161
26,NW100-0229264,HKW III Block A,45.501172,26.009595
37,NW700-0105516,Heyden 4,140.607513,20.551693
39,NW900-0205103,Bergkamen A,107.862887,15.156963
13,BYS00009,Kraftwerk Zolling,148.134540,14.994242
21,NI01010098080,KWM Block 3,76.246352,9.790979
28,NW100-0365906,Walsum 10,150.313953,8.673461
43,SL0100999-G,Bexbach,94.716769,8.060799
46,SL0105352-G,Dampfturbinenanlage DT3,15.971755,6.015088
18,HE30001045,Staudinger 4,114.068429,3.079921
4,BE169709,HKW Klingenberg Dampfturbine 1,35.119077,1.584554
44,SL0101000-G,Gasmotor 1 Mod.,14.515700,-0.634748
45,SL0101003-G,Weiher 3,71.811503,-3.137303
40,NW900-0327252,GuD Herne,64.878627,-22.695552
17,BYS00114,Gasturbinenanlage 12,16.650636,-42.992697
22,NI01241117210,DT30 GuD Süd Wolfsburg,118.842134,-45.172941
14,BYS00041,SWM HKW Nord 2 T20,113.533971,-88.499362
35,NW500-0342658,Scholven 1 DT,118.681204,-106.696332
12,BWpf-450-2948214-00000000,GKM Block 6,247.873328,-139.366872

In [116]:
#profit2 = profit

In [119]:
profit2.sort_values("profit", ascending=False)

,plantid,plantname,revenue,profit
21,SN80011277,Kraftwerk Lippendorf Block S,845.592635,286.401855
14,NW300-0326774,Niederaußem G,1245.726455,242.056864
10,BYS00048,Irsching 5 DT,341.278167,232.044833
20,SN70015796,Boxberg Block N,1202.545192,214.323757
13,NW100-0167182,SWD KWF GTKW,266.311410,179.601410
1,BB45025564,Kraftwerk Jänschwalde Block A,1180.306888,113.483473
3,BE172654,HKW Mitte Dampfturbine,142.743825,80.999075
9,BYS00044,SWM HKW Sued GuD1 GT2,89.847656,52.437656
18,NW900-9141660,Trianel Kohlekraftwerk Lünen,290.568831,44.375619
16,NW300-9002708,Dormagen DT,102.577362,34.671523
22,ST100125,Schkopau A,330.936473,34.231357
17,NW500-0915123,Datteln 4,361.658330,23.686828
4,BWpf-450-1020129-00000000,Heizkraftwerk Heilbronn FHT 1,43.903306,-4.876545
7,BWpf-450-2142201-00000000,Kraftwerk Walheim Block 2,2.273751,-10.695950
15,NW300-0923949,Block 4 Merkenich RheinEnergie,0.000000,-21.150769
5,BWpf-450-1195689-00000000,Heizkraftwerk Stuttgart-Münster DT 12,18.250977,-33.168725
12,NI06060316030,GKH 1,114.089336,-33.512753
2,BE166928,HKW Reuter West Dampfturbine D,126.922714,-46.158883
6,BWpf-450-1741292-00000000,Heizkraftwerk Altbach/Deizisau HKW 1,56.354601,-46.208461
11,MV30000226,Kraftwerk Rostock Block A,135.462265,-61.858110
8,BWpf-450-2797933-00000000,Rheinhafen- Dampfkraftwerk RDK 4S DT,265.822193,-99.739748
0,BB23020490,1MKA,110.645937,-198.719281
19,RP5000671,GuD Mitte DT10,218.220516,-265.692818