In [1]:
import pandas as pd
from helpers import get_factor, get_price

In [2]:
pd.options.mode.chained_assignment = None

In [3]:
CDF = pd.read_csv("../production/CDF.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [4]:
smard = pd.read_csv("Gro_handelspreise_202301010000_202401010000_Stunde.csv", sep=";", na_values="-", decimal=",", thousands=".")
smardlog = smard[["Datum von", "Deutschland/Luxemburg [€/MWh] Originalauflösungen"]]
smardlog.rename(columns={"Datum von": "timestamp", "Deutschland/Luxemburg [€/MWh] Originalauflösungen": "price"}, inplace=True)
smardlog["timestamp"] = pd.to_datetime(smardlog["timestamp"], format="mixed")

In [5]:
co2s = pd.read_csv("../pollution/pollutants.csv")
nat_mp = pd.read_csv("nat_mapper_2025.csv")
plantlist = pd.read_csv("../basic/plants_2.csv")
nat_mp.fillna(0, inplace=True)

In [6]:
CDF2 = CDF.loc[CDF.produced_at > "2022-12-31 23:50"].loc[CDF.produced_at < "2024-01-01 00:00"]

In [7]:
len(CDF2.groupby('produced_at').sum()) * 4

35036

In [8]:
dataset = CDF2.merge(seem, left_on="variable", right_on="sseid")

In [9]:
magic = dataset.groupby(["produced_at", "plantid"]).sum()

In [10]:
magic2 = magic[["value"]]

In [11]:
#magic2.sort_values(["produced_at", "value"])

In [12]:
production = magic2.reset_index()
production["produced_at"] = pd.to_datetime(production["produced_at"], format="mixed")

In [13]:
merged = production.merge(smardlog, left_on="produced_at", right_on="timestamp")

In [14]:
merged["revenue"] = merged["value"] * merged["price"]
tmp1 = merged[["plantid", "value", "price", "revenue"]].groupby("plantid").sum()

In [15]:
tmp1.reset_index(inplace=True)

In [16]:
revenue = tmp1[["plantid", "revenue"]]

In [17]:
tmp1

                      plantid     value      price       revenue
0            06-02-B10117A007    707521  833736.96  6.933753e+07
1                  BB23020490   1182664  833736.96  1.124468e+08
2                  BB45025564  11629654  833736.96  1.185297e+09
3                  BB45025611   8443056  833736.96  8.770335e+08
4                    BE166928   1284475  833736.96  1.283071e+08
5                    BE169709    347644  833736.96  3.511908e+07
6                    BE172654   1375621  833736.96  1.436704e+08
7                    BE172656   1135173  833736.96  1.200585e+08
8   BWpf-450-1020129-00000000    306853  833736.96  4.400377e+07
9   BWpf-450-1195689-00000000    199574  833736.96  1.950829e+07
10  BWpf-450-1741292-00000000    543854  833736.96  5.674700e+07
11  BWpf-450-2142201-00000000     13956  833736.96  2.315443e+06
12  BWpf-450-2797933-00000000   3744961  833736.96  3.920294e+08
13  BWpf-450-2948214-00000000   2328411  833736.96  2.478733e+08
14                   BYS00009   1273335  833736.96  1.481345e+08
15                   BYS00041   1145668  833736.96  1.135340e+08
16                   BYS00044    806060  833736.96  9.040717e+07
17                   BYS00048   2856627  833736.96  3.423873e+08
18                   BYS00114    167731  833736.96  1.665064e+07
19                   BYS00727     60018  833736.96  7.220972e+06
20                 HE30001045   1018041  833736.96  1.140684e+08
21                 HE50001960    357840  833736.96  4.669283e+07
22                 MV30000226   1145693  833736.96  1.359821e+08
23              NI01010098080    609549  833736.96  7.624635e+07
24              NI01241117210   1191734  833736.96  1.188421e+08
25              NI06060316030   1136996  833736.96  1.160479e+08
26              NI10257673950   3820312  833736.96  4.314819e+08
27              NW100-0167182   2392763  833736.96  2.671955e+08
28              NW100-0229264    395406  833736.96  4.550117e+07
29              NW100-0248923  15022470  833736.96  1.581932e+09
30              NW100-0365906   1229773  833736.96  1.503140e+08
31              NW300-0326774  11726108  833736.96  1.249043e+09
32              NW300-0370387   1999677  833736.96  2.165069e+08
33              NW300-0877384   7312424  833736.96  7.860647e+08
34              NW300-0923949         0  833736.96  0.000000e+00
35              NW300-9002708    907665  833736.96  1.031325e+08
36              NW300-9046030    587200  833736.96  6.915468e+07
37              NW500-0342658   1198168  833736.96  1.186812e+08
38              NW500-0915123   3406589  833736.96  3.625774e+08
39              NW700-0105516   1116943  833736.96  1.406075e+08
40              NW900-0125939    565667  833736.96  6.969710e+07
41              NW900-0205103    834744  833736.96  1.078629e+08
42              NW900-0327252    584248  833736.96  6.487863e+07
43              NW900-0865327     10623  833736.96  1.625273e+06
44              NW900-9140178    918998  833736.96  1.073103e+08
45              NW900-9141660   2585237  833736.96  2.912289e+08
46                   SD661-06     18948  833736.96  2.738489e+06
47                   SD661-18    270939  833736.96  2.671743e+07
48                   SD666-16   2831770  833736.96  2.920567e+08
49                   SD666-17   2103067  833736.96  2.017425e+08
50                   SD666-18   1778014  833736.96  1.867304e+08
51                SL0100999-G    833290  833736.96  9.471677e+07
52                SL0101000-G    111729  833736.96  1.451570e+07
53                SL0101003-G    634532  833736.96  7.181150e+07
54                SL0105352-G    141928  833736.96  1.597176e+07
55                 SN70015796  11845026  833736.96  1.206200e+09
56                 SN80011277   7736932  833736.96  8.473972e+08
57                   ST100125   3064360  833736.96  3.326643e+08

In [18]:
#dataset.sort_values(["plantid", "produced_at"])

In [19]:
plantlist2 = plantlist[["plantid", "energysource"]]
plantlist3 = plantlist2.merge(nat_mp, on="plantid")

In [20]:
tmp0 = pd.merge(revenue, plantlist3, on="plantid")
tmp0["factor"] = tmp0["energysource"].apply(get_factor)
tmp0["fuel_price"] = tmp0["energysource"].apply(get_price)

In [21]:
#prod2 = prod.loc[prod.year == 2023].loc[prod.yearpower > 1000000]
co2s2 = co2s.loc[co2s.year == 2023].loc[co2s.pollutant == "CO2"]

In [22]:
co2s2.drop_duplicates(subset=["year", "plantid", "pollutant"], inplace=True)

In [23]:
co2s2

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
52,2023,BB16018798,CO2,Air,2.850000e+08,9,Mio. t,0.285,CO2 [Mio. t]
84,2023,BB23020389,CO2,Air,4.340000e+08,9,Mio. t,0.434,CO2 [Mio. t]
163,2023,BB23020490,CO2,Air,3.015000e+09,9,Mio. t,3.015,CO2 [Mio. t]
369,2023,BB23022811,CO2,Air,1.500000e+08,9,Mio. t,0.150,CO2 [Mio. t]
411,2023,BB45025564,CO2,Air,1.413400e+10,9,Mio. t,14.134,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
15336,2023,ST18046,CO2,Air,2.210000e+08,9,Mio. t,0.221,CO2 [Mio. t]
15459,2023,TH30013152,CO2,Air,2.620000e+08,9,Mio. t,0.262,CO2 [Mio. t]
15490,2023,TH62013494,CO2,Air,1.290000e+08,9,Mio. t,0.129,CO2 [Mio. t]
15566,2023,TH72012874,CO2,Air,1.770000e+08,9,Mio. t,0.177,CO2 [Mio. t]
15599,2023,TH86012942,CO2,Air,1.110000e+08,9,Mio. t,0.111,CO2 [Mio. t]

In [24]:
co2s3 = co2s2[["plantid", "amount_2"]]

In [25]:
tmp1 = pd.merge(tmp0, co2s3, on="plantid")

In [26]:
tmp2 = pd.merge(tmp1, production, on="plantid")

In [27]:
tmp2 = tmp1

In [28]:
coal_cost_per_t = 103.5 or 120
co2_cost = 70
#electricity_price = 78.50

In [29]:
tmp2["co2_cost"] = (tmp2["amount_2"] * 10**6 - tmp2["free_co2s"]) * co2_cost / 10**6
tmp2["coal_cost"] = (tmp2["amount_2"] * 10**6 * 1/tmp2["factor"] * tmp2["fuel_price"]) / 10**6

In [30]:
tmp2["profit"] = (tmp2["revenue"] / 10**6) - (tmp2["co2_cost"] + tmp2["coal_cost"])

In [31]:
profit = tmp2[["plantid", "revenue", "profit"]]
profit["revenue"] = profit["revenue"].apply(lambda x: x / 10**6)

In [32]:
profit.to_csv("profit.csv", index=False)

In [33]:
profit.sort_values("profit")

                      plantid      revenue      profit
0                  BB23020490   112.446805 -196.918413
12  BWpf-450-2948214-00000000   247.873328 -139.366872
35              NW500-0342658   118.681204 -106.696332
14                   BYS00041   113.533971  -88.499362
20                 MV30000226   135.982097  -61.338277
9   BWpf-450-1741292-00000000    56.747003  -45.816059
22              NI01241117210   118.842134  -45.172941
3                    BE166928   128.307113  -44.774484
17                   BYS00114    16.650636  -42.992697
8   BWpf-450-1195689-00000000    19.508291  -31.911410
23              NI06060316030   116.047917  -31.554172
40              NW900-0327252    64.878627  -22.695552
32              NW300-0923949     0.000000  -21.150769
10  BWpf-450-2142201-00000000     2.315443  -10.654259
7   BWpf-450-1020129-00000000    44.003772   -4.776078
45                SL0101003-G    71.811503   -3.137303
44                SL0101000-G    14.515700   -0.634748
4                    BE169709    35.119077    1.584554
18                 HE30001045   114.068429    3.079921
46                SL0105352-G    15.971755    6.015088
43                SL0100999-G    94.716769    8.060799
28              NW100-0365906   150.313953    8.673461
21              NI01010098080    76.246352    9.790979
13                   BYS00009   148.134540   14.994242
39              NW900-0205103   107.862887   15.156963
37              NW700-0105516   140.607513   20.551693
36              NW500-0915123   362.577369   24.605868
26              NW100-0229264    45.501172   26.009595
11  BWpf-450-2797933-00000000   392.029446   26.467506
19                 HE50001960    46.692828   32.386161
34              NW300-9046030    69.154685   32.711351
33              NW300-9002708   103.132538   35.226699
49                   ST100125   332.664312   35.959196
42              NW900-9141660   291.228889   45.035676
38              NW900-0125939    69.697102   46.400435
15                   BYS00044    90.407175   52.997175
6                    BE172656   120.058472   65.202539
41              NW900-9140178   107.310336   74.057003
31              NW300-0877384   786.064712   81.693246
5                    BE172654   143.670421   81.925671
30              NW300-0370387   216.506863  117.616863
1                  BB45025564  1185.297396  118.473981
2                  BB45025611   877.033454  157.876547
25              NW100-0167182   267.195517  180.485517
47                 SN70015796  1206.200412  217.978978
16                   BYS00048   342.387341  233.154007
29              NW300-0326774  1249.043238  245.373646
48                 SN80011277   847.397189  288.206410
24              NI10257673950   431.481929  295.721155
27              NW100-0248923  1581.931513  336.890044