In [1]:
import pandas as pd
import numpy as np
import re
import json

In [13]:
NEW_COL_DICT = {
    'Berichtsjahr': int,
    'InspireID_Betrieb': str,
    'PRTR_Kennnummer': str,
 'Bundesland': str,
 'Name_Betrieb': str,
 'Adresse_PLZ': str,
 'Adresse_Ort': str,
 'Adresse_Str': str,
 'Adresse_Str_Nr': str,
 'Koordinaten': str,
 'Flusseinzugsgebiet': str,
 'Status_Betrieb': str,
 'Anmerkungen_des_Betreibers': str,
 'Kompartiment': str,
 'E_PRTR_Hauptaktivitaet': str,
 'Taetigkeit': str,
 'Branche': str,
 'Stoffgruppe': str,
 'Schadstoff': str,
 'Schadstoffmenge_(kg/Jahr)': float,
 'versehentliche_Freisetzung_(kg/Jahr)': float,
 'Bestimmungsmethode': str,
 'Bestimmungsverfahren': str,
 'Bemerkungen_Bestimmungsverfahren': str,
 'Geheimhaltungsgrund_Name_Betrieb': str,
 'Geheimhaltungsgrund_Adresse': str,
 'Geheimhaltungsgrund_Schadstoff': str,
 'Geheimhaltungsgrund_Betriebsdaten': str,
 'NACE_Code': str,
 'NACE_Wirtschaftszweig': str,
 'Anzahl_Anlagen': str,
 'Muttergesellschaft': str,
 'Geheimhaltungsgrund_Muttergesellschaft': str}

In [14]:
new = pd.read_excel("../data/E-PRTR_Deutschland_Freisetzung_2007-2023_2025-03-19.xlsx", dtype=NEW_COL_DICT, na_values="-")

In [15]:
new2 = new.copy()
new2["InspireID_Betrieb"] = new2["InspireID_Betrieb"].apply(lambda x: str(x))
def match_inspire(name):
    if re.match(r"DE.EEA\/[0-9]+\.FACILITY", name):
        return "DE.EEA" + re.search("[0-9]+", name)[0]
        #None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bb.inspire.pf.eureg\/[0-9]+", name):
        return "BB" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.sh\/[0-9]+", name):
        return "SH" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bw.lubw.inspire.pf\/[A-Za-z]*-[0-9]+", name):
        return "BW" + re.search("[A-Za-z]*([0-9]*-)*[0-9]+$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.by.inspire.pf.ied\/S[0-9]+", name):
        return "BY" + re.search("S[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de\.hb\/[0-9]+", name):
        return "HB" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hb\/de.hb.pf.bube-eureg.([0-9]*\-*\/*)*[0-9]*", name):
        return "HB" + re.search("([0-9]*-*/*)*[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.he.0945.de7.pf.eu_industrie\/[0-9]*", name):
        return "HE" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hh\/pf.bube-eureg_\/[0-9]+", name):
        return "HH" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.mv.land.inspire.pf.bube\/[0-9]+", name):
        return "MV" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.ni.mu\/[0-9]+", name):
        return "NI" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.nw.inspire.pf.bube-eureg/arb-([0-9]*-)[0-9]+", name):
        return "NW" + re.search("([0-9]*-)[0-9]+$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.rp.inspire.pf.bube-eureg\/[0-9]+", name):
        return "RP" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sl.inspire.pf\/[0-9]+-G", name):
        return "SL" + re.search("[0-9]*-G$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sn.sax4inspire.pf\/[0-9]+", name):
        return "SN" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.st.lau.pf.anlagen-ied-euregistry\/[0-9]+", name):
        return "ST" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.th/([a-z]*[0-9]*-*)*([a-z]*[0-9]*)/[0-9]+", name):
        return "TH" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https://registry.gdi-de.org/id/de.be.pf.lisa\/[0-9]+", name):
        return "BE" + re.search("[0-9]*$", name)[0]
        # return "MLT" + re.search("[0-9]+", name)[0]
        #return None
    else:
        return name

new2["InspireID_Betrieb"] = new2["InspireID_Betrieb"].apply(match_inspire)

In [16]:
new["InspireID_Betrieb"] = new["InspireID_Betrieb"].apply(lambda x: str(x))

In [17]:
bpm = pd.read_csv("../basic/plant_sse_mapper2.csv")
bpm['PRTR_Kennnummer'] = bpm['PRTR_Kennnummer'].apply(lambda x: str(x).replace('/', '_'))
#bpm.drop_duplicates(["PRTR_Kennnummer"], inplace=True)

In [18]:
raw_toadd = new.loc[new.InspireID_Betrieb == "nan"].loc[new.Branche == "Energiesektor"].drop_duplicates(subset="PRTR_Kennnummer")

In [19]:
toadd = raw_toadd[["InspireID_Betrieb", "PRTR_Kennnummer"]].replace("nan", np.nan)

/tmp/ipykernel_1997163/3086296939.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  toadd = raw_toadd[["InspireID_Betrieb", "PRTR_Kennnummer"]].replace("nan", np.nan)

In [20]:
toadd["InspireID_Betrieb"] = toadd["PRTR_Kennnummer"]

In [21]:
mapper = new.loc[new.InspireID_Betrieb != "nan"]

In [22]:
mapper2a = mapper.drop_duplicates(subset="PRTR_Kennnummer", keep="first")

In [23]:
mapper2 = pd.concat([mapper2a, toadd])

In [24]:
mapper3 = mapper2[["InspireID_Betrieb", "PRTR_Kennnummer"]]
mapper3["InspireID_Betrieb"] = mapper3["InspireID_Betrieb"].apply(lambda x: str(x))
mapper3["InspireID_Betrieb"] = mapper3["InspireID_Betrieb"].apply(lambda x: str(match_inspire(x)))

/tmp/ipykernel_1997163/2815922723.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapper3["InspireID_Betrieb"] = mapper3["InspireID_Betrieb"].apply(lambda x: str(x))
/tmp/ipykernel_1997163/2815922723.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapper3["InspireID_Betrieb"] = mapper3["InspireID_Betrieb"].apply(lambda x: str(match_inspire(x)))

In [25]:
mapper4 = mapper3.merge(bpm, on="PRTR_Kennnummer").sort_values("InspireID_Betrieb")

In [26]:
mapper4.to_csv("../basic/inspire_prtr_mapper.csv", index=False)

In [27]:
new2["InspireID_Betrieb"] = new2["InspireID_Betrieb"].apply(match_inspire)

In [28]:
new2.groupby("InspireID_Betrieb").count()

,Berichtsjahr,PRTR_Kennnummer,Bundesland,Name_Betrieb,Adresse_PLZ,Adresse_Ort,Adresse_Str,Adresse_Str_Nr,Koordinaten,Flusseinzugsgebiet,...,Bemerkungen_Bestimmungsverfahren,Geheimhaltungsgrund_Name_Betrieb,Geheimhaltungsgrund_Adresse,Geheimhaltungsgrund_Schadstoff,Geheimhaltungsgrund_Betriebsdaten,NACE_Code,NACE_Wirtschaftszweig,Anzahl_Anlagen,Muttergesellschaft,Geheimhaltungsgrund_Muttergesellschaft
InspireID_Betrieb,,,,,,,,,,,,,,,,,,,,,
BB1291029107,4,3,4,4,4,4,4,4,4,4,...,3,0,0,0,0,4,4,4,4,0
BB1291045754,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,1,1,1,0
BB16009777,4,4,4,4,4,4,4,4,4,4,...,0,0,0,0,0,4,4,0,2,0
BB16010336,17,16,17,17,17,17,17,17,17,17,...,5,0,0,0,0,17,17,6,17,0
BB16011024,4,4,4,4,4,4,4,0,4,4,...,0,0,0,0,0,4,4,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TH92012861,16,15,16,16,16,16,16,16,16,16,...,5,0,0,0,0,16,11,6,14,0
TH92012906,8,8,8,8,8,8,8,8,8,8,...,0,0,0,0,0,8,8,0,6,0
TH92013060,16,15,16,16,16,16,16,16,16,16,...,5,0,0,0,0,16,16,6,15,0
TH92013062,13,12,13,13,13,13,13,7,13,13,...,4,0,0,0,0,13,13,5,12,0
nan,616,616,616,616,614,614,613,556,616,616,...,0,2,0,0,0,616,616,0,445,0

In [29]:
match_inspire("DE.EEA/105825.FACILITY")

'DE.EEA105825'

In [30]:
new3 = new2.loc[new2.InspireID_Betrieb == "nan"].loc[new2.Branche == "Energiesektor"]

In [31]:
new3.groupby("PRTR_Kennnummer").count()

,Berichtsjahr,InspireID_Betrieb,Bundesland,Name_Betrieb,Adresse_PLZ,Adresse_Ort,Adresse_Str,Adresse_Str_Nr,Koordinaten,Flusseinzugsgebiet,...,Bemerkungen_Bestimmungsverfahren,Geheimhaltungsgrund_Name_Betrieb,Geheimhaltungsgrund_Adresse,Geheimhaltungsgrund_Schadstoff,Geheimhaltungsgrund_Betriebsdaten,NACE_Code,NACE_Wirtschaftszweig,Anzahl_Anlagen,Muttergesellschaft,Geheimhaltungsgrund_Muttergesellschaft
PRTR_Kennnummer,,,,,,,,,,,,,,,,,,,,,
03-06-06063822850,12,12,12,12,12,12,12,12,12,12,...,0,0,0,0,0,12,12,0,12,0
06-02-B10117A007,7,7,7,7,7,7,7,7,7,7,...,0,0,0,0,0,7,7,0,0,0
06-05-100-0030723,29,29,29,29,29,29,29,29,29,29,...,0,0,0,0,0,29,29,0,25,0
06-05-100-0431554,72,72,72,72,72,72,72,72,72,72,...,0,0,0,0,0,72,72,0,48,0
06-05-100-0853075,52,52,52,52,52,52,52,52,52,52,...,0,0,0,0,0,52,52,0,29,0
06-05-100-0988652,30,30,30,30,30,30,30,30,30,30,...,0,0,0,0,0,30,30,0,30,0
06-08-4163702,2,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,2,2,0,0,0
06-08-9611355,4,4,4,4,4,4,4,4,4,4,...,0,0,0,0,0,4,4,0,0,0
16-30-31400103005,9,9,9,9,9,9,9,9,9,9,...,0,0,0,0,0,9,9,0,8,0
16-30-42400000054,2,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,2,2,0,0,0

In [32]:
new4 = new2.sort_values("InspireID_Betrieb").sort_values("Berichtsjahr")

In [33]:
new4.to_csv("newplants.csv", index=False)