In [1]:
import pandas as pd
import numpy as np
import re
import json

In [2]:
NEW_COL_DICT = {
    'Berichtsjahr': int,
    'InspireID_Betrieb': str,
    'PRTR_Kennnummer': str,
 'Bundesland': str,
 'Name_Betrieb': str,
 'Adresse_PLZ': str,
 'Adresse_Ort': str,
 'Adresse_Str': str,
 'Adresse_Str_Nr': str,
 'Koordinaten': str,
 'Flusseinzugsgebiet': str,
 'Status_Betrieb': str,
 'Anmerkungen_des_Betreibers': str,
 'Kompartiment': str,
 'E_PRTR_Hauptaktivitaet': str,
 'Taetigkeit': str,
 'Branche': str,
 'Stoffgruppe': str,
 'Schadstoff': str,
 'Schadstoffmenge_(kg/Jahr)': float,
 'versehentliche_Freisetzung_(kg/Jahr)': float,
 'Bestimmungsmethode': str,
 'Bestimmungsverfahren': str,
 'Bemerkungen_Bestimmungsverfahren': str,
 'Geheimhaltungsgrund_Name_Betrieb': str,
 'Geheimhaltungsgrund_Adresse': str,
 'Geheimhaltungsgrund_Schadstoff': str,
 'Geheimhaltungsgrund_Betriebsdaten': str,
 'NACE_Code': str,
 'NACE_Wirtschaftszweig': str,
 'Anzahl_Anlagen': str,
 'Muttergesellschaft': str,
 'Geheimhaltungsgrund_Muttergesellschaft': str}

In [3]:
new = pd.read_excel("../data/E-PRTR_Deutschland_Freisetzung_2007-2023_2025-03-19.xlsx", dtype=NEW_COL_DICT)

In [4]:
DROP_LIST_NEW = ['Geheimhaltungsgrund_Muttergesellschaft', 'Anzahl_Anlagen', 'NACE_Wirtschaftszweig','NACE_Code','Geheimhaltungsgrund_Name_Betrieb', 'Geheimhaltungsgrund_Adresse', 'Geheimhaltungsgrund_Schadstoff',
 'Geheimhaltungsgrund_Betriebsdaten', 'Bestimmungsmethode', 'Bestimmungsverfahren', 'Bemerkungen_Bestimmungsverfahren','versehentliche_Freisetzung_(kg/Jahr)','Anmerkungen_des_Betreibers',
 'E_PRTR_Hauptaktivitaet', 'Taetigkeit', 'Branche', 'Adresse_PLZ','Adresse_Ort','Stoffgruppe',
 'Adresse_Str', 'Adresse_Str_Nr', 'Koordinaten','Bundesland', 'Flusseinzugsgebiet', 'Status_Betrieb',]

In [5]:
new2 = new.drop(DROP_LIST_NEW, axis=1)

In [6]:
new3 = new2.rename(columns={"Berichtsjahr": "year", "PRTR_Kennnummer": "plantid", "Name_Betrieb": "company", "Muttergesellschaft": "eigentuemer", "Schadstoffmenge_(kg/Jahr)": "amount",
                           "Schadstoff": 'pollutant','Kompartiment': 'releases_to'})

In [7]:
#list(raw3)

In [8]:
list(new3)

['year',
 'InspireID_Betrieb',
 'plantid',
 'company',
 'releases_to',
 'pollutant',
 'amount',
 'eigentuemer']

In [9]:
#list(raw0)

In [10]:
DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [11]:
#list(new)

In [12]:
COL_DICT = {'jahr': int,
 'kennnummer': str,
 'betriebsname': str,
 'betriebsname_2': str,
 'plz': str,
 'ort': str,
 'strasse': str,
 'hausnr': str,
 'bundesland': str,
 'flusseinzugsgebiet': str,
 'geo_lat_wgs84': np.float64,
 'geo_long_wgs84': np.float64,
 'taet_nr': str,
 'taetigkeit': str,
 'activity': str,
 'haupttaetigkeit': str,
 'branche': str,
 'sector': str,
 'nace_id': int,
 'nace_wirtschaftszweig': str,
 'nace_sector': str,
 'stoffgruppe': str,
 'substances_group': str,
 'schadstoff': str,
 'pollutant': str,
 'umweltkompartiment': str,
 'releases_to': str,
 'jahresfracht_freisetzung': float,
 'versehentliche_freisetzung': float,
 'schadstoff_schwellenwert': float,
 'einheit': str,
 'unit': str,
 'bestimmungsmethode': str,
 'determination_method': str,
 'schutzgrund_fracht': str,
 'confidential_reason_release': str,
 'schutzgrund_betrieb': str,
 'confidential_reason_facility': str}

DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [13]:
#raw0 = pd.read_csv("../data/2020-05-19_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", sep=";", dtype=COL_DICT)

In [14]:
raw0 = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx", dtype=COL_DICT)

In [15]:
raw0

,jahr,kennnummer,betriebsname,betriebsname_2,betreiber,eigentuemer,plz,ort,strasse,hausnr,...,versehentliche_freisetzung,schadstoff_schwellenwert,einheit,unit,bestimmungsmethode,determination_method,schutzgrund_fracht,confidential_reason_release,schutzgrund_betrieb,confidential_reason_facility
0,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
1,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
2,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,150000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
3,2007,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,NaN,-,-,25541,Brunsbüttel,Melamidstr.,-,...,0.0,150000.0,kg/Jahr,kg/year,Schätzung,Estimation,NaN,NaN,NaN,NaN
4,2007,01-10-51048040567,Shell Deutschland Oil GmbH,Raffinerie Heide,-,-,25734,Hemmingstedt,Postfach,14 40,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71703,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,100.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71704,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,1000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71705,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,50000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71706,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71707,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN

In [16]:
raw1 = raw0.rename(columns={"jahr": "year", "betriebsname_2": "plantname", "betriebsname": "company", "kennnummer": "plantid", "ort": "place", "strasse": "street", "bundesland": "federalstate", "jahresfracht_freisetzung": "amount"})

In [17]:
raw1['plantid'] = raw1['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [18]:
#raw0 = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", error_bad_lines=False, engine="c", sep=";", low_memory=False)

In [19]:
#raw0

In [20]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
bpm.drop_duplicates(["plantid"], inplace=True)

In [103]:
insprmpr = new.copy()

In [126]:
insprmpr2 = insprmpr.copy()
insprmpr2 = insprmpr2[~insprmpr2.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
insprmpr2 = insprmpr2[insprmpr2.PRTR_Kennnummer != "-"]
insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [127]:
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("-")]
new3['InspireID_Betrieb'] = new3['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [128]:
new3

,year,InspireID_Betrieb,plantid,company,releases_to,pollutant,amount,eigentuemer
0,2007,10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Kohlendioxid (CO2),2.000000e+08,-
1,2007,10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Stickoxide (NOx/NO2),1.870000e+05,-
2,2007,10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Schwefeloxide (SOx/SO2),2.530000e+05,-
3,2007,10038068,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,Luft,Schwefeloxide (SOx/SO2),2.130000e+05,-
4,2007,10039818,01-10-51048040567,Shell Deutschland Oil GmbH,Luft,Kohlendioxid (CO2),1.140000e+09,-
...,...,...,...,...,...,...,...,...
75385,2023,92012855,-,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...,Luft,Ammoniak (NH3),1.590000e+04,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...
75386,2023,92012857,-,Viloss GmbH / Loßnitz,Luft,Ammoniak (NH3),1.240000e+04,Viloss GmbH
75387,2023,92012861,-,Agrarunternehmen Barnstädt e. G.,Luft,Ammoniak (NH3),2.730000e+04,Agrarunternehmen Barnstädt
75388,2023,92013060,-,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.,Luft,Ammoniak (NH3),4.340000e+04,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.
75389,2023,92013062,-,Agrarunternehmen Barnstädt,Luft,Ammoniak (NH3),1.350000e+04,Agrarunternehmen Barnstedt

In [129]:

#insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).replace("https://registry.gdi-de.org/id/de.ni.mu/", ""))

In [130]:
insprmpr2 = insprmpr2[["InspireID_Betrieb", "PRTR_Kennnummer"]]

In [131]:
insprmpr3 = insprmpr2.drop_duplicates(subset='InspireID_Betrieb', keep="first")

In [132]:
insprmpr3

      InspireID_Betrieb      PRTR_Kennnummer
0              10000140    01-10-51011005501
3              10038068    01-10-51011008130
4              10039818    01-10-51048040567
12             10007530    01-10-56027123428
26       43117.FACILITY    01-10-56050192711
...                 ...                  ...
72280            S00421  06-09-277-0077-0001
72649            S12167  06-09-661-9003-0001
72881         680029800       06-00002670433
73176       07239453340    03-07-07239453340
73229       09262668700    03-09-09262668700

[2829 rows x 2 columns]

In [133]:
#raw1.loc[raw1.plantid == "03-01-01012110180"]

In [134]:
raw2 = pd.merge(raw1, bpm, how="inner", on="plantid")
new4 = pd.merge(new3, bpm, how="inner", on="plantid")

In [31]:
raw2.year = raw2.year.astype(int)

In [32]:
DROP_LIST

['flusseinzugsgebiet',
 'schutzgrund_fracht',
 'confidential_reason_release',
 'schutzgrund_betrieb',
 'confidential_reason_facility',
 'versehentliche_freisetzung',
 'bestimmungsmethode',
 'determination_method',
 'einheit',
 'umweltkompartiment',
 'haupttaetigkeit',
 'taetigkeit',
 'nace_wirtschaftszweig',
 'schadstoff',
 'stoffgruppe',
 'branche',
 'schadstoff_schwellenwert',
 'sseid',
 'geo_lat_wgs84',
 'geo_long_wgs84']

In [33]:
raw3 = raw2.drop(DROP_LIST, axis=1)

In [34]:
#raw3.loc[raw3.plantid == "03-01-01012110180"]

In [35]:
p = "PCDD + PCDF (dioxins + furans) (as Teq)"
q = "Trichlorobenzenes (TCBs) (all isomers)"
z = "Total organic carbon (TOC) (as total C or COD/3)"

In [36]:
re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

<>:1: SyntaxWarning: invalid escape sequence '\)'
<>:1: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_314341/3641376740.py:1: SyntaxWarning: invalid escape sequence '\)'
  re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

'TCBs'

In [37]:
t = "Kraftwerk Voerde OHG der STEAG GmbH und RWE"

In [38]:
match_list = ["Vattenfall", "RWE", "Uniper", "LEAG", "EnBW", "Steag"]

In [39]:
raw4 = raw3.sort_values(by="amount", ascending=False)
new5 = new4.sort_values(by="amount", ascending=False)

In [40]:
def fix_company(company):
    for name in match_list:
        if name in company:
            return name
        else:
            return company

In [41]:
def fix_pollutant(pol):
    match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)
    if match:
        return match[-1]
    else:
        return pol

<>:2: SyntaxWarning: invalid escape sequence '\)'
<>:2: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_314341/3548206704.py:2: SyntaxWarning: invalid escape sequence '\)'
  match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)

In [42]:
fix_pollutant(q)

'TCBs'

In [43]:
unit_2_dict = {9: "Mio. t", 6: "Tsd. t", 3: "t", 1: "kg", -3: "g", -6: "mg"}
amount_dict = {"CO2": 9, "CO": 6, "NO2": 6, "Cl": 6, "SO2": 6, "Total nitrogen": 6, "PM10": 6, "HCl": 3, "HF": 3, "N2O": 6, "Benzene": 3, "Pb": 3, "Zn": 3, "Benzene": 3, "Fluorides (as total F)": 3, "NMVOC": 3, "NH3": 3, "TOC": 3, "CH4": 3, "AOX": 3, "Total phosphorus": 3, "HCFCs": 3, "HFCs": 3, "DCE": 3, "Phenols (as total C)": 3, "Cu": 3, "PER": 3, "Cr": 3, "Trichloroethylene": 3, "Trichloromethane": 3, "TCM": 3, "CN": 3, "Ni": 3, "DCM": 3, "HCN": 3, "As": 3, "Hg": 3}
neg_dict = {"Teq": 6}

In [44]:
raw5 = raw4.copy()

In [45]:
raw4['group'] = raw4['company'].apply(lambda x: fix_company(x))
raw4['pollutant'] = raw4['pollutant'].apply(lambda x: fix_pollutant(x))
new5['group'] = new5['company'].apply(lambda x: fix_company(x))
new5['pollutant'] = new5['pollutant'].apply(lambda x: fix_pollutant(x))

In [46]:
new5['potency'] = new5['pollutant'].apply(lambda x: amount_dict.get(x, 1))
new5['neg_potency'] = new5['pollutant'].apply(lambda x: neg_dict.get(x, 0))
new5['unit_2'] = new5['potency'].apply(lambda x: unit_2_dict[x])
new5['amount_2'] = new5['amount'] / 10**(new5['potency'])
new5['amount_2'] = new5['amount_2'] * 10**(new5['neg_potency'])
new5.loc[new5['pollutant'] == "Teq"] = new5.loc[new5['pollutant'] == "Teq"].replace("kg", "mg")

In [47]:
#raw4

In [48]:
raw5['potency'] = raw5['pollutant'].apply(lambda x: amount_dict.get(x, 1))

In [49]:
raw5['neg_potency'] = raw5['pollutant'].apply(lambda x: neg_dict.get(x, 0))

In [50]:
raw5['unit_2'] = raw5['potency'].apply(lambda x: unit_2_dict[x])

In [51]:
raw5['amount_2'] = raw5['amount'] / 10**(raw5['potency'])
raw5['amount_2'] = raw5['amount_2'] * 10**(raw5['neg_potency'])

In [52]:
raw5.loc[raw5['pollutant'] == "Teq"] = raw5.loc[raw5['pollutant'] == "Teq"].replace("kg", "mg")

In [53]:
#raw5

In [54]:
DROP_LIST = ['plz', 'company','plantname', 'group', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']
DROP_LIST = ['plz', 'company','plantname', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']

In [55]:
NEW_DROP_LIST_2 = ['group', 'sseid']

In [56]:
raw6 = raw5.drop(DROP_LIST, axis=1)
new6 = new5.drop(NEW_DROP_LIST_2, axis=1)

In [135]:
raw6['pollutant2'] = raw6['pollutant'] + ' [' + raw6['unit_2'] + ']'
new6['pollutant2'] = new6['pollutant'] + ' [' + new6['unit_2'] + ']'

In [136]:
new65 = new6.drop("plantid", axis=1)

In [137]:
new70 = pd.merge(new65, insprmpr3, how="inner", on="InspireID_Betrieb")

In [138]:
new70

,year,InspireID_Betrieb,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2,PRTR_Kennnummer
0,2013,arb-2017-162008-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t],06-05-100-0248923
1,2014,arb-2017-162008-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.240000e+10,9,Mio. t,32.400000,CO2 [Mio. t],06-05-100-0248923
2,2018,arb-2017-162008-100-0248923,RWE Power AG - Kraftwerk Neurath,RWE Power AG,CO2,Luft,3.220000e+10,9,Mio. t,32.200000,CO2 [Mio. t],06-05-100-0248923
3,2015,arb-2017-162008-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.210000e+10,9,Mio. t,32.100000,CO2 [Mio. t],06-05-100-0248923
4,2016,arb-2017-162008-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.130000e+10,9,Mio. t,31.300000,CO2 [Mio. t],06-05-100-0248923
...,...,...,...,...,...,...,...,...,...,...,...,...
14726,2015,03030273580,DOW Deutschland Anlagenges. m.b.H,Dow Deutschland Anlagengesellschaft mbH,Furane,Wasser,1.310000e-04,1,kg,0.000013,Furane [kg],03-03-03030273580
14727,2012,nan,Kraftwerk Voerde OHG der STEAG GmbH und RWE Po...,STEAG GmbH,Furane,Luft,1.300000e-04,1,kg,0.000013,Furane [kg],03-01-01010784700
14728,2015,45025564,Vattenfall Europe Generation AG Kraftwerk Jäns...,Vattenfall Europe Generation AG,Furane,Luft,1.300000e-04,1,kg,0.000013,Furane [kg],12-40710010000
14729,2009,arb-2017-315000-300-0923949,HKW Merkenich,RheinEnergie AG,Furane,Luft,1.150000e-04,1,kg,0.000012,Furane [kg],06-05-300-0923949
14730,2019,45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg],12-40710010000

In [139]:
new70 = new70[['year', 'PRTR_Kennnummer', 'company', 'eigentuemer', 'pollutant', 'releases_to', 'amount', 'potency', 'unit_2', 'amount_2', 'pollutant2']]

In [145]:
new71 = new70.rename(columns={"PRTR_Kennnummer": "plantid"})

In [146]:
#new70.sort_values("year")

In [148]:
new71

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
0,2013,06-05-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
1,2014,06-05-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.240000e+10,9,Mio. t,32.400000,CO2 [Mio. t]
2,2018,06-05-100-0248923,RWE Power AG - Kraftwerk Neurath,RWE Power AG,CO2,Luft,3.220000e+10,9,Mio. t,32.200000,CO2 [Mio. t]
3,2015,06-05-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.210000e+10,9,Mio. t,32.100000,CO2 [Mio. t]
4,2016,06-05-100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.130000e+10,9,Mio. t,31.300000,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
14726,2015,03-03-03030273580,DOW Deutschland Anlagenges. m.b.H,Dow Deutschland Anlagengesellschaft mbH,Furane,Wasser,1.310000e-04,1,kg,0.000013,Furane [kg]
14727,2012,03-01-01010784700,Kraftwerk Voerde OHG der STEAG GmbH und RWE Po...,STEAG GmbH,Furane,Luft,1.300000e-04,1,kg,0.000013,Furane [kg]
14728,2015,12-40710010000,Vattenfall Europe Generation AG Kraftwerk Jäns...,Vattenfall Europe Generation AG,Furane,Luft,1.300000e-04,1,kg,0.000013,Furane [kg]
14729,2009,06-05-300-0923949,HKW Merkenich,RheinEnergie AG,Furane,Luft,1.150000e-04,1,kg,0.000012,Furane [kg]
14730,2019,12-40710010000,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]

In [61]:
m1 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])
m2 = raw6.duplicated(['year', 'pollutant', 'plantid'])
m3 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])

In [149]:
raw7 = raw6.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])
new7 = new71.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])

In [150]:
new7.loc[new7.releases_to == "Wasser"]

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
12571,2020,01-10-51048040567,Raffinerie Heide GmbH,Raffinerie Heide GmbH,Zn,Wasser,150.0,3,t,0.1500,Zn [t]
11980,2019,01-10-51048040567,Raffinerie Heide GmbH,Raffinerie Heide GmbH,Zn,Wasser,335.0,3,t,0.3350,Zn [t]
12127,2018,01-10-51048040567,Raffinerie Heide GmbH,Raffinerie Heide GmbH,Zn,Wasser,271.0,3,t,0.2710,Zn [t]
14185,2018,01-10-51048040567,Raffinerie Heide GmbH,Raffinerie Heide GmbH,Phenole (als Gesamt-C),Wasser,21.3,1,kg,2.1300,Phenole (als Gesamt-C) [kg]
12489,2017,01-10-51048040567,Raffinerie Heide GmbH,Raffinerie Heide GmbH,Zn,Wasser,164.0,3,t,0.1640,Zn [t]
...,...,...,...,...,...,...,...,...,...,...,...
2891,2009,18042,"K+S KALI GmbH, Werk Zielitz",-,Cl,Wasser,78800000.0,6,Tsd. t,78.8000,Cl [Tsd. t]
12632,2009,18042,"K+S KALI GmbH, Werk Zielitz",-,Zn,Wasser,140.0,3,t,0.1400,Zn [t]
2881,2008,18042,K + S KALI Zielitz,-,Cl,Wasser,96700000.0,6,Tsd. t,96.7000,Cl [Tsd. t]
12122,2008,18042,K + S KALI Zielitz,-,Zn,Wasser,272.0,3,t,0.2720,Zn [t]
13851,2008,18042,K + S KALI Zielitz,-,Pb,Wasser,32.5,3,t,0.0325,Pb [t]

In [151]:
#raw7.loc[raw7.plantid == "14-70-46630660001"].sort_values("potency", ascending=False)

In [152]:
#adds = pd.read_csv("additionals.csv") # manually add boxberg

In [153]:
#adds

In [154]:
raw8 = raw7.drop(['betreiber', 'eigentuemer'], axis=1)
new8 = new7.drop(['company', 'eigentuemer'], axis=1)

In [155]:
new8['releases_to'] = new8['releases_to'].replace({"Luft": "Air", "Wasser": "Water"})

In [156]:
new8

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
2201,2020,01-10-51011005501,CO2,Air,182000000.0,9,Mio. t,0.1820,CO2 [Mio. t]
7435,2020,01-10-51011005501,NO2,Air,168000.0,6,Tsd. t,0.1680,NO2 [Tsd. t]
2040,2019,01-10-51011005501,CO2,Air,207000000.0,9,Mio. t,0.2070,CO2 [Mio. t]
7455,2019,01-10-51011005501,NO2,Air,166000.0,6,Tsd. t,0.1660,NO2 [Tsd. t]
2019,2018,01-10-51011005501,CO2,Air,212000000.0,9,Mio. t,0.2120,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
2881,2008,18042,Cl,Water,96700000.0,6,Tsd. t,96.7000,Cl [Tsd. t]
6046,2008,18042,NO2,Air,328000.0,6,Tsd. t,0.3280,NO2 [Tsd. t]
9904,2008,18042,HCl,Air,17800.0,3,t,17.8000,HCl [t]
12122,2008,18042,Zn,Water,272.0,3,t,0.2720,Zn [t]
13851,2008,18042,Pb,Water,32.5,3,t,0.0325,Pb [t]

In [157]:
#raw8.sort_values("amount", ascending=False)

In [158]:
#pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006

In [159]:
new8.to_csv("pollutants_pg.csv", index=True, header=False)
new8.to_csv("pollutants.csv", index=False)
new8.to_csv("pollutants_nh.csv", index=False, header=False)

In [160]:
bpm.loc[bpm.plantid == "06-05-500-0342713"]

Empty DataFrame
Columns: [plantid, sseid]
Index: []

In [74]:
#raw5.loc[raw5["pollutant"] == "Teq"].sort_values("amount", ascending=False)

In [75]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '06-05-100-0248923'].sort_values("amount", ascending=False)

In [76]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '12-40710010000'].sort_values("amount", ascending=False) #12-40710010000 #06-05-300-0923949

In [77]:
#raw4.loc[raw4['year'] == 2009].loc[raw4['plantid'] == '06-05-100-0431554'].sort_values("amount", ascending=False)

In [78]:
#raw4.groupby("pollutant").sum()

In [79]:
#raw3.groupby("pollutant").sum()

In [80]:
#raw4

In [81]:
raw8.groupby('releases_to').min()

,year,plantid,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,
Air,2007,01-10-51011005501,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [82]:
raw7.groupby('releases_to').max()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2022,18042,swb Erzeugung GmbH & Co.KG,verschiedene Eigentümer,Zinc and compounds (as Zn),3.330000e+10,3,t,3.330000e+09,Zinc and compounds (as Zn) [kg]
Land,2022,18042,K+S Minerals and Agriculture GmbH,K+S Minerals and Agriculture GmbH,Zinc and compounds (as Zn),8.260000e+08,6,kg,8.260000e+07,Zinc and compounds (as Zn) [kg]
Water,2022,18042,swb Erzeugung GmbH & Co.KG,und Karton GmbH,Zinc and compounds (as Zn),1.910000e+09,6,t,1.910000e+08,Zinc and compounds (as Zn) [kg]

In [83]:
raw7.groupby('releases_to').min()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2007,01-10-51011005501,-,-,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,-,-,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,-,-,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [84]:
raw7

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
14740,2022,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,203000000.0,1,kg,20300000.00,Carbon dioxide (CO2) [kg]
14741,2022,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Nitrogen oxides (NOx/NO2),Air,173000.0,1,kg,17300.00,Nitrogen oxides (NOx/NO2) [kg]
13953,2021,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,214000000.0,1,kg,21400000.00,Carbon dioxide (CO2) [kg]
13954,2021,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Nitrogen oxides (NOx/NO2),Air,154000.0,1,kg,15400.00,Nitrogen oxides (NOx/NO2) [kg]
13189,2020,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,182000000.0,1,kg,18200000.00,Carbon dioxide (CO2) [kg]
...,...,...,...,...,...,...,...,...,...,...,...
2181,2008,18042,-,-,Chlorides (as total Cl),Water,96700000.0,1,kg,9670000.00,Chlorides (as total Cl) [kg]
2176,2008,18042,-,-,Nitrogen oxides (NOx/NO2),Air,328000.0,1,kg,32800.00,Nitrogen oxides (NOx/NO2) [kg]
2177,2008,18042,-,-,Chlorine and inorganic compounds (as HCl),Air,17800.0,1,kg,1780.00,Chlorine and inorganic compounds (as HCl) [kg]
2178,2008,18042,-,-,Zinc and compounds (as Zn),Water,272.0,1,kg,27.20,Zinc and compounds (as Zn) [kg]
2179,2008,18042,-,-,Lead and compounds (as Pb),Water,32.5,1,kg,3.25,Lead and compounds (as Pb) [kg]

In [85]:
'''
"text/plain": [
-       "   year            plantid pollutant releases_to       amount  potency  \\\n",
-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",
-       "\n",
-       "   unit_2  amount_2    pollutant2  \n",
-       "0  Mio. t      19.1  CO2 [Mio. t]  "
-      ]
-     },

'''

'\n"text/plain": [\n-       "   year            plantid pollutant releases_to       amount  potency  \\\n",\n-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",\n-       "\n",\n-       "   unit_2  amount_2    pollutant2  \n",\n-       "0  Mio. t      19.1  CO2 [Mio. t]  "\n-      ]\n-     },\n\n'