In [1]:
import pandas as pd
import numpy as np
import re
import json
from helper import match_inspire

In [2]:
NEW_COL_DICT = {
    'Berichtsjahr': int,
    'InspireID_Betrieb': str,
    'PRTR_Kennnummer': str,
 'Bundesland': str,
 'Name_Betrieb': str,
 'Adresse_PLZ': str,
 'Adresse_Ort': str,
 'Adresse_Str': str,
 'Adresse_Str_Nr': str,
 'Koordinaten': str,
 'Flusseinzugsgebiet': str,
 'Status_Betrieb': str,
 'Anmerkungen_des_Betreibers': str,
 'Kompartiment': str,
 'E_PRTR_Hauptaktivitaet': str,
 'Taetigkeit': str,
 'Branche': str,
 'Stoffgruppe': str,
 'Schadstoff': str,
 'Schadstoffmenge_(kg/Jahr)': float,
 'versehentliche_Freisetzung_(kg/Jahr)': float,
 'Bestimmungsmethode': str,
 'Bestimmungsverfahren': str,
 'Bemerkungen_Bestimmungsverfahren': str,
 'Geheimhaltungsgrund_Name_Betrieb': str,
 'Geheimhaltungsgrund_Adresse': str,
 'Geheimhaltungsgrund_Schadstoff': str,
 'Geheimhaltungsgrund_Betriebsdaten': str,
 'NACE_Code': str,
 'NACE_Wirtschaftszweig': str,
 'Anzahl_Anlagen': str,
 'Muttergesellschaft': str,
 'Geheimhaltungsgrund_Muttergesellschaft': str}

In [3]:
new = pd.read_excel("../data/E-PRTR_Deutschland_Freisetzung_2007-2024_2025-12-19.xlsx", dtype=NEW_COL_DICT)

In [4]:
DROP_LIST_NEW = ['Geheimhaltungsgrund_Muttergesellschaft', 'Anzahl_Anlagen', 'NACE_Wirtschaftszweig','NACE_Code','Geheimhaltungsgrund_Name_Betrieb', 'Geheimhaltungsgrund_Adresse', 'Geheimhaltungsgrund_Schadstoff','Bestimmungsmethode', 'Bestimmungsverfahren', 'Bemerkungen_Bestimmungsverfahren','versehentliche_Freisetzung_(kg/Jahr)','Anmerkungen_des_Betreibers',
 'E_PRTR_Hauptaktivitaet', 'Taetigkeit', 'Branche', 'Adresse_PLZ','Adresse_Ort','Stoffgruppe',
 'Adresse_Str', 'Adresse_Str_Nr','Bundesland', 'Flusseinzugsgebiet', 'Status_Betrieb',]

In [5]:
new2 = new.drop(DROP_LIST_NEW, axis=1)

In [6]:
new3 = new2.rename(columns={"Berichtsjahr": "year", "PRTR_Kennnummer": "plantid", "Name_Betrieb": "company", "Muttergesellschaft": "eigentuemer", "Schadstoffmenge_(kg/Jahr)": "amount",
                           "Schadstoff": 'pollutant','Kompartiment': 'releases_to'})

In [7]:
#list(raw3)

In [8]:
list(new3)

['year',
 'InspireID_Betrieb',
 'plantid',
 'company',
 'Koordinaten_geo_lat_wgs84',
 'Koordinaten_geo_long_wgs84',
 'releases_to',
 'pollutant',
 'amount',
 'eigentuemer']

In [9]:
#list(raw0)

In [10]:
DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [11]:
#list(new)

In [12]:
COL_DICT = {'jahr': int,
 'kennnummer': str,
 'betriebsname': str,
 'betriebsname_2': str,
 'plz': str,
 'ort': str,
 'strasse': str,
 'hausnr': str,
 'bundesland': str,
 'flusseinzugsgebiet': str,
 'geo_lat_wgs84': np.float64,
 'geo_long_wgs84': np.float64,
 'taet_nr': str,
 'taetigkeit': str,
 'activity': str,
 'haupttaetigkeit': str,
 'branche': str,
 'sector': str,
 'nace_id': int,
 'nace_wirtschaftszweig': str,
 'nace_sector': str,
 'stoffgruppe': str,
 'substances_group': str,
 'schadstoff': str,
 'pollutant': str,
 'umweltkompartiment': str,
 'releases_to': str,
 'jahresfracht_freisetzung': float,
 'versehentliche_freisetzung': float,
 'schadstoff_schwellenwert': float,
 'einheit': str,
 'unit': str,
 'bestimmungsmethode': str,
 'determination_method': str,
 'schutzgrund_fracht': str,
 'confidential_reason_release': str,
 'schutzgrund_betrieb': str,
 'confidential_reason_facility': str}

DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [13]:
#raw0 = pd.read_csv("../data/2020-05-19_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", sep=";", dtype=COL_DICT)

In [14]:
raw0 = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx", dtype=COL_DICT)

In [15]:
raw0

,jahr,kennnummer,betriebsname,betriebsname_2,betreiber,eigentuemer,plz,ort,strasse,hausnr,...,versehentliche_freisetzung,schadstoff_schwellenwert,einheit,unit,bestimmungsmethode,determination_method,schutzgrund_fracht,confidential_reason_release,schutzgrund_betrieb,confidential_reason_facility
0,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
1,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
2,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,150000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
3,2007,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,NaN,-,-,25541,Brunsbüttel,Melamidstr.,-,...,0.0,150000.0,kg/Jahr,kg/year,Schätzung,Estimation,NaN,NaN,NaN,NaN
4,2007,01-10-51048040567,Shell Deutschland Oil GmbH,Raffinerie Heide,-,-,25734,Hemmingstedt,Postfach,14 40,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71703,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,100.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71704,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,1000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71705,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,50000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71706,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71707,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN

In [16]:
raw1 = raw0.rename(columns={"jahr": "year", "betriebsname_2": "plantname", "betriebsname": "company", "kennnummer": "plantid", "ort": "place", "strasse": "street", "bundesland": "federalstate", "jahresfracht_freisetzung": "amount"})

In [17]:
raw1['plantid'] = raw1['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [18]:
#raw0 = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", error_bad_lines=False, engine="c", sep=";", low_memory=False)

In [19]:
#raw0

In [20]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
bpm.drop_duplicates(["plantid"], inplace=True)

In [21]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [22]:
insprmpr = new.copy()

In [23]:
insprmpr2 = insprmpr.copy()
insprmpr2 = insprmpr2[~insprmpr2.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
insprmpr2 = insprmpr2[insprmpr2.PRTR_Kennnummer != "-"]
insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [24]:
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("-")]
#new3['InspireID_Betrieb'] = new3['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [25]:
new3["InspireID_Betrieb"] = new3["InspireID_Betrieb"].apply(lambda x: str(x))
new3a = new3.copy()
'''
def match_inspire(name):
    if re.match(r"DE.EEA\/[0-9]+\.FACILITY", name):
        return "DE.EEA" + re.search("[0-9]+", name)[0]
        #None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bb.inspire.pf.eureg\/[0-9]+", name):
        return "BB" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.sh\/[0-9]+", name):
        return "SH" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bw.lubw.inspire.pf\/[A-Za-z]*-[0-9]+", name):
        return "BW" + re.search("[A-Za-z]*([0-9]*-)*[0-9]+$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.by.inspire.pf.ied\/S[0-9]+", name):
        return "BY" + re.search("S[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de\.hb\/[0-9]+", name):
        return "HB" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hb\/de.hb.pf.bube-eureg.([0-9]*\-*\/*)*[0-9]*", name):
        return "HB" + re.search("([0-9]*-*/*)*[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.he.0945.de7.pf.eu_industrie\/[0-9]*", name):
        return "HE" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hh\/pf.bube-eureg_\/[0-9]+", name):
        return "HH" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.mv.land.inspire.pf.bube\/[0-9]+", name):
        return "MV" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.ni.mu\/[0-9]+", name):
        return "NI" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.nw.inspire.pf.bube-eureg/arb-([0-9]*-)[0-9]+", name):
        return "NW" + re.search("([0-9]*-)[0-9]+$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.rp.inspire.pf.bube-eureg\/[0-9]+", name):
        return "RP" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sl.inspire.pf\/[0-9]+-G", name):
        return "SL" + re.search("[0-9]*-G$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sn.sax4inspire.pf\/[0-9]+", name):
        return "SN" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.st.lau.pf.anlagen-ied-euregistry\/[0-9]+", name):
        return "ST" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.th/([a-z]*[0-9]*-*)*([a-z]*[0-9]*)/[0-9]+", name):
        return "TH" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https://registry.gdi-de.org/id/de.be.pf.lisa\/[0-9]+", name):
        return "BE" + re.search("[0-9]*$", name)[0]
        # return "MLT" + re.search("[0-9]+", name)[0]
        #return None
    else:
        return name
'''
new3a["InspireID_Betrieb"] = new3a["InspireID_Betrieb"].apply(match_inspire)

<>:5: SyntaxWarning: "\/" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\/"? A raw string is also an option.
<>:5: SyntaxWarning: "\/" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\/"? A raw string is also an option.
/tmp/ipykernel_1514820/925570653.py:5: SyntaxWarning: "\/" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\/"? A raw string is also an option.
  if re.match(r"DE.EEA\/[0-9]+\.FACILITY", name):

In [26]:
new3a

,year,InspireID_Betrieb,plantid,company,Koordinaten_geo_lat_wgs84,Koordinaten_geo_long_wgs84,releases_to,pollutant,amount,eigentuemer
0,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Kohlendioxid (CO2),2.000000e+08,-
1,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Stickoxide (NOx/NO2),1.870000e+05,-
2,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Schwefeloxide (SOx/SO2),2.530000e+05,-
3,2007,SH10038068,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,53.9093138767091,9.186096,Luft,Schwefeloxide (SOx/SO2),2.130000e+05,-
4,2007,SH10039818,01-10-51048040567,Shell Deutschland Oil GmbH,54.1608132435955,9.079759,Luft,Kohlendioxid (CO2),1.140000e+09,-
...,...,...,...,...,...,...,...,...,...,...
79840,2024,TH92012855,-,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...,51.00132,11.193320,Luft,Ammoniak (NH3),1.500000e+04,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...
79841,2024,TH92012857,-,Viloss GmbH / Loßnitz,50.86695,11.426040,Luft,Ammoniak (NH3),1.240000e+04,Viloss GmbH
79842,2024,TH92012861,-,Agrarunternehmen Barnstädt e. G.,50.99689,11.537970,Luft,Ammoniak (NH3),2.650000e+04,Agrarunternehmen Barnstädt
79843,2024,TH92013060,-,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.,51.08841,11.246320,Luft,Ammoniak (NH3),4.510000e+04,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.
79844,2024,TH92013062,-,Agrarunternehmen Barnstädt,51.07202,11.606560,Luft,Ammoniak (NH3),1.400000e+04,Agrarunternehmen Barnstedt

In [27]:

#insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).replace("https://registry.gdi-de.org/id/de.ni.mu/", ""))

In [28]:
#insprmpr2 = insprmpr2[["InspireID_Betrieb", "PRTR_Kennnummer"]]

In [29]:
#insprmpr3 = insprmpr2.drop_duplicates(subset='InspireID_Betrieb', keep="first")

In [30]:
#insprmpr3

In [31]:
#raw1.loc[raw1.plantid == "03-01-01012110180"]

In [32]:
new3a.drop(columns="plantid", inplace=True)
new3a.rename(columns={"InspireID_Betrieb": "plantid"}, inplace=True)

In [33]:
seem

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1105           SD662-98  SEE927542617698
1106           SD662-98  SEE915847711449
1107           SD662-98  SEE912980761904
1108           SD662-98  SEE918332839635
1109           SD662-98  SEE922908994215

[1110 rows x 2 columns]

In [34]:
raw2 = pd.merge(raw1, bpm, how="inner", on="plantid")
new4 = pd.merge(new3a, seem, how="inner", on="plantid")

In [35]:
new4

,year,plantid,company,Koordinaten_geo_lat_wgs84,Koordinaten_geo_long_wgs84,releases_to,pollutant,amount,eigentuemer,sseid
0,2007,SH10000140,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Kohlendioxid (CO2),200000000.0,-,SEE940809994431
1,2007,SH10000140,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Kohlendioxid (CO2),200000000.0,-,SEE931197865137
2,2007,SH10000140,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Kohlendioxid (CO2),200000000.0,-,SEE914143996840
3,2007,SH10000140,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Stickoxide (NOx/NO2),187000.0,-,SEE940809994431
4,2007,SH10000140,Sasol Germany GmbH,53.9128595235255,9.157963,Luft,Stickoxide (NOx/NO2),187000.0,-,SEE931197865137
...,...,...,...,...,...,...,...,...,...,...
68722,2024,TH72012874,Heizkraftwerk Jena Süd,50.89756,11.585280,Luft,Stickoxide (NOx/NO2),104000.0,TEAG Thüringer Energie AG,SEE912583238223
68723,2024,TH72012874,Heizkraftwerk Jena Süd,50.89756,11.585280,Luft,Stickoxide (NOx/NO2),104000.0,TEAG Thüringer Energie AG,SEE969004747543
68724,2024,TH72012874,Heizkraftwerk Jena Süd,50.89756,11.585280,Luft,Stickoxide (NOx/NO2),104000.0,TEAG Thüringer Energie AG,SEE951160693116
68725,2024,TH86012942,TWS Thüringer Wärme Service GmbH,50.6862,11.328620,Luft,Kohlendioxid (CO2),107000000.0,TWS Thüringer Wärme Service,SEE925388069183
68726,2024,TH86012942,TWS Thüringer Wärme Service GmbH,50.6862,11.328620,Luft,Kohlendioxid (CO2),107000000.0,TWS Thüringer Wärme Service,SEE962906846994

In [36]:
raw2.year = raw2.year.astype(int)

In [37]:
DROP_LIST

['flusseinzugsgebiet',
 'schutzgrund_fracht',
 'confidential_reason_release',
 'schutzgrund_betrieb',
 'confidential_reason_facility',
 'versehentliche_freisetzung',
 'bestimmungsmethode',
 'determination_method',
 'einheit',
 'umweltkompartiment',
 'haupttaetigkeit',
 'taetigkeit',
 'nace_wirtschaftszweig',
 'schadstoff',
 'stoffgruppe',
 'branche',
 'schadstoff_schwellenwert',
 'sseid',
 'geo_lat_wgs84',
 'geo_long_wgs84']

In [38]:
raw3 = raw2.drop(DROP_LIST, axis=1)

In [39]:
raw3

,year,plantid,company,plantname,betreiber,eigentuemer,plz,place,street,hausnr,...,taet_nr,activity,sector,nace_id,nace_sector,substances_group,pollutant,releases_to,amount,unit
0,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,4.a.ii,Production of oxygen-containing hydrocarbons,Chemical industry,2059,Manufacture of other chemical products n.e.c.,Greenhouse gases,Carbon dioxide (CO2),Air,2.000000e+08,kg/year
1,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,4.a.ii,Production of oxygen-containing hydrocarbons,Chemical industry,2059,Manufacture of other chemical products n.e.c.,Other gases,Nitrogen oxides (NOx/NO2),Air,1.870000e+05,kg/year
2,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,4.a.ii,Production of oxygen-containing hydrocarbons,Chemical industry,2059,Manufacture of other chemical products n.e.c.,Other gases,Sulphur oxides (SOx/SO2),Air,2.530000e+05,kg/year
3,2007,01-10-51048040567,Shell Deutschland Oil GmbH,Raffinerie Heide,-,-,25734,Hemmingstedt,Postfach,14 40,...,1.a,Mineral oil and gas refineries,Energy sector,1920,Manufacture of refined petroleum products,Greenhouse gases,Carbon dioxide (CO2),Air,1.140000e+09,kg/year
4,2007,01-10-51048040567,Shell Deutschland Oil GmbH,Raffinerie Heide,-,-,25734,Hemmingstedt,Postfach,14 40,...,1.a,Mineral oil and gas refineries,Energy sector,1920,Manufacture of refined petroleum products,Other gases,Non-methane volatile organic compounds (NMVOC),Air,2.210000e+05,kg/year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15506,2022,18042,"K+S Minerals and Agriculture GmbH, Werk Zielitz",NaN,K+S Minerals and Agriculture GmbH,-,39326,Zielitz,Farsleber Str.,1,...,3.a,Underground mining and related operations,Mineral industry,891,Mining of chemical and fertiliser minerals,Other gases,Nitrogen oxides (NOx/NO2),Air,1.940000e+05,kg/year
15507,2022,18042,"K+S Minerals and Agriculture GmbH, Werk Zielitz",NaN,K+S Minerals and Agriculture GmbH,-,39326,Zielitz,Farsleber Str.,1,...,3.a,Underground mining and related operations,Mineral industry,891,Mining of chemical and fertiliser minerals,Other gases,Chlorine and inorganic compounds (as HCl),Air,1.550000e+04,kg/year
15508,2022,18042,"K+S Minerals and Agriculture GmbH, Werk Zielitz",NaN,K+S Minerals and Agriculture GmbH,-,39326,Zielitz,Farsleber Str.,1,...,3.a,Underground mining and related operations,Mineral industry,891,Mining of chemical and fertiliser minerals,Heavy metals,Lead and compounds (as Pb),Water,4.100000e+01,kg/year
15509,2022,18042,"K+S Minerals and Agriculture GmbH, Werk Zielitz",NaN,K+S Minerals and Agriculture GmbH,-,39326,Zielitz,Farsleber Str.,1,...,3.a,Underground mining and related operations,Mineral industry,891,Mining of chemical and fertiliser minerals,Heavy metals,Zinc and compounds (as Zn),Water,2.650000e+02,kg/year
15510,2022,18042,"K+S Minerals and Agriculture GmbH, Werk Zielitz",NaN,K+S Minerals and Agriculture GmbH,-,39326,Zielitz,Farsleber Str.,1,...,3.a,Underground mining and related operations,Mineral industry,891,Mining of chemical and fertiliser minerals,Inorganic substances,Chlorides (as total Cl),Water,1.240000e+08,kg/year

In [40]:
raw3['pollutant'].reset_index().groupby('pollutant').first()

                                                   index
pollutant
1,2-dichloroethane (DCE)                              80
Ammonia (NH3)                                         64
Anthracene                                           953
Arsenic and compounds (as As)                         54
Benzene                                                8
Brominated diphenylethers (PBDE)                   14580
Cadmium and compounds (as Cd)                         40
Carbon dioxide (CO2)                                   0
Carbon monoxide (CO)                                  49
Chlorides (as total Cl)                               62
Chlorine and inorganic compounds (as HCl)             14
Chlorofluorocarbons (CFCs)                           198
Chromium and compounds (as Cr)                        55
Copper and compounds (as Cu)                          56
Cyanides (as total CN)                                63
Dichloromethane (DCM)                                 84
Ethyl benzene                                        915
Fluoranthene                                         933
Fluorides (as total F)                                89
Fluorine and inorganic compounds (as HF)             128
Halogenated organic compounds (as AOX)                85
Hexachlorobenzene (HCB)                               86
Hydro-fluorocarbons (HFCs)                            66
Hydrochlorofluorocarbons(HCFCs)                       65
Hydrogen cyanide (HCN)                                45
Lead and compounds (as Pb)                            42
Mercury and compounds (as Hg)                         18
Methane (CH4)                                        215
Naphthalene                                          952
Nickel and compounds (as Ni)                           7
Nitrogen oxides (NOx/NO2)                              1
Nitrous oxide (N2O)                                   20
Non-methane volatile organic compounds (NMVOC)         4
Nonylphenol and Nonylphenol ethoxylates (NP/NPEs)    726
Octylphenols and Octylphenol ethoxylates             937
Organotin compounds(as total Sn)                     469
PCDD + PCDF (dioxins + furans) (as Teq)               43
Particulate matter (PM10)                              9
Phenols (as total C)                                  60
Polycyclic aromatic hydrocarbons (PAHs)              173
Sulphur oxides (SOx/SO2)                               2
Tetrachloroethylene (PER)                           1130
Tetrachloromethane (TCM)                            1131
Toluene                                              397
Total nitrogen                                        47
Total organic carbon (TOC) (as total C or COD/3)      61
Total phosphorus                                      48
Trichlorobenzenes (TCBs) (all isomers)               927
Trichloroethylene                                   1132
Trichloromethane                                      78
Xylenes                                              399
Zinc and compounds (as Zn)                            10

In [41]:
#raw3.loc[raw3.plantid == "03-01-01012110180"]

In [42]:
p = "PCDD + PCDF (dioxins + furans) (as Teq)"
q = "Trichlorobenzenes (TCBs) (all isomers)"
z = "Total organic carbon (TOC) (as total C or COD/3)"

In [43]:
re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

<>:1: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
<>:1: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
/tmp/ipykernel_1514820/3641376740.py:1: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
  re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

'TCBs'

In [44]:
t = "Kraftwerk Voerde OHG der STEAG GmbH und RWE"

In [45]:
match_list = ["Vattenfall", "RWE", "Uniper", "LEAG", "EnBW", "Steag"]

In [46]:
raw4 = raw3.sort_values(by="amount", ascending=False)
new5 = new4.sort_values(by="amount", ascending=False)

In [47]:
def fix_company(company):
    for name in match_list:
        if name in company:
            return name
        else:
            return company

In [48]:
def fix_pollutant(pol):
    match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)
    if match:
        return match[-1]
    else:
        return pol

<>:2: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
<>:2: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
/tmp/ipykernel_1514820/3548206704.py:2: SyntaxWarning: "\)" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\)"? A raw string is also an option.
  match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)

In [49]:
fix_pollutant(q)

'TCBs'

In [50]:
unit_2_dict = {9: "Mio. t", 6: "Tsd. t", 3: "t", 1: "kg", -3: "g", -6: "mg"}
amount_dict = {"CO2": 9, "CO": 6, "NO2": 6, "Cl": 6, "SO2": 6, "Total nitrogen": 6, "PM10": 6, "HCl": 3, "HF": 3, "N2O": 6, "Benzene": 3, "Pb": 3, "Zn": 3, "Benzene": 3, "Fluorides (as total F)": 3, "NMVOC": 3, "NH3": 3, "TOC": 3, "CH4": 3, "AOX": 3, "Total phosphorus": 3, "HCFCs": 3, "HFCs": 3, "DCE": 3, "Phenols (as total C)": 3, "Cu": 3, "PER": 3, "Cr": 3, "Trichloroethylene": 3, "Trichloromethane": 3, "TCM": 3, "CN": 3, "Ni": 3, "DCM": 3, "HCN": 3, "As": 3, "Hg": 3}
neg_dict = {"Teq": 6}

In [51]:
raw5 = raw4.copy()

In [52]:
raw4['group'] = raw4['company'].apply(lambda x: fix_company(x))
raw4['pollutant'] = raw4['pollutant'].apply(lambda x: fix_pollutant(x))
new5['group'] = new5['company'].apply(lambda x: fix_company(x))
new5['pollutant'] = new5['pollutant'].apply(lambda x: fix_pollutant(str(x)))

In [53]:
new5['potency'] = new5['pollutant'].apply(lambda x: amount_dict.get(x, 1))
new5['neg_potency'] = new5['pollutant'].apply(lambda x: neg_dict.get(x, 0))
new5['unit_2'] = new5['potency'].apply(lambda x: unit_2_dict[x])
new5['amount_2'] = new5['amount'] / 10**(new5['potency'])
new5['amount_2'] = new5['amount_2'] * 10**(new5['neg_potency'])
new5.loc[new5['pollutant'] == "Teq"] = new5.loc[new5['pollutant'] == "Teq"].replace("kg", "mg")

In [54]:
#raw4

In [55]:
raw5['potency'] = raw5['pollutant'].apply(lambda x: amount_dict.get(x, 1))

In [56]:
raw5['neg_potency'] = raw5['pollutant'].apply(lambda x: neg_dict.get(x, 0))

In [57]:
raw5['unit_2'] = raw5['potency'].apply(lambda x: unit_2_dict[x])

In [58]:
raw5['amount_2'] = raw5['amount'] / 10**(raw5['potency'])
raw5['amount_2'] = raw5['amount_2'] * 10**(raw5['neg_potency'])

In [59]:
raw5.loc[raw5['pollutant'] == "Teq"] = raw5.loc[raw5['pollutant'] == "Teq"].replace("kg", "mg")

In [60]:
#raw5

In [61]:
DROP_LIST = ['plz', 'company','plantname', 'group', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']
DROP_LIST = ['plz', 'company','plantname', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']

In [62]:
NEW_DROP_LIST_2 = ['group', 'sseid']

In [63]:
raw6 = raw5.drop(DROP_LIST, axis=1)
new6 = new5.drop(NEW_DROP_LIST_2, axis=1)

In [64]:
raw6['pollutant2'] = raw6['pollutant'] + ' [' + raw6['unit_2'] + ']'
new6['pollutant2'] = new6['pollutant'] + ' [' + new6['unit_2'] + ']'

In [65]:
#new65 = new6.drop("plantid", axis=1)

In [66]:
#new70 = pd.merge(new65, insprmpr3, how="inner", on="InspireID_Betrieb")

In [67]:
new70 = new6.copy()

In [68]:
#new70.drop_duplicates(subset="InspireID_Betrieb")

In [69]:
new70 = new70[['year', 'plantid', 'company', 'eigentuemer', 'pollutant', 'releases_to', 'amount', 'potency', 'unit_2', 'amount_2', 'pollutant2']]

In [70]:
#new71 = new70.rename(columns={"PRTR_Kennnummer": "plantid"})
new71 = new70.copy()

In [71]:
#new70.sort_values("year")

In [72]:
new71

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
26205,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26206,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26204,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26208,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26202,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
48902,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48903,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48905,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48906,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48904,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]

In [73]:
m1 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])
m2 = raw6.duplicated(['year', 'pollutant', 'plantid'])
m3 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])

In [74]:
raw6.loc[m2]

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
6288,2012,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Water,5.860000e+08,1,kg,5.860000e+07,Chlorides (as total Cl) [kg]
4100,2010,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Land,5.430000e+08,1,kg,5.430000e+07,Chlorides (as total Cl) [kg]
1914,2008,06-90031210632,-,-,Chlorides (as total Cl),Water,5.230000e+08,1,kg,5.230000e+07,Chlorides (as total Cl) [kg]
5205,2011,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Water,5.090000e+08,1,kg,5.090000e+07,Chlorides (as total Cl) [kg]
7300,2013,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Land,4.610000e+08,1,kg,4.610000e+07,Chlorides (as total Cl) [kg]
...,...,...,...,...,...,...,...,...,...,...,...
11331,2017,12358,Uniper Kraftwerke GmbH,-,Mercury and compounds (as Hg),Water,1.190000e+00,1,kg,1.190000e-01,Mercury and compounds (as Hg) [kg]
12235,2018,12358,Uniper Kraftwerke GmbH,-,Mercury and compounds (as Hg),Water,1.190000e+00,1,kg,1.190000e-01,Mercury and compounds (as Hg) [kg]
3807,2010,06-05-900-0205103,STEAG und RWE Power GKW Bergkamen Geschäftsste...,STEAG und RWE Power GKW Bergkamen Geschäftsste...,Mercury and compounds (as Hg),Water,1.140000e+00,1,kg,1.140000e-01,Mercury and compounds (as Hg) [kg]
9918,2016,06-05-500-0875785,Evonik Degussa GmbH,Evonik Degussa GmbH,Mercury and compounds (as Hg),Water,1.130000e+00,1,kg,1.130000e-01,Mercury and compounds (as Hg) [kg]
614,2007,06-05-900-0884101,-,-,Mercury and compounds (as Hg),Water,1.020000e+00,1,kg,1.020000e-01,Mercury and compounds (as Hg) [kg]

In [75]:
raw7 = raw6.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])
new7 = new71.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])

In [76]:
new7.loc[new7.releases_to == "Wasser"]

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
65761,2024,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,292800.0,3,t,292.8000,TOC [t]
65762,2024,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,Ni,Wasser,32.4,3,t,0.0324,Ni [t]
62627,2023,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,216300.0,3,t,216.3000,TOC [t]
62628,2023,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,Ni,Wasser,27.1,3,t,0.0271,Ni [t]
59351,2022,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,249000.0,3,t,249.0000,TOC [t]
...,...,...,...,...,...,...,...,...,...,...,...
4026,2007,TH62013494,K+S Standort Unterbreizbach,-,Ni,Wasser,192.0,3,t,0.1920,Ni [t]
4024,2007,TH62013494,K+S Standort Unterbreizbach,-,Ni,Wasser,192.0,3,t,0.1920,Ni [t]
4019,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]
4020,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]
4018,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]

In [77]:
#raw7.loc[raw7.plantid == "14-70-46630660001"].sort_values("potency", ascending=False)

In [78]:
#adds = pd.read_csv("additionals.csv") # manually add boxberg

In [79]:
#adds

In [80]:
raw8 = raw7.drop(['betreiber', 'eigentuemer'], axis=1)
new8 = new7.drop(['company', 'eigentuemer'], axis=1)

In [81]:
new8['releases_to'] = new8['releases_to'].replace({"Luft": "Air", "Wasser": "Water"})

In [82]:
#new9['pollutant'].reset_index().groupby('pollutant').first()

In [83]:
new8

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
65756,2024,BB16012651,NO2,Air,745000.0,6,Tsd. t,0.745000,NO2 [Tsd. t]
65754,2024,BB16012651,PM10,Air,51300.0,6,Tsd. t,0.051300,PM10 [Tsd. t]
65755,2024,BB16012651,NMVOC,Air,2119000.0,3,t,2119.000000,NMVOC [t]
62622,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
62620,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
8356,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
4044,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4043,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4045,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]
4046,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [84]:
#raw8.sort_values("amount", ascending=False)

In [85]:
#pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006

In [86]:
new8.drop_duplicates(subset=['plantid', 'pollutant', 'year', 'releases_to'], inplace=True)

In [87]:
new8.loc[new8.plantid == "BB45025611"].loc[new8.pollutant == "CO2"]

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
65912,2024,BB45025611,CO2,Air,8.081269e+09,9,Mio. t,8.081269,CO2 [Mio. t]
62805,2023,BB45025611,CO2,Air,9.713000e+09,9,Mio. t,9.713000,CO2 [Mio. t]
59529,2022,BB45025611,CO2,Air,9.640000e+09,9,Mio. t,9.640000,CO2 [Mio. t]
56039,2021,BB45025611,CO2,Air,1.190000e+10,9,Mio. t,11.900000,CO2 [Mio. t]
52692,2020,BB45025611,CO2,Air,1.040000e+10,9,Mio. t,10.400000,CO2 [Mio. t]
48968,2019,BB45025611,CO2,Air,1.060000e+10,9,Mio. t,10.600000,CO2 [Mio. t]
45080,2018,BB45025611,CO2,Air,1.250000e+10,9,Mio. t,12.500000,CO2 [Mio. t]
44472,2017,BB45025611,CO2,Air,1.150000e+10,9,Mio. t,11.500000,CO2 [Mio. t]
40703,2016,BB45025611,CO2,Air,1.230000e+10,9,Mio. t,12.300000,CO2 [Mio. t]
36769,2015,BB45025611,CO2,Air,1.230000e+10,9,Mio. t,12.300000,CO2 [Mio. t]
32913,2014,BB45025611,CO2,Air,1.170000e+10,9,Mio. t,11.700000,CO2 [Mio. t]
28895,2013,BB45025611,CO2,Air,1.140000e+10,9,Mio. t,11.400000,CO2 [Mio. t]
24861,2012,BB45025611,CO2,Air,1.260000e+10,9,Mio. t,12.600000,CO2 [Mio. t]
20719,2011,BB45025611,CO2,Air,1.190000e+10,9,Mio. t,11.900000,CO2 [Mio. t]
16532,2010,BB45025611,CO2,Air,1.120000e+10,9,Mio. t,11.200000,CO2 [Mio. t]
12249,2009,BB45025611,CO2,Air,1.070000e+10,9,Mio. t,10.700000,CO2 [Mio. t]
8071,2008,BB45025611,CO2,Air,1.250000e+10,9,Mio. t,12.500000,CO2 [Mio. t]
3945,2007,BB45025611,CO2,Air,1.240000e+10,9,Mio. t,12.400000,CO2 [Mio. t]

In [88]:
#new8 = new8.loc[new8.plantid != "NW100-0501870"]

In [89]:
new9 = new8.loc[~(new8.pollutant == "Kohlendioxid ohne Biomasse")]

In [90]:
new9

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
65756,2024,BB16012651,NO2,Air,745000.0,6,Tsd. t,0.745000,NO2 [Tsd. t]
65754,2024,BB16012651,PM10,Air,51300.0,6,Tsd. t,0.051300,PM10 [Tsd. t]
65755,2024,BB16012651,NMVOC,Air,2119000.0,3,t,2119.000000,NMVOC [t]
62622,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
62620,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
16814,2010,TH86012942,NO2,Air,104000.0,6,Tsd. t,0.104000,NO2 [Tsd. t]
12504,2009,TH86012942,NO2,Air,136000.0,6,Tsd. t,0.136000,NO2 [Tsd. t]
8357,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
4044,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4045,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [103]:
new9['pollutant'].reset_index().groupby('pollutant').first()

                                        index
pollutant
AOX                                     66322
Anthracen                                7812
As                                      65897
Benzol                                  59829
CH4                                     65954
CN                                      20570
CO                                      65874
CO2                                     65759
Cd                                      28679
Cl                                      65788
Cr                                      62650
Cu                                      28723
DCM                                     60061
EDC                                     67068
Ethylbenzol                             18314
FCKWs                                   31686
Fluoranthen                             21738
Fluoride (als Gesamt-F)                 65798
Furane                                  48907
Gesamtphosphor                          66192
Gesamtstickstoff                         7858
HCB                                     41422
HCN                                     25388
HCl                                     28674
HF                                      20741
HFCKW                                   19490
HFKWs                                   62813
Hg                                      65830
N2O                                     65847
NH3                                     32714
NMVOC                                   65755
NO2                                     65756
NPEs                                    23698
Naphthalin                              68126
Ni                                      65762
Octylphenole und Octylphenolethoxylate  55319
PAK                                     63475
PBDE                                    58802
PER                                     67061
PM10                                    65754
Pb                                      65881
Phenole (als Gesamt-C)                  66105
SO2                                     65778
Sn                                      35651
TCB                                     66514
TCM                                     67084
TOC                                     65761
Toluol                                  18316
Trichlorethylen                         25550
Trichlormethan                          60053
Xylole                                  64777
Zn                                      65765

In [104]:
new9.to_csv("pollutants_pg.csv", index=True, header=False)
new9.to_csv("pollutants.csv", index=False)
new9.to_csv("pollutants_nh.csv", index=False, header=False)

In [93]:
new8.loc[new8.duplicated(subset=['plantid', 'pollutant', 'year', 'releases_to'])]

Empty DataFrame
Columns: [year, plantid, pollutant, releases_to, amount, potency, unit_2, amount_2, pollutant2]
Index: []

In [94]:
bpm.loc[bpm.plantid == "06-05-500-0342713"]

Empty DataFrame
Columns: [plantid, sseid]
Index: []

In [95]:
#raw5.loc[raw5["pollutant"] == "Teq"].sort_values("amount", ascending=False)

In [96]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '06-05-100-0248923'].sort_values("amount", ascending=False)

In [97]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '12-40710010000'].sort_values("amount", ascending=False) #12-40710010000 #06-05-300-0923949

In [98]:
#raw4.loc[raw4['year'] == 2009].loc[raw4['plantid'] == '06-05-100-0431554'].sort_values("amount", ascending=False)

In [99]:
#raw4.groupby("pollutant").sum()

In [100]:
#raw3.groupby("pollutant").sum()

In [101]:
#raw4

In [102]:
raw8.groupby('releases_to').min()

,year,plantid,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,
Air,2007,01-10-51011005501,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [103]:
raw7.groupby('releases_to').max()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2022,18042,swb Erzeugung GmbH & Co.KG,verschiedene Eigentümer,Zinc and compounds (as Zn),3.330000e+10,3,t,3.330000e+09,Zinc and compounds (as Zn) [kg]
Land,2022,18042,K+S Minerals and Agriculture GmbH,K+S Minerals and Agriculture GmbH,Zinc and compounds (as Zn),8.260000e+08,6,kg,8.260000e+07,Zinc and compounds (as Zn) [kg]
Water,2022,18042,swb Erzeugung GmbH & Co.KG,und Karton GmbH,Zinc and compounds (as Zn),1.910000e+09,6,t,1.910000e+08,Zinc and compounds (as Zn) [kg]

In [104]:
raw7.groupby('releases_to').min()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2007,01-10-51011005501,-,-,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,-,-,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,-,-,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [109]:
new9.loc[new9.plantid == "BB45025611"].loc[new9.pollutant == "CO2"]

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
65912,2024,BB45025611,CO2,Air,8.081269e+09,9,Mio. t,8.081269,CO2 [Mio. t]
62805,2023,BB45025611,CO2,Air,9.713000e+09,9,Mio. t,9.713000,CO2 [Mio. t]
59529,2022,BB45025611,CO2,Air,9.640000e+09,9,Mio. t,9.640000,CO2 [Mio. t]
56039,2021,BB45025611,CO2,Air,1.190000e+10,9,Mio. t,11.900000,CO2 [Mio. t]
52692,2020,BB45025611,CO2,Air,1.040000e+10,9,Mio. t,10.400000,CO2 [Mio. t]
48968,2019,BB45025611,CO2,Air,1.060000e+10,9,Mio. t,10.600000,CO2 [Mio. t]
45080,2018,BB45025611,CO2,Air,1.250000e+10,9,Mio. t,12.500000,CO2 [Mio. t]
44472,2017,BB45025611,CO2,Air,1.150000e+10,9,Mio. t,11.500000,CO2 [Mio. t]
40703,2016,BB45025611,CO2,Air,1.230000e+10,9,Mio. t,12.300000,CO2 [Mio. t]
36769,2015,BB45025611,CO2,Air,1.230000e+10,9,Mio. t,12.300000,CO2 [Mio. t]
32913,2014,BB45025611,CO2,Air,1.170000e+10,9,Mio. t,11.700000,CO2 [Mio. t]
28895,2013,BB45025611,CO2,Air,1.140000e+10,9,Mio. t,11.400000,CO2 [Mio. t]
24861,2012,BB45025611,CO2,Air,1.260000e+10,9,Mio. t,12.600000,CO2 [Mio. t]
20719,2011,BB45025611,CO2,Air,1.190000e+10,9,Mio. t,11.900000,CO2 [Mio. t]
16532,2010,BB45025611,CO2,Air,1.120000e+10,9,Mio. t,11.200000,CO2 [Mio. t]
12249,2009,BB45025611,CO2,Air,1.070000e+10,9,Mio. t,10.700000,CO2 [Mio. t]
8071,2008,BB45025611,CO2,Air,1.250000e+10,9,Mio. t,12.500000,CO2 [Mio. t]
3945,2007,BB45025611,CO2,Air,1.240000e+10,9,Mio. t,12.400000,CO2 [Mio. t]

In [106]:
'''
"text/plain": [
-       "   year            plantid pollutant releases_to       amount  potency  \\\n",
-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",
-       "\n",
-       "   unit_2  amount_2    pollutant2  \n",
-       "0  Mio. t      19.1  CO2 [Mio. t]  "
-      ]
-     },

'''

'\n"text/plain": [\n-       "   year            plantid pollutant releases_to       amount  potency  \\\n",\n-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",\n-       "\n",\n-       "   unit_2  amount_2    pollutant2  \n",\n-       "0  Mio. t      19.1  CO2 [Mio. t]  "\n-      ]\n-     },\n\n'