In [1]:
import pandas as pd
import numpy as np
import re
import json

In [78]:
COL_DICT = {'jahr': int,
 'kennnummer': str,
 'betriebsname': str,
 'betriebsname_2': str,
 'plz': str,
 'ort': str,
 'strasse': str,
 'hausnr': str,
 'bundesland': str,
 'flusseinzugsgebiet': str,
 'geo_lat_wgs84': np.float64,
 'geo_long_wgs84': np.float64,
 'taet_nr': str,
 'taetigkeit': str,
 'activity': str,
 'haupttaetigkeit': str,
 'branche': str,
 'sector': str,
 'nace_id': int,
 'nace_wirtschaftszweig': str,
 'nace_sector': str,
 'stoffgruppe': str,
 'substances_group': str,
 'schadstoff': str,
 'pollutant': str,
 'umweltkompartiment': str,
 'releases_to': str,
 'jahresfracht_freisetzung': float,
 'versehentliche_freisetzung': float,
 'schadstoff_schwellenwert': float,
 'einheit': str,
 'unit': str,
 'bestimmungsmethode': str,
 'determination_method': str,
 'schutzgrund_fracht': str,
 'confidential_reason_release': str,
 'schutzgrund_betrieb': str,
 'confidential_reason_facility': str}

DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [79]:
#raw0 = pd.read_csv("../data/2020-05-19_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", sep=";", dtype=COL_DICT)

In [80]:
raw0 = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx", dtype=COL_DICT)

In [81]:
raw1 = raw0.rename(columns={"jahr": "year", "betriebsname_2": "plantname", "betriebsname": "company", "kennnummer": "plantid", "ort": "place", "strasse": "street", "bundesland": "federalstate", "jahresfracht_freisetzung": "amount"})

In [82]:
raw1['plantid'] = raw1['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [83]:
#raw0 = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", error_bad_lines=False, engine="c", sep=";", low_memory=False)

In [84]:
#raw0

In [85]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
bpm.drop_duplicates(["plantid"], inplace=True)

In [86]:
bpm

                 plantid            sseid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
8         06-10-00101000  SEE934337929126
9         06-00453010412  SEE905366486355
..                   ...              ...
940        07-05-8030815  SEE957723162266
944    16-72-73595430000  SEE988601422752
950    14-70-52316707024  SEE939899660715
952    06-05-500-0875785  SEE994351082467
985  06-09-700-9002-0001  SEE916274994887

[327 rows x 2 columns]

In [87]:
#raw1.loc[raw1.plantid == "03-01-01012110180"]

In [88]:
raw2 = pd.merge(raw1, bpm, how="inner", on="plantid")

In [89]:
raw2.year = raw2.year.astype(int)

In [90]:
DROP_LIST

['flusseinzugsgebiet',
 'schutzgrund_fracht',
 'confidential_reason_release',
 'schutzgrund_betrieb',
 'confidential_reason_facility',
 'versehentliche_freisetzung',
 'bestimmungsmethode',
 'determination_method',
 'einheit',
 'umweltkompartiment',
 'haupttaetigkeit',
 'taetigkeit',
 'nace_wirtschaftszweig',
 'schadstoff',
 'stoffgruppe',
 'branche',
 'schadstoff_schwellenwert',
 'sseid',
 'geo_lat_wgs84',
 'geo_long_wgs84']

In [91]:
list(raw2)

['year',
 'plantid',
 'company',
 'plantname',
 'betreiber',
 'eigentuemer',
 'plz',
 'place',
 'street',
 'hausnr',
 'federalstate',
 'flusseinzugsgebiet',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'taet_nr',
 'taetigkeit',
 'activity',
 'haupttaetigkeit',
 'branche',
 'sector',
 'nace_id',
 'nace_wirtschaftszweig',
 'nace_sector',
 'stoffgruppe',
 'substances_group',
 'schadstoff',
 'pollutant',
 'umweltkompartiment',
 'releases_to',
 'amount',
 'versehentliche_freisetzung',
 'schadstoff_schwellenwert',
 'einheit',
 'unit',
 'bestimmungsmethode',
 'determination_method',
 'schutzgrund_fracht',
 'confidential_reason_release',
 'schutzgrund_betrieb',
 'confidential_reason_facility',
 'sseid']

In [92]:
raw3 = raw2.drop(DROP_LIST, axis=1)

In [93]:
#raw3.loc[raw3.plantid == "03-01-01012110180"]

In [94]:
p = "PCDD + PCDF (dioxins + furans) (as Teq)"

In [95]:
q = "Trichlorobenzenes (TCBs) (all isomers)"
z = "Total organic carbon (TOC) (as total C or COD/3)"

In [96]:
re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

<>:1: SyntaxWarning: invalid escape sequence '\)'
<>:1: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_827716/3641376740.py:1: SyntaxWarning: invalid escape sequence '\)'
  re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

'TCBs'

In [97]:
t = "Kraftwerk Voerde OHG der STEAG GmbH und RWE"

In [98]:
match_list = ["Vattenfall", "RWE", "Uniper", "LEAG", "EnBW", "Steag"]

In [99]:
raw4 = raw3.sort_values(by="amount", ascending=False)

In [100]:
raw3.shape

(13883, 21)

In [101]:
raw4.shape

(13883, 21)

In [102]:
def fix_company(company):
    for name in match_list:
        if name in company:
            return name
        else:
            return company

In [103]:
def fix_pollutant(pol):
    match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)
    if match:
        return match[-1]
    else:
        return pol

<>:2: SyntaxWarning: invalid escape sequence '\)'
<>:2: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_827716/3548206704.py:2: SyntaxWarning: invalid escape sequence '\)'
  match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)

In [104]:
fix_pollutant(q)

'TCBs'

In [105]:
unit_2_dict = {9: "Mio. t", 6: "Tsd. t", 3: "t", 1: "kg", -3: "g", -6: "mg"}
amount_dict = {"CO2": 9, "CO": 6, "NO2": 6, "Cl": 6, "SO2": 6, "Total nitrogen": 6, "PM10": 6, "HCl": 3, "HF": 3, "N2O": 6, "Benzene": 3, "Pb": 3, "Zn": 3, "Benzene": 3, "Fluorides (as total F)": 3, "NMVOC": 3, "NH3": 3, "TOC": 3, "CH4": 3, "AOX": 3, "Total phosphorus": 3, "HCFCs": 3, "HFCs": 3, "DCE": 3, "Phenols (as total C)": 3, "Cu": 3, "PER": 3, "Cr": 3, "Trichloroethylene": 3, "Trichloromethane": 3, "TCM": 3, "CN": 3, "Ni": 3, "DCM": 3, "HCN": 3, "As": 3, "Hg": 3}
neg_dict = {"Teq": 6}

In [106]:
raw4['group'] = raw4['company'].apply(lambda x: fix_company(x))
raw4['pollutant'] = raw4['pollutant'].apply(lambda x: fix_pollutant(x))

In [107]:
raw5 = raw4.copy()

In [108]:
#raw4

In [109]:
raw5['potency'] = raw5['pollutant'].apply(lambda x: amount_dict.get(x, 1))

In [110]:
raw5['neg_potency'] = raw5['pollutant'].apply(lambda x: neg_dict.get(x, 0))

In [111]:
raw5['unit_2'] = raw5['potency'].apply(lambda x: unit_2_dict[x])

In [112]:
raw5['amount_2'] = raw5['amount'] / 10**(raw5['potency'])
raw5['amount_2'] = raw5['amount_2'] * 10**(raw5['neg_potency'])

In [113]:
raw5.loc[raw5['pollutant'] == "Teq"] = raw5.loc[raw5['pollutant'] == "Teq"].replace("kg", "mg")

In [114]:
#raw5

In [115]:
DROP_LIST = ['plz', 'company','plantname', 'group', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']

In [116]:
raw6 = raw5.drop(DROP_LIST, axis=1)

In [117]:
raw6['pollutant2'] = raw6['pollutant'] + ' [' + raw6['unit_2'] + ']'

In [118]:
raw6

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
6067,2013,06-05-100-0248923,RWE Power AG Kraftwerk Neurath,RWE Power AG Kraftwerk Neurath,CO2,Air,3.330000e+10,9,Mio. t,33.3,CO2 [Mio. t]
6971,2014,06-05-100-0248923,RWE Power AG Kraftwerk Neurath,RWE Power AG Kraftwerk Neurath,CO2,Air,3.240000e+10,9,Mio. t,32.4,CO2 [Mio. t]
10438,2018,06-05-100-0248923,RWE Power AG Kraftwerk Neurath,RWE Power AG Kraftwerk Neurath,CO2,Air,3.220000e+10,9,Mio. t,32.2,CO2 [Mio. t]
7875,2015,06-05-100-0248923,RWE Power AG Kraftwerk Neurath,RWE Power AG Kraftwerk Neurath,CO2,Air,3.210000e+10,9,Mio. t,32.1,CO2 [Mio. t]
8747,2016,06-05-100-0248923,RWE Power AG Kraftwerk Neurath,RWE Power AG Kraftwerk Neurath,CO2,Air,3.130000e+10,9,Mio. t,31.3,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
7727,2015,03-03-03030273580,Dow Deutschland Anlagengesellschaft mbH,Dow Deutschland Anlagengesellschaft mbH,Teq,Water,1.310000e-04,1,mg,13.1,Teq [mg]
8435,2015,12-40710010000,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,Teq,Air,1.300000e-04,1,mg,13.0,Teq [mg]
5140,2012,06-05-100-0431554,STEAG GmbH,STEAG GmbH,Teq,Air,1.300000e-04,1,mg,13.0,Teq [mg]
2302,2009,06-05-300-0923949,RheinEnergie AG,RheinEnergie AG,Teq,Air,1.150000e-04,1,mg,11.5,Teq [mg]
11719,2019,12-40710010000,LEAG Lausitz Energie Kraftwerk AG,EPH,Teq,Air,1.100000e-04,1,mg,11.0,Teq [mg]

In [119]:
m1 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])
m2 = raw6.duplicated(['year', 'pollutant', 'plantid'])
m3 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])

In [120]:
raw7 = raw6.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])

In [121]:
raw7.loc[raw7.releases_to == "Water"]

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
13216,2022,03-01-01241117210,Volkswagen AG,Volkswagen AG,Zn,Water,184.0,3,t,0.1840,Zn [t]
13215,2022,03-01-01241117210,Volkswagen AG,Volkswagen AG,Ni,Water,86.2,3,t,0.0862,Ni [t]
12520,2021,03-01-01241117210,Volkswagen AG,Volkswagen AG,Zn,Water,224.0,3,t,0.2240,Zn [t]
12519,2021,03-01-01241117210,Volkswagen AG,Volkswagen AG,Ni,Water,162.0,3,t,0.1620,Ni [t]
11841,2020,03-01-01241117210,V0lkswagen AG,Volkswagen AG,Zn,Water,148.0,3,t,0.1480,Zn [t]
...,...,...,...,...,...,...,...,...,...,...,...
2919,2009,18042,-,-,Cl,Water,78800000.0,6,Tsd. t,78.8000,Cl [Tsd. t]
2918,2009,18042,-,-,Zn,Water,140.0,3,t,0.1400,Zn [t]
1948,2008,18042,-,-,Cl,Water,96700000.0,6,Tsd. t,96.7000,Cl [Tsd. t]
1945,2008,18042,-,-,Zn,Water,272.0,3,t,0.2720,Zn [t]
1946,2008,18042,-,-,Pb,Water,32.5,3,t,0.0325,Pb [t]

In [122]:
raw7.loc[raw7.plantid == "14-70-46630660001"].sort_values("potency", ascending=False)

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
13825,2022,14-70-46630660001,Lausitz Energie Kraftwerke AG,EPH und PPF Investments,CO2,Air,1.910000e+10,9,Mio. t,19.10,CO2 [Mio. t]
12448,2020,14-70-46630660001,Lausitz Energie Kraftwerke AG,EPH und PPF Investments,CO2,Air,1.540000e+10,9,Mio. t,15.40,CO2 [Mio. t]
13133,2021,14-70-46630660001,Lausitz Energie Kraftwerke AG,EPH und PPF Investments,CO2,Air,1.560000e+10,9,Mio. t,15.60,CO2 [Mio. t]
10995,2018,14-70-46630660001,LEAG Lausitz Energie Kraftwerke AG,EPH,CO2,Air,1.910000e+10,9,Mio. t,19.10,CO2 [Mio. t]
11759,2019,14-70-46630660001,LEAG Lausitz Energie Kraftwerke AG,EPH,CO2,Air,1.870000e+10,9,Mio. t,18.70,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
9360,2016,14-70-46630660001,LEAG Lausitz Energie Kraftwerke AG,EPH,Cd,Air,4.890000e+01,1,kg,4.89,Cd [kg]
7630,2014,14-70-46630660001,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,Cd,Air,6.000000e+01,1,kg,6.00,Cd [kg]
8489,2015,14-70-46630660001,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,Cd,Air,3.800000e+01,1,kg,3.80,Cd [kg]
5797,2012,14-70-46630660001,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,Cd,Air,1.370000e+01,1,kg,1.37,Cd [kg]
4830,2011,14-70-46630660001,Vattenfall Europe Generation AG,Vattenfall Europe Generation AG,Cd,Air,2.200000e+01,1,kg,2.20,Cd [kg]

In [123]:
#adds = pd.read_csv("additionals.csv") # manually add boxberg

In [124]:
#adds

In [125]:
raw8 = raw7.drop(['betreiber', 'eigentuemer'], axis=1)

In [126]:
raw8

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
13196,2022,01-50-01000004838,CO2,Air,545000000.0,9,Mio. t,0.5450,CO2 [Mio. t]
13198,2022,01-50-01000004838,SO2,Air,188000.0,6,Tsd. t,0.1880,SO2 [Tsd. t]
13197,2022,01-50-01000004838,NO2,Air,165000.0,6,Tsd. t,0.1650,NO2 [Tsd. t]
13199,2022,01-50-01000004838,HCl,Air,47100.0,3,t,47.1000,HCl [t]
12500,2021,01-50-01000004838,CO2,Air,593000000.0,9,Mio. t,0.5930,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...
1948,2008,18042,Cl,Water,96700000.0,6,Tsd. t,96.7000,Cl [Tsd. t]
1943,2008,18042,NO2,Air,328000.0,6,Tsd. t,0.3280,NO2 [Tsd. t]
1944,2008,18042,HCl,Air,17800.0,3,t,17.8000,HCl [t]
1945,2008,18042,Zn,Water,272.0,3,t,0.2720,Zn [t]
1946,2008,18042,Pb,Water,32.5,3,t,0.0325,Pb [t]

In [127]:
#raw8.sort_values("amount", ascending=False)

In [128]:
#pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006

In [129]:
raw8.to_csv("pollutants_pg.csv", index=True, header=False)
raw8.to_csv("pollutants.csv", index=False)
raw8.to_csv("pollutants_nh.csv", index=False, header=False)

In [130]:
bpm.loc[bpm.plantid == "06-05-500-0342713"]

Empty DataFrame
Columns: [plantid, sseid]
Index: []

In [56]:
#raw5.loc[raw5["pollutant"] == "Teq"].sort_values("amount", ascending=False)

In [57]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '06-05-100-0248923'].sort_values("amount", ascending=False)

In [58]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '12-40710010000'].sort_values("amount", ascending=False) #12-40710010000 #06-05-300-0923949

In [59]:
#raw4.loc[raw4['year'] == 2009].loc[raw4['plantid'] == '06-05-100-0431554'].sort_values("amount", ascending=False)

In [60]:
#raw4.groupby("pollutant").sum()

In [61]:
#raw3.groupby("pollutant").sum()

In [62]:
#raw4

In [131]:
raw8.groupby('releases_to').min()

,year,plantid,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,
Air,2007,01-50-01000004838,As,0.000110,1,Mio. t,0.010,As [t]
Land,2008,06-90031210632,AOX,15.000000,3,Tsd. t,0.015,AOX [t]
Water,2007,03-01-01241117210,AOX,0.000131,1,Tsd. t,0.001,AOX [t]

In [134]:
raw7.groupby('releases_to').max()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2022,18042,swb Erzeugung GmbH & Co.KG,verschiedene Eigentümer,Zn,3.330000e+10,9,t,1980.0,Zn [t]
Land,2022,18042,K+S Minerals and Agriculture GmbH,K+S Minerals and Agriculture GmbH,Zn,8.260000e+08,6,t,826.0,Zn [t]
Water,2022,18042,swb Erzeugung GmbH & Co.KG,swb Erzeugung GmbH & Co.KG,Zn,1.910000e+09,6,t,3160.0,Zn [t]

In [133]:
raw7.groupby('releases_to').min()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2007,01-50-01000004838,-,-,As,0.000110,1,Mio. t,0.010,As [t]
Land,2008,06-90031210632,-,-,AOX,15.000000,3,Tsd. t,0.015,AOX [t]
Water,2007,03-01-01241117210,-,-,AOX,0.000131,1,Tsd. t,0.001,AOX [t]

In [135]:
raw7

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
13196,2022,01-50-01000004838,Stadtwerke Flensburg GmbH,Stadtwerke Flensburg GmbH,CO2,Air,545000000.0,9,Mio. t,0.5450,CO2 [Mio. t]
13198,2022,01-50-01000004838,Stadtwerke Flensburg GmbH,Stadtwerke Flensburg GmbH,SO2,Air,188000.0,6,Tsd. t,0.1880,SO2 [Tsd. t]
13197,2022,01-50-01000004838,Stadtwerke Flensburg GmbH,Stadtwerke Flensburg GmbH,NO2,Air,165000.0,6,Tsd. t,0.1650,NO2 [Tsd. t]
13199,2022,01-50-01000004838,Stadtwerke Flensburg GmbH,Stadtwerke Flensburg GmbH,HCl,Air,47100.0,3,t,47.1000,HCl [t]
12500,2021,01-50-01000004838,Stadtwerke Flensburg GmbH,Stadtwerke Flensburg GmbH,CO2,Air,593000000.0,9,Mio. t,0.5930,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
1948,2008,18042,-,-,Cl,Water,96700000.0,6,Tsd. t,96.7000,Cl [Tsd. t]
1943,2008,18042,-,-,NO2,Air,328000.0,6,Tsd. t,0.3280,NO2 [Tsd. t]
1944,2008,18042,-,-,HCl,Air,17800.0,3,t,17.8000,HCl [t]
1945,2008,18042,-,-,Zn,Water,272.0,3,t,0.2720,Zn [t]
1946,2008,18042,-,-,Pb,Water,32.5,3,t,0.0325,Pb [t]

In [67]:
'''
"text/plain": [
-       "   year            plantid pollutant releases_to       amount  potency  \\\n",
-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",
-       "\n",
-       "   unit_2  amount_2    pollutant2  \n",
-       "0  Mio. t      19.1  CO2 [Mio. t]  "
-      ]
-     },

'''

'\n"text/plain": [\n-       "   year            plantid pollutant releases_to       amount  potency  \\\n",\n-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",\n-       "\n",\n-       "   unit_2  amount_2    pollutant2  \n",\n-       "0  Mio. t      19.1  CO2 [Mio. t]  "\n-      ]\n-     },\n\n'