In [1]:
import pandas as pd
import numpy as np
import re
import json
from helper import match_inspire

In [2]:
NEW_COL_DICT = {
    'Berichtsjahr': int,
    'InspireID_Betrieb': str,
    'PRTR_Kennnummer': str,
 'Bundesland': str,
 'Name_Betrieb': str,
 'Adresse_PLZ': str,
 'Adresse_Ort': str,
 'Adresse_Str': str,
 'Adresse_Str_Nr': str,
 'Koordinaten': str,
 'Flusseinzugsgebiet': str,
 'Status_Betrieb': str,
 'Anmerkungen_des_Betreibers': str,
 'Kompartiment': str,
 'E_PRTR_Hauptaktivitaet': str,
 'Taetigkeit': str,
 'Branche': str,
 'Stoffgruppe': str,
 'Schadstoff': str,
 'Schadstoffmenge_(kg/Jahr)': float,
 'versehentliche_Freisetzung_(kg/Jahr)': float,
 'Bestimmungsmethode': str,
 'Bestimmungsverfahren': str,
 'Bemerkungen_Bestimmungsverfahren': str,
 'Geheimhaltungsgrund_Name_Betrieb': str,
 'Geheimhaltungsgrund_Adresse': str,
 'Geheimhaltungsgrund_Schadstoff': str,
 'Geheimhaltungsgrund_Betriebsdaten': str,
 'NACE_Code': str,
 'NACE_Wirtschaftszweig': str,
 'Anzahl_Anlagen': str,
 'Muttergesellschaft': str,
 'Geheimhaltungsgrund_Muttergesellschaft': str}

In [3]:
new = pd.read_excel("../data/E-PRTR_Deutschland_Freisetzung_2007-2023_2025-03-19.xlsx", dtype=NEW_COL_DICT)

In [4]:
DROP_LIST_NEW = ['Geheimhaltungsgrund_Muttergesellschaft', 'Anzahl_Anlagen', 'NACE_Wirtschaftszweig','NACE_Code','Geheimhaltungsgrund_Name_Betrieb', 'Geheimhaltungsgrund_Adresse', 'Geheimhaltungsgrund_Schadstoff',
 'Geheimhaltungsgrund_Betriebsdaten', 'Bestimmungsmethode', 'Bestimmungsverfahren', 'Bemerkungen_Bestimmungsverfahren','versehentliche_Freisetzung_(kg/Jahr)','Anmerkungen_des_Betreibers',
 'E_PRTR_Hauptaktivitaet', 'Taetigkeit', 'Branche', 'Adresse_PLZ','Adresse_Ort','Stoffgruppe',
 'Adresse_Str', 'Adresse_Str_Nr', 'Koordinaten','Bundesland', 'Flusseinzugsgebiet', 'Status_Betrieb',]

In [5]:
new2 = new.drop(DROP_LIST_NEW, axis=1)

In [6]:
new3 = new2.rename(columns={"Berichtsjahr": "year", "PRTR_Kennnummer": "plantid", "Name_Betrieb": "company", "Muttergesellschaft": "eigentuemer", "Schadstoffmenge_(kg/Jahr)": "amount",
                           "Schadstoff": 'pollutant','Kompartiment': 'releases_to'})

In [7]:
#list(raw3)

In [8]:
list(new3)

['year',
 'InspireID_Betrieb',
 'plantid',
 'company',
 'releases_to',
 'pollutant',
 'amount',
 'eigentuemer']

In [9]:
#list(raw0)

In [10]:
DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [11]:
#list(new)

In [12]:
COL_DICT = {'jahr': int,
 'kennnummer': str,
 'betriebsname': str,
 'betriebsname_2': str,
 'plz': str,
 'ort': str,
 'strasse': str,
 'hausnr': str,
 'bundesland': str,
 'flusseinzugsgebiet': str,
 'geo_lat_wgs84': np.float64,
 'geo_long_wgs84': np.float64,
 'taet_nr': str,
 'taetigkeit': str,
 'activity': str,
 'haupttaetigkeit': str,
 'branche': str,
 'sector': str,
 'nace_id': int,
 'nace_wirtschaftszweig': str,
 'nace_sector': str,
 'stoffgruppe': str,
 'substances_group': str,
 'schadstoff': str,
 'pollutant': str,
 'umweltkompartiment': str,
 'releases_to': str,
 'jahresfracht_freisetzung': float,
 'versehentliche_freisetzung': float,
 'schadstoff_schwellenwert': float,
 'einheit': str,
 'unit': str,
 'bestimmungsmethode': str,
 'determination_method': str,
 'schutzgrund_fracht': str,
 'confidential_reason_release': str,
 'schutzgrund_betrieb': str,
 'confidential_reason_facility': str}

DROP_LIST = ['flusseinzugsgebiet', 'schutzgrund_fracht', 'confidential_reason_release', 'schutzgrund_betrieb', 'confidential_reason_facility', 'versehentliche_freisetzung', 'bestimmungsmethode', 'determination_method', 'einheit', 'umweltkompartiment', 'haupttaetigkeit', 'taetigkeit', 'nace_wirtschaftszweig', 'schadstoff', 'stoffgruppe', 'branche', 'schadstoff_schwellenwert', 'sseid', 'geo_lat_wgs84', 'geo_long_wgs84']

In [13]:
#raw0 = pd.read_csv("../data/2020-05-19_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", sep=";", dtype=COL_DICT)

In [14]:
raw0 = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx", dtype=COL_DICT)

In [15]:
raw0

,jahr,kennnummer,betriebsname,betriebsname_2,betreiber,eigentuemer,plz,ort,strasse,hausnr,...,versehentliche_freisetzung,schadstoff_schwellenwert,einheit,unit,bestimmungsmethode,determination_method,schutzgrund_fracht,confidential_reason_release,schutzgrund_betrieb,confidential_reason_facility
0,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
1,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,100000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
2,2007,01-10-51011005501,Sasol Germany GmbH,NaN,-,-,25541,Brunsbüttel,Fritz-Staiger-Str.,15,...,0.0,150000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
3,2007,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,NaN,-,-,25541,Brunsbüttel,Melamidstr.,-,...,0.0,150000.0,kg/Jahr,kg/year,Schätzung,Estimation,NaN,NaN,NaN,NaN
4,2007,01-10-51048040567,Shell Deutschland Oil GmbH,Raffinerie Heide,-,-,25734,Hemmingstedt,Postfach,14 40,...,0.0,100000000.0,kg/Jahr,kg/year,Berechnung,Calculation,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71703,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,100.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71704,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,1000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71705,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,50000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71706,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN
71707,2022,20397,Gelsenwasser Industrieservice GmbH,NaN,AWS GmbH,-,06258,Schkopau,Bau,M954,...,0.0,2000.0,kg/Jahr,kg/year,Messung,Measurement,NaN,NaN,NaN,NaN

In [16]:
raw1 = raw0.rename(columns={"jahr": "year", "betriebsname_2": "plantname", "betriebsname": "company", "kennnummer": "plantid", "ort": "place", "strasse": "street", "bundesland": "federalstate", "jahresfracht_freisetzung": "amount"})

In [17]:
raw1['plantid'] = raw1['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [18]:
#raw0 = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", encoding="iso-8859-1", error_bad_lines=False, engine="c", sep=";", low_memory=False)

In [19]:
#raw0

In [20]:
bpm = pd.read_csv("../basic/plant_sse_mapper.csv")
bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
bpm.drop_duplicates(["plantid"], inplace=True)

In [21]:
#bpm = pd.read_csv("../basic/block_plant_mapper.csv")
raw_sse = pd.read_csv("../basic/inspire_prtr_mapper.csv")
see = raw_sse.rename(columns={"InspireID_Betrieb": "plantid"})
seem = see[['plantid', 'sseid']]
#bpm['plantid'] = bpm['plantid'].apply(lambda x: str(x).replace('/', '_'))
seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

/tmp/ipykernel_1957022/2092039524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seem['plantid'] = seem['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [22]:
insprmpr = new.copy()

In [23]:
insprmpr2 = insprmpr.copy()
insprmpr2 = insprmpr2[~insprmpr2.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
insprmpr2 = insprmpr2[insprmpr2.PRTR_Kennnummer != "-"]
insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [24]:
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("inspire.ec.europa.eu")]
#new3 = new3[~new3.PRTR_Kennnummer.str.contains("-")]
#new3['InspireID_Betrieb'] = new3['InspireID_Betrieb'].apply(lambda x: str(x).split("/")[-1])

In [25]:
new3["InspireID_Betrieb"] = new3["InspireID_Betrieb"].apply(lambda x: str(x))
new3a = new3.copy()
'''
def match_inspire(name):
    if re.match(r"DE.EEA\/[0-9]+\.FACILITY", name):
        return "DE.EEA" + re.search("[0-9]+", name)[0]
        #None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bb.inspire.pf.eureg\/[0-9]+", name):
        return "BB" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.sh\/[0-9]+", name):
        return "SH" + re.search("[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.bw.lubw.inspire.pf\/[A-Za-z]*-[0-9]+", name):
        return "BW" + re.search("[A-Za-z]*([0-9]*-)*[0-9]+$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.by.inspire.pf.ied\/S[0-9]+", name):
        return "BY" + re.search("S[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de\.hb\/[0-9]+", name):
        return "HB" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hb\/de.hb.pf.bube-eureg.([0-9]*\-*\/*)*[0-9]*", name):
        return "HB" + re.search("([0-9]*-*/*)*[0-9]+", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.he.0945.de7.pf.eu_industrie\/[0-9]*", name):
        return "HE" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.hh\/pf.bube-eureg_\/[0-9]+", name):
        return "HH" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.mv.land.inspire.pf.bube\/[0-9]+", name):
        return "MV" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https:\/\/registry.gdi-de.org\/id\/de.ni.mu\/[0-9]+", name):
        return "NI" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.nw.inspire.pf.bube-eureg/arb-([0-9]*-)[0-9]+", name):
        return "NW" + re.search("([0-9]*-)[0-9]+$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.rp.inspire.pf.bube-eureg\/[0-9]+", name):
        return "RP" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sl.inspire.pf\/[0-9]+-G", name):
        return "SL" + re.search("[0-9]*-G$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.sn.sax4inspire.pf\/[0-9]+", name):
        return "SN" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.st.lau.pf.anlagen-ied-euregistry\/[0-9]+", name):
        return "ST" + re.search("[0-9]*$", name)[0]
        #return None
    elif re.match(r"https://registry.gdi-de.org/id/de.th/([a-z]*[0-9]*-*)*([a-z]*[0-9]*)/[0-9]+", name):
        return "TH" + re.search("[0-9]+$", name)[0]
        # return None
    elif re.match(r"https://registry.gdi-de.org/id/de.be.pf.lisa\/[0-9]+", name):
        return "BE" + re.search("[0-9]*$", name)[0]
        # return "MLT" + re.search("[0-9]+", name)[0]
        #return None
    else:
        return name
'''
new3a["InspireID_Betrieb"] = new3a["InspireID_Betrieb"].apply(match_inspire)

<>:3: SyntaxWarning: invalid escape sequence '\/'
<>:3: SyntaxWarning: invalid escape sequence '\/'
/tmp/ipykernel_1957022/925570653.py:3: SyntaxWarning: invalid escape sequence '\/'
  '''

In [26]:
new3a

,year,InspireID_Betrieb,plantid,company,releases_to,pollutant,amount,eigentuemer
0,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Kohlendioxid (CO2),2.000000e+08,-
1,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Stickoxide (NOx/NO2),1.870000e+05,-
2,2007,SH10000140,01-10-51011005501,Sasol Germany GmbH,Luft,Schwefeloxide (SOx/SO2),2.530000e+05,-
3,2007,SH10038068,01-10-51011008130,TOTAL Bitumen Deutschland GmbH,Luft,Schwefeloxide (SOx/SO2),2.130000e+05,-
4,2007,SH10039818,01-10-51048040567,Shell Deutschland Oil GmbH,Luft,Kohlendioxid (CO2),1.140000e+09,-
...,...,...,...,...,...,...,...,...
75385,2023,TH92012855,-,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...,Luft,Ammoniak (NH3),1.590000e+04,Ferkelproduktion Agro Pig GmbH & Co. KG Nieder...
75386,2023,TH92012857,-,Viloss GmbH / Loßnitz,Luft,Ammoniak (NH3),1.240000e+04,Viloss GmbH
75387,2023,TH92012861,-,Agrarunternehmen Barnstädt e. G.,Luft,Ammoniak (NH3),2.730000e+04,Agrarunternehmen Barnstädt
75388,2023,TH92013060,-,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.,Luft,Ammoniak (NH3),4.340000e+04,VAN ASTEN Tierzucht Neumark GmbH & Co. KG i.G.
75389,2023,TH92013062,-,Agrarunternehmen Barnstädt,Luft,Ammoniak (NH3),1.350000e+04,Agrarunternehmen Barnstedt

In [27]:

#insprmpr2['InspireID_Betrieb'] = insprmpr2['InspireID_Betrieb'].apply(lambda x: str(x).replace("https://registry.gdi-de.org/id/de.ni.mu/", ""))

In [28]:
#insprmpr2 = insprmpr2[["InspireID_Betrieb", "PRTR_Kennnummer"]]

In [29]:
#insprmpr3 = insprmpr2.drop_duplicates(subset='InspireID_Betrieb', keep="first")

In [30]:
#insprmpr3

In [31]:
#raw1.loc[raw1.plantid == "03-01-01012110180"]

In [32]:
new3a.drop(columns="plantid", inplace=True)
new3a.rename(columns={"InspireID_Betrieb": "plantid"}, inplace=True)

In [33]:
seem

                plantid            sseid
0      06-02-B10117A007  SEE987197130805
1      06-02-B10117A007  SEE913896693631
2     06-05-100-0030723          BNA1084
3     06-05-100-0431554          BNA0992
4     06-05-100-0431554          BNA0991
...                 ...              ...
1103           SD662-98  SEE927542617698
1104           SD662-98  SEE915847711449
1105           SD662-98  SEE912980761904
1106           SD662-98  SEE918332839635
1107           SD662-98  SEE922908994215

[1108 rows x 2 columns]

In [34]:
raw2 = pd.merge(raw1, bpm, how="inner", on="plantid")
new4 = pd.merge(new3a, seem, how="inner", on="plantid")

In [35]:
new4

,year,plantid,company,releases_to,pollutant,amount,eigentuemer,sseid
0,2007,SH10000140,Sasol Germany GmbH,Luft,Kohlendioxid (CO2),200000000.0,-,SEE940809994431
1,2007,SH10000140,Sasol Germany GmbH,Luft,Kohlendioxid (CO2),200000000.0,-,SEE931197865137
2,2007,SH10000140,Sasol Germany GmbH,Luft,Kohlendioxid (CO2),200000000.0,-,SEE914143996840
3,2007,SH10000140,Sasol Germany GmbH,Luft,Stickoxide (NOx/NO2),187000.0,-,SEE940809994431
4,2007,SH10000140,Sasol Germany GmbH,Luft,Stickoxide (NOx/NO2),187000.0,-,SEE931197865137
...,...,...,...,...,...,...,...,...
65140,2023,TH72012874,Heizkraftwerk Jena Süd,Luft,Kohlendioxid (CO2),177000000.0,TEAG Thüringer Energie AG,SEE912583238223
65141,2023,TH72012874,Heizkraftwerk Jena Süd,Luft,Kohlendioxid (CO2),177000000.0,TEAG Thüringer Energie AG,SEE969004747543
65142,2023,TH72012874,Heizkraftwerk Jena Süd,Luft,Kohlendioxid (CO2),177000000.0,TEAG Thüringer Energie AG,SEE951160693116
65143,2023,TH86012942,TWS Thüringer Wärme Service GmbH,Luft,Kohlendioxid (CO2),111000000.0,TWS Thüringer Wärme Service,SEE925388069183
65144,2023,TH86012942,TWS Thüringer Wärme Service GmbH,Luft,Kohlendioxid (CO2),111000000.0,TWS Thüringer Wärme Service,SEE962906846994

In [36]:
raw2.year = raw2.year.astype(int)

In [37]:
DROP_LIST

['flusseinzugsgebiet',
 'schutzgrund_fracht',
 'confidential_reason_release',
 'schutzgrund_betrieb',
 'confidential_reason_facility',
 'versehentliche_freisetzung',
 'bestimmungsmethode',
 'determination_method',
 'einheit',
 'umweltkompartiment',
 'haupttaetigkeit',
 'taetigkeit',
 'nace_wirtschaftszweig',
 'schadstoff',
 'stoffgruppe',
 'branche',
 'schadstoff_schwellenwert',
 'sseid',
 'geo_lat_wgs84',
 'geo_long_wgs84']

In [38]:
raw3 = raw2.drop(DROP_LIST, axis=1)

In [39]:
#raw3.loc[raw3.plantid == "03-01-01012110180"]

In [40]:
p = "PCDD + PCDF (dioxins + furans) (as Teq)"
q = "Trichlorobenzenes (TCBs) (all isomers)"
z = "Total organic carbon (TOC) (as total C or COD/3)"

In [41]:
re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

<>:1: SyntaxWarning: invalid escape sequence '\)'
<>:1: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_1957022/3641376740.py:1: SyntaxWarning: invalid escape sequence '\)'
  re.findall("([A-Z]{2,}[A-Za-z]*?)\)",q)[-1]

'TCBs'

In [42]:
t = "Kraftwerk Voerde OHG der STEAG GmbH und RWE"

In [43]:
match_list = ["Vattenfall", "RWE", "Uniper", "LEAG", "EnBW", "Steag"]

In [44]:
raw4 = raw3.sort_values(by="amount", ascending=False)
new5 = new4.sort_values(by="amount", ascending=False)

In [45]:
def fix_company(company):
    for name in match_list:
        if name in company:
            return name
        else:
            return company

In [46]:
def fix_pollutant(pol):
    match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)
    if match:
        return match[-1]
    else:
        return pol

<>:2: SyntaxWarning: invalid escape sequence '\)'
<>:2: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipykernel_1957022/3548206704.py:2: SyntaxWarning: invalid escape sequence '\)'
  match = re.findall("([A-Z]{1,}[0-9]*[A-Za-z]+[0-9]*?)\)",pol)

In [47]:
fix_pollutant(q)

'TCBs'

In [48]:
unit_2_dict = {9: "Mio. t", 6: "Tsd. t", 3: "t", 1: "kg", -3: "g", -6: "mg"}
amount_dict = {"CO2": 9, "CO": 6, "NO2": 6, "Cl": 6, "SO2": 6, "Total nitrogen": 6, "PM10": 6, "HCl": 3, "HF": 3, "N2O": 6, "Benzene": 3, "Pb": 3, "Zn": 3, "Benzene": 3, "Fluorides (as total F)": 3, "NMVOC": 3, "NH3": 3, "TOC": 3, "CH4": 3, "AOX": 3, "Total phosphorus": 3, "HCFCs": 3, "HFCs": 3, "DCE": 3, "Phenols (as total C)": 3, "Cu": 3, "PER": 3, "Cr": 3, "Trichloroethylene": 3, "Trichloromethane": 3, "TCM": 3, "CN": 3, "Ni": 3, "DCM": 3, "HCN": 3, "As": 3, "Hg": 3}
neg_dict = {"Teq": 6}

In [49]:
raw5 = raw4.copy()

In [50]:
raw4['group'] = raw4['company'].apply(lambda x: fix_company(x))
raw4['pollutant'] = raw4['pollutant'].apply(lambda x: fix_pollutant(x))
new5['group'] = new5['company'].apply(lambda x: fix_company(x))
new5['pollutant'] = new5['pollutant'].apply(lambda x: fix_pollutant(str(x)))

In [51]:
new5['potency'] = new5['pollutant'].apply(lambda x: amount_dict.get(x, 1))
new5['neg_potency'] = new5['pollutant'].apply(lambda x: neg_dict.get(x, 0))
new5['unit_2'] = new5['potency'].apply(lambda x: unit_2_dict[x])
new5['amount_2'] = new5['amount'] / 10**(new5['potency'])
new5['amount_2'] = new5['amount_2'] * 10**(new5['neg_potency'])
new5.loc[new5['pollutant'] == "Teq"] = new5.loc[new5['pollutant'] == "Teq"].replace("kg", "mg")

In [52]:
#raw4

In [53]:
raw5['potency'] = raw5['pollutant'].apply(lambda x: amount_dict.get(x, 1))

In [54]:
raw5['neg_potency'] = raw5['pollutant'].apply(lambda x: neg_dict.get(x, 0))

In [55]:
raw5['unit_2'] = raw5['potency'].apply(lambda x: unit_2_dict[x])

In [56]:
raw5['amount_2'] = raw5['amount'] / 10**(raw5['potency'])
raw5['amount_2'] = raw5['amount_2'] * 10**(raw5['neg_potency'])

In [57]:
raw5.loc[raw5['pollutant'] == "Teq"] = raw5.loc[raw5['pollutant'] == "Teq"].replace("kg", "mg")

In [58]:
#raw5

In [59]:
DROP_LIST = ['plz', 'company','plantname', 'group', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']
DROP_LIST = ['plz', 'company','plantname', 'federalstate',  'place', 'street', 'hausnr', 'taet_nr', 'nace_id', 'substances_group', 'unit', 'activity', 'sector', 'nace_sector', 'neg_potency']

In [60]:
NEW_DROP_LIST_2 = ['group', 'sseid']

In [61]:
raw6 = raw5.drop(DROP_LIST, axis=1)
new6 = new5.drop(NEW_DROP_LIST_2, axis=1)

In [62]:
raw6['pollutant2'] = raw6['pollutant'] + ' [' + raw6['unit_2'] + ']'
new6['pollutant2'] = new6['pollutant'] + ' [' + new6['unit_2'] + ']'

In [63]:
#new65 = new6.drop("plantid", axis=1)

In [64]:
#new70 = pd.merge(new65, insprmpr3, how="inner", on="InspireID_Betrieb")

In [65]:
new70 = new6.copy()

In [66]:
#new70.drop_duplicates(subset="InspireID_Betrieb")

In [67]:
new70 = new70[['year', 'plantid', 'company', 'eigentuemer', 'pollutant', 'releases_to', 'amount', 'potency', 'unit_2', 'amount_2', 'pollutant2']]

In [68]:
#new71 = new70.rename(columns={"PRTR_Kennnummer": "plantid"})
new71 = new70.copy()

In [69]:
#new70.sort_values("year")

In [70]:
new71

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
26214,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26210,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26212,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26211,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
26209,2013,NW100-0248923,RWE Power AG,RWE Power AG Kraftwerk Neurath,CO2,Luft,3.330000e+10,9,Mio. t,33.300000,CO2 [Mio. t]
...,...,...,...,...,...,...,...,...,...,...,...
48705,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48706,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48707,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48702,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]
48703,2019,BB45025564,"LEAG, Kraftwerk Jänschwalde",LEAG Lausitz Energie Kraftwerk AG,Furane,Luft,1.100000e-04,1,kg,0.000011,Furane [kg]

In [71]:
m1 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])
m2 = raw6.duplicated(['year', 'pollutant', 'plantid'])
m3 = raw6.duplicated(['year', 'pollutant', 'plantid', 'releases_to'])

In [72]:
raw6.loc[m2]

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
6288,2012,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Water,5.860000e+08,1,kg,5.860000e+07,Chlorides (as total Cl) [kg]
4100,2010,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Land,5.430000e+08,1,kg,5.430000e+07,Chlorides (as total Cl) [kg]
1914,2008,06-90031210632,-,-,Chlorides (as total Cl),Water,5.230000e+08,1,kg,5.230000e+07,Chlorides (as total Cl) [kg]
5205,2011,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Water,5.090000e+08,1,kg,5.090000e+07,Chlorides (as total Cl) [kg]
7300,2013,06-90031210632,K+S KALI GmbH,K+S KALI GmbH,Chlorides (as total Cl),Land,4.610000e+08,1,kg,4.610000e+07,Chlorides (as total Cl) [kg]
...,...,...,...,...,...,...,...,...,...,...,...
11331,2017,12358,Uniper Kraftwerke GmbH,-,Mercury and compounds (as Hg),Water,1.190000e+00,1,kg,1.190000e-01,Mercury and compounds (as Hg) [kg]
12235,2018,12358,Uniper Kraftwerke GmbH,-,Mercury and compounds (as Hg),Water,1.190000e+00,1,kg,1.190000e-01,Mercury and compounds (as Hg) [kg]
3807,2010,06-05-900-0205103,STEAG und RWE Power GKW Bergkamen Geschäftsste...,STEAG und RWE Power GKW Bergkamen Geschäftsste...,Mercury and compounds (as Hg),Water,1.140000e+00,1,kg,1.140000e-01,Mercury and compounds (as Hg) [kg]
9918,2016,06-05-500-0875785,Evonik Degussa GmbH,Evonik Degussa GmbH,Mercury and compounds (as Hg),Water,1.130000e+00,1,kg,1.130000e-01,Mercury and compounds (as Hg) [kg]
614,2007,06-05-900-0884101,-,-,Mercury and compounds (as Hg),Water,1.020000e+00,1,kg,1.020000e-01,Mercury and compounds (as Hg) [kg]

In [73]:
raw7 = raw6.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])
new7 = new71.sort_values(['plantid', 'year', 'potency'], ascending=[True, False, False])

In [74]:
new7.loc[new7.releases_to == "Wasser"]

,year,plantid,company,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
62082,2023,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,216300.0,3,t,216.3000,TOC [t]
62083,2023,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,Ni,Wasser,27.1,3,t,0.0271,Ni [t]
58804,2022,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,249000.0,3,t,249.0000,TOC [t]
58805,2022,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,Ni,Wasser,34.6,3,t,0.0346,Ni [t]
55433,2021,BB23020389,LEIPA Georg Leinfelder Werk Schwedt Süd,LEIPA Georg Leinfelder Werk Schwedt Süd,TOC,Wasser,270000.0,3,t,270.0000,TOC [t]
...,...,...,...,...,...,...,...,...,...,...,...
4027,2007,TH62013494,K+S Standort Unterbreizbach,-,Ni,Wasser,192.0,3,t,0.1920,Ni [t]
4028,2007,TH62013494,K+S Standort Unterbreizbach,-,Ni,Wasser,192.0,3,t,0.1920,Ni [t]
4020,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]
4022,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]
4021,2007,TH62013494,K+S Standort Unterbreizbach,-,Gesamtstickstoff,Wasser,52100.0,1,kg,5210.0000,Gesamtstickstoff [kg]

In [75]:
#raw7.loc[raw7.plantid == "14-70-46630660001"].sort_values("potency", ascending=False)

In [76]:
#adds = pd.read_csv("additionals.csv") # manually add boxberg

In [77]:
#adds

In [78]:
raw8 = raw7.drop(['betreiber', 'eigentuemer'], axis=1)
new8 = new7.drop(['company', 'eigentuemer'], axis=1)

In [79]:
new8['releases_to'] = new8['releases_to'].replace({"Luft": "Air", "Wasser": "Water"})

In [80]:
new8

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
62075,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
62073,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
62074,2023,BB16012651,NMVOC,Air,2580000.0,3,t,2580.000000,NMVOC [t]
58797,2022,BB16012651,NO2,Air,671000.0,6,Tsd. t,0.671000,NO2 [Tsd. t]
58796,2022,BB16012651,PM10,Air,88800.0,6,Tsd. t,0.088800,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
8359,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
4046,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4045,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4048,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]
4047,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [81]:
#raw8.sort_values("amount", ascending=False)

In [82]:
#pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006

In [101]:
new8.drop_duplicates(subset=['plantid', 'pollutant', 'year', 'releases_to'], inplace=True)

In [106]:
new8 = new8.loc[new8.plantid != "NW100-0501870"]

In [107]:
new8.to_csv("pollutants_pg.csv", index=True, header=False)
new8.to_csv("pollutants.csv", index=False)
new8.to_csv("pollutants_nh.csv", index=False, header=False)

In [108]:
new8

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
62075,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
62073,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
62074,2023,BB16012651,NMVOC,Air,2580000.0,3,t,2580.000000,NMVOC [t]
58797,2022,BB16012651,NO2,Air,671000.0,6,Tsd. t,0.671000,NO2 [Tsd. t]
58796,2022,BB16012651,PM10,Air,88800.0,6,Tsd. t,0.088800,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
16817,2010,TH86012942,NO2,Air,104000.0,6,Tsd. t,0.104000,NO2 [Tsd. t]
12506,2009,TH86012942,NO2,Air,136000.0,6,Tsd. t,0.136000,NO2 [Tsd. t]
8358,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
4046,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4048,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [99]:
new8.loc[new8.duplicated(subset=['plantid', 'pollutant', 'year', 'releases_to'])]

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
62077,2023,BB16018798,CO2,Air,285000000.0,9,Mio. t,0.285000,CO2 [Mio. t]
62078,2023,BB16018798,CO2,Air,285000000.0,9,Mio. t,0.285000,CO2 [Mio. t]
58803,2022,BB16018798,CO2,Air,247000000.0,9,Mio. t,0.247000,CO2 [Mio. t]
58802,2022,BB16018798,CO2,Air,247000000.0,9,Mio. t,0.247000,CO2 [Mio. t]
58800,2022,BB16018798,NO2,Air,101000.0,6,Tsd. t,0.101000,NO2 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
16816,2010,TH86012942,NO2,Air,104000.0,6,Tsd. t,0.104000,NO2 [Tsd. t]
12505,2009,TH86012942,NO2,Air,136000.0,6,Tsd. t,0.136000,NO2 [Tsd. t]
8359,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
4045,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
4047,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [86]:
bpm.loc[bpm.plantid == "06-05-500-0342713"]

Empty DataFrame
Columns: [plantid, sseid]
Index: []

In [87]:
#raw5.loc[raw5["pollutant"] == "Teq"].sort_values("amount", ascending=False)

In [88]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '06-05-100-0248923'].sort_values("amount", ascending=False)

In [89]:
#raw4.loc[raw4['year'] == 2017].loc[raw4['plantid'] == '12-40710010000'].sort_values("amount", ascending=False) #12-40710010000 #06-05-300-0923949

In [90]:
#raw4.loc[raw4['year'] == 2009].loc[raw4['plantid'] == '06-05-100-0431554'].sort_values("amount", ascending=False)

In [91]:
#raw4.groupby("pollutant").sum()

In [92]:
#raw3.groupby("pollutant").sum()

In [93]:
#raw4

In [94]:
raw8.groupby('releases_to').min()

,year,plantid,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,
Air,2007,01-10-51011005501,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [95]:
raw7.groupby('releases_to').max()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2022,18042,swb Erzeugung GmbH & Co.KG,verschiedene Eigentümer,Zinc and compounds (as Zn),3.330000e+10,3,t,3.330000e+09,Zinc and compounds (as Zn) [kg]
Land,2022,18042,K+S Minerals and Agriculture GmbH,K+S Minerals and Agriculture GmbH,Zinc and compounds (as Zn),8.260000e+08,6,kg,8.260000e+07,Zinc and compounds (as Zn) [kg]
Water,2022,18042,swb Erzeugung GmbH & Co.KG,und Karton GmbH,Zinc and compounds (as Zn),1.910000e+09,6,t,1.910000e+08,Zinc and compounds (as Zn) [kg]

In [96]:
raw7.groupby('releases_to').min()

,year,plantid,betreiber,eigentuemer,pollutant,amount,potency,unit_2,amount_2,pollutant2
releases_to,,,,,,,,,,
Air,2007,01-10-51011005501,-,-,"1,2-dichloroethane (DCE)",0.000110,1,kg,0.000011,"1,2-dichloroethane (DCE) [kg]"
Land,2008,06-90030210631,-,-,Arsenic and compounds (as As),15.000000,1,Tsd. t,0.058700,Arsenic and compounds (as As) [kg]
Water,2007,01-10-51048040567,-,-,"1,2-dichloroethane (DCE)",0.000131,1,Tsd. t,0.000013,"1,2-dichloroethane (DCE) [kg]"

In [97]:
raw7

,year,plantid,betreiber,eigentuemer,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
14740,2022,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,203000000.0,1,kg,20300000.00,Carbon dioxide (CO2) [kg]
14741,2022,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Nitrogen oxides (NOx/NO2),Air,173000.0,1,kg,17300.00,Nitrogen oxides (NOx/NO2) [kg]
13953,2021,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,214000000.0,1,kg,21400000.00,Carbon dioxide (CO2) [kg]
13954,2021,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Nitrogen oxides (NOx/NO2),Air,154000.0,1,kg,15400.00,Nitrogen oxides (NOx/NO2) [kg]
13189,2020,01-10-51011005501,Sasol Germany GmbH,Sasol Germany GmbH,Carbon dioxide (CO2),Air,182000000.0,1,kg,18200000.00,Carbon dioxide (CO2) [kg]
...,...,...,...,...,...,...,...,...,...,...,...
2181,2008,18042,-,-,Chlorides (as total Cl),Water,96700000.0,1,kg,9670000.00,Chlorides (as total Cl) [kg]
2176,2008,18042,-,-,Nitrogen oxides (NOx/NO2),Air,328000.0,1,kg,32800.00,Nitrogen oxides (NOx/NO2) [kg]
2177,2008,18042,-,-,Chlorine and inorganic compounds (as HCl),Air,17800.0,1,kg,1780.00,Chlorine and inorganic compounds (as HCl) [kg]
2178,2008,18042,-,-,Zinc and compounds (as Zn),Water,272.0,1,kg,27.20,Zinc and compounds (as Zn) [kg]
2179,2008,18042,-,-,Lead and compounds (as Pb),Water,32.5,1,kg,3.25,Lead and compounds (as Pb) [kg]

In [98]:
'''
"text/plain": [
-       "   year            plantid pollutant releases_to       amount  potency  \\\n",
-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",
-       "\n",
-       "   unit_2  amount_2    pollutant2  \n",
-       "0  Mio. t      19.1  CO2 [Mio. t]  "
-      ]
-     },

'''

'\n"text/plain": [\n-       "   year            plantid pollutant releases_to       amount  potency  \\\n",\n-       "0  2018  14-70-46630660001       CO2         Air  19100000000        9   \n",\n-       "\n",\n-       "   unit_2  amount_2    pollutant2  \n",\n-       "0  Mio. t      19.1  CO2 [Mio. t]  "\n-      ]\n-     },\n\n'