In [61]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
import datetime

In [62]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [63]:
hours = (365 * 10 + 3) * 24
base = datetime.datetime(2015, 1, 1)
date_list = [base + datetime.timedelta(hours=x) for x in range(0, hours)]
COMPLETE = pd.DataFrame(data={'produced_at': date_list})
COMPLETE.produced_at = pd.to_datetime(COMPLETE.produced_at)

In [64]:
#COMPLETE

In [65]:
base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2025-01-01', freq='1h')})

In [66]:
base_df.dtypes

produced_at    datetime64[ns]
dtype: object

In [67]:
files = [f for f in os.listdir("combined")]

In [68]:
#files

In [69]:
COMPLETE.dtypes

produced_at    datetime64[ns]
dtype: object

In [70]:
def gen_power3(files):
    zero = pd.DataFrame()
    result = COMPLETE
    for f in files[0:6]:
        final = pd.DataFrame()
        df = pd.read_csv("./combined/" + f, parse_dates=["produced_at"])
        #print(f)
        df2 = pd.DataFrame()
        try:
            df2 = df.merge(COMPLETE, on='produced_at', how='right')
        except ValueError:
            print(f)
        if final.empty:
            final = df2
        else:
            final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [71]:
start = datetime.datetime.now()

In [72]:
#cdf = gen_power3(files)

In [73]:
end = datetime.datetime.now()

In [74]:
duration = end - start
duration_in_s = duration.total_seconds()

In [75]:
duration_in_s

0.309182

In [76]:
fls = os.listdir("combined")
fls.remove('.ipynb_checkpoints')

In [77]:
fls.sort()

In [78]:
fls

['06-02-B10117A007.csv',
 '06-05-100-0431554.csv',
 '06-05-100-0853075.csv',
 'BB23020490.csv',
 'BB45025564.csv',
 'BB45025611.csv',
 'BE166928.csv',
 'BE169709.csv',
 'BE172654.csv',
 'BE172656.csv',
 'BWpf-450-1020129-00000000.csv',
 'BWpf-450-1195689-00000000.csv',
 'BWpf-450-1741292-00000000.csv',
 'BWpf-450-2142201-00000000.csv',
 'BWpf-450-2797933-00000000.csv',
 'BWpf-450-2948214-00000000.csv',
 'BWpf-450.csv',
 'BYS00009.csv',
 'BYS00041.csv',
 'BYS00044.csv',
 'BYS00048.csv',
 'BYS00114.csv',
 'BYS00727.csv',
 'HE30001045.csv',
 'HE50001960.csv',
 'MV30000226.csv',
 'NI01010098080.csv',
 'NI01012110180.csv',
 'NI01241117210.csv',
 'NI06060316030.csv',
 'NI09000237910.csv',
 'NI10257673950.csv',
 'NW100-0081105.csv',
 'NW100-0167182.csv',
 'NW100-0229264.csv',
 'NW100-0248923.csv',
 'NW100-0365906.csv',
 'NW300-0326774.csv',
 'NW300-0370387.csv',
 'NW300-0877384.csv',
 'NW300-0923949.csv',
 'NW300-9002708.csv',
 'NW300-9046030.csv',
 'NW500-0342658.csv',
 'NW500-0915123.csv',
 'NW700-0105516.csv',
 'NW900-0045033.csv',
 'NW900-0079017.csv',
 'NW900-0080266.csv',
 'NW900-0125939.csv',
 'NW900-0205103.csv',
 'NW900-0327252.csv',
 'NW900-0865327.csv',
 'NW900-0884101.csv',
 'NW900-9140178.csv',
 'NW900-9141660.csv',
 'RP5000671.csv',
 'SD661-06.csv',
 'SD661-18.csv',
 'SD661-94.csv',
 'SD666-12.csv',
 'SD666-16.csv',
 'SD666-17.csv',
 'SD666-18.csv',
 'SD669-01.csv',
 'SH50080412.csv',
 'SL0100999-G.csv',
 'SL0101000-G.csv',
 'SL0101003-G.csv',
 'SL0105352-G.csv',
 'SN70015796.csv',
 'SN80011256.csv',
 'SN80011277.csv',
 'ST100125.csv']

In [79]:
#cdf

In [80]:
def combine2cdf():
    base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2025-01-01', freq='1h')})
    #base_df['produced_at'] = base_df['produced_at'].astype(str)
    pdlist = [base_df]
    fls = os.listdir("combined")
    fls.remove('.ipynb_checkpoints')
    for f in fls:
        #final = pd.DataFrame()
        tmp = pd.read_csv("combined/" + f, na_values='-')
        final = tmp.drop(columns=['produced_at'], axis=1)
        print(tmp.shape)
        #if final.empty:
        #    final = result
        #else:
        #    print("DEBUG!")
        #df['produced_at'] = df['produced_at'].astype(str)
        #df = pd.merge(base_df, df, on="produced_at", how='outer')
        pdlist.append(final)
        #result = pd.merge(result, result, how='left', on=['produced_at'])
        
    
    result = pd.concat(pdlist, axis=1)
        
        #df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
    return result

In [81]:
cdf = combine2cdf()

(87672, 6)
(87672, 8)
(87672, 10)
(87672, 3)
(87672, 7)
(87672, 3)
(87672, 4)
(61368, 3)
(87672, 2)
(87672, 3)
(70128, 3)
(87672, 2)
(87672, 4)
(78888, 2)
(87682, 2)
(87672, 3)
(87672, 3)
(87672, 7)
(87672, 4)
(87672, 4)
(87672, 3)
(35064, 2)
(87672, 6)
(87672, 2)
(35064, 2)
(35064, 2)
(87672, 4)
(87672, 4)
(87672, 4)
(87682, 2)
(87672, 3)
(35064, 3)
(61368, 6)
(70128, 5)
(87672, 6)
(87672, 3)
(35064, 4)
(26304, 3)
(87672, 2)
(87672, 4)
(87672, 3)
(87672, 2)
(87672, 3)
(78888, 3)
(87672, 4)
(87672, 2)
(43824, 2)
(87672, 2)
(87672, 4)
(87672, 2)
(26311, 14)
(43824, 2)
(87672, 4)
(87672, 10)
(87672, 7)
(26304, 3)
(78888, 2)
(87672, 3)
(87672, 2)
(52608, 2)
(87672, 2)
(78888, 2)
(87672, 2)
(87672, 5)
(87672, 3)
(87672, 2)
(87672, 2)
(61368, 2)
(87672, 3)
(87672, 3)
(87672, 9)
(87672, 5)
(87672, 6)
(87672, 2)

In [82]:
#cdf = combine2cdf()

In [83]:
cdf = cdf.loc[:, ~cdf.columns.str.contains('^Unnamed')]
cdfa = cdf.dropna(subset=['produced_at'])
cdf2 = cdfa.fillna(0)

In [84]:
cdf2

,produced_at,BNA0221c,SEE957083466325,SEE989503748513,SEE972458947407,SEE975361659900,SEE907150117643,SEE979012663285,SEE978971638464,SEE931736847297,...,SEE985842749525,SEE968582186379,SEE908125004449,SEE907389779292,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972,SEE961029163353
0,2015-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87668,2024-12-31 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87669,2024-12-31 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87670,2024-12-31 22:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87671,2024-12-31 23:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87672,2025-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
cdf2

,produced_at,BNA0221c,SEE957083466325,SEE989503748513,SEE972458947407,SEE975361659900,SEE907150117643,SEE979012663285,SEE978971638464,SEE931736847297,...,SEE985842749525,SEE968582186379,SEE908125004449,SEE907389779292,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972,SEE961029163353
0,2015-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87668,2024-12-31 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87669,2024-12-31 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87670,2024-12-31 22:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87671,2024-12-31 23:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87672,2025-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
#cdf['produced_at'] = cdf['produced_at'].astype(pd.datetime64)
cdf2['produced_at'] = pd.to_datetime(cdf2['produced_at'])

In [87]:
gm = cdf2.resample('1ME', on='produced_at').sum()

In [88]:
gm

,BNA0221c,SEE957083466325,SEE989503748513,SEE972458947407,SEE975361659900,SEE907150117643,SEE979012663285,SEE978971638464,SEE931736847297,SEE976414005279,...,SEE985842749525,SEE968582186379,SEE908125004449,SEE907389779292,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972,SEE961029163353
produced_at,,,,,,,,,,,,,,,,,,,,,
2015-01-31,15020.0,12228.0,0.0,0.0,0.0,100448.0,108992.0,100541.0,172535.0,196917.0,...,154013.0,352119.0,300624.0,478261.0,0.0,0.0,0.0,86441.0,84584.0,203056.0
2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,267521.0,166636.0,291465.0,538011.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,288612.0,338093.0,309412.0,540158.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,352278.0,206796.0,293448.0,569898.0,0.0,0.0,0.0,0.0,0.0,0.0
2015-05-31,0.0,0.0,0.0,0.0,0.0,104627.0,58501.0,97989.0,199305.0,229729.0,...,251912.0,423714.0,312625.0,588667.0,0.0,0.0,0.0,76325.0,75177.0,202021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-30,0.0,1690.0,0.0,0.0,96401.0,0.0,0.0,0.0,0.0,0.0,...,83754.0,298060.0,281886.0,458874.0,0.0,0.0,0.0,0.0,0.0,286109.0
2024-10-31,0.0,1897.0,0.0,0.0,177005.0,0.0,0.0,0.0,0.0,0.0,...,289581.0,358146.0,198493.0,497878.0,0.0,0.0,0.0,0.0,0.0,280942.0
2024-11-30,0.0,7186.0,0.0,0.0,300093.0,0.0,0.0,0.0,0.0,0.0,...,345638.0,291300.0,246862.0,523371.0,0.0,0.0,0.0,0.0,0.0,412120.0
2024-12-31,0.0,9622.0,0.0,0.0,238409.0,0.0,0.0,0.0,0.0,0.0,...,306787.0,132401.0,279823.0,234392.0,0.0,0.0,0.0,0.0,0.0,239937.0
2025-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
gm2 = gm.reset_index()
#gm2['year'] = gm2['produced_at2']
#gm2['month'] = gm2['produced_at3']

In [90]:
def gen_power3(files):
    result = COMPLETE
    for plant, files in FILES_DICT.items():
        final = pd.DataFrame()
        for idx, f in enumerate(files):
            f = "fix/" + f
            df = pd.read_csv(f, parse_dates=["produced_at"])
            df2 = df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
            if final.empty:
                final = df2
            else:
                final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [91]:
gm2

,produced_at,BNA0221c,SEE957083466325,SEE989503748513,SEE972458947407,SEE975361659900,SEE907150117643,SEE979012663285,SEE978971638464,SEE931736847297,...,SEE985842749525,SEE968582186379,SEE908125004449,SEE907389779292,BNA0335,BNA0334,BNA0333,SEE952352206145,SEE933236950972,SEE961029163353
0,2015-01-31,15020.0,12228.0,0.0,0.0,0.0,100448.0,108992.0,100541.0,172535.0,...,154013.0,352119.0,300624.0,478261.0,0.0,0.0,0.0,86441.0,84584.0,203056.0
1,2015-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,267521.0,166636.0,291465.0,538011.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,288612.0,338093.0,309412.0,540158.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,352278.0,206796.0,293448.0,569898.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-05-31,0.0,0.0,0.0,0.0,0.0,104627.0,58501.0,97989.0,199305.0,...,251912.0,423714.0,312625.0,588667.0,0.0,0.0,0.0,76325.0,75177.0,202021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,2024-09-30,0.0,1690.0,0.0,0.0,96401.0,0.0,0.0,0.0,0.0,...,83754.0,298060.0,281886.0,458874.0,0.0,0.0,0.0,0.0,0.0,286109.0
117,2024-10-31,0.0,1897.0,0.0,0.0,177005.0,0.0,0.0,0.0,0.0,...,289581.0,358146.0,198493.0,497878.0,0.0,0.0,0.0,0.0,0.0,280942.0
118,2024-11-30,0.0,7186.0,0.0,0.0,300093.0,0.0,0.0,0.0,0.0,...,345638.0,291300.0,246862.0,523371.0,0.0,0.0,0.0,0.0,0.0,412120.0
119,2024-12-31,0.0,9622.0,0.0,0.0,238409.0,0.0,0.0,0.0,0.0,...,306787.0,132401.0,279823.0,234392.0,0.0,0.0,0.0,0.0,0.0,239937.0
120,2025-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0