In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
import datetime

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
hours = (365 * 9 + 2) * 24
base = datetime.datetime(2015, 1, 1)
date_list = [base + datetime.timedelta(hours=x) for x in range(0, hours)]
COMPLETE = pd.DataFrame(data={'produced_at': date_list})
COMPLETE.produced_at = pd.to_datetime(COMPLETE.produced_at)

In [4]:
COMPLETE

              produced_at
0     2015-01-01 00:00:00
1     2015-01-01 01:00:00
2     2015-01-01 02:00:00
3     2015-01-01 03:00:00
4     2015-01-01 04:00:00
...                   ...
78883 2023-12-31 19:00:00
78884 2023-12-31 20:00:00
78885 2023-12-31 21:00:00
78886 2023-12-31 22:00:00
78887 2023-12-31 23:00:00

[78888 rows x 1 columns]

In [5]:
base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2024-01-01', freq='1H')})

In [6]:
base_df.dtypes

produced_at    datetime64[ns]
dtype: object

In [7]:
files = [f for f in os.listdir("combined")]

In [8]:
#files

In [9]:
COMPLETE.dtypes

produced_at    datetime64[ns]
dtype: object

In [10]:
def gen_power3(files):
    zero = pd.DataFrame()
    result = COMPLETE
    for f in files[0:6]:
        final = pd.DataFrame()
        df = pd.read_csv("./combined/" + f, parse_dates=["produced_at"])
        #print(f)
        df2 = pd.DataFrame()
        try:
            df2 = df.merge(COMPLETE, on='produced_at', how='right')
        except ValueError:
            print(f)
        if final.empty:
            final = df2
        else:
            final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [11]:
start = datetime.datetime.now()

In [12]:
#cdf = gen_power3(files)

In [13]:
end = datetime.datetime.now()

In [14]:
duration = end - start
duration_in_s = duration.total_seconds()

In [15]:
duration_in_s

0.018624

In [16]:
#cdf

In [17]:
def combine2cdf():
    base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2024-01-01', freq='1H')})
    #base_df['produced_at'] = base_df['produced_at'].astype(str)
    pdlist = [base_df]
    for f in os.listdir("combined"):
        #final = pd.DataFrame()
        tmp = pd.read_csv("combined/" + f, na_values='-')
        final = tmp.drop(columns=['produced_at'], axis=1)
        print(tmp.shape)
        #if final.empty:
        #    final = result
        #else:
        #    print("DEBUG!")
        #df['produced_at'] = df['produced_at'].astype(str)
        #df = pd.merge(base_df, df, on="produced_at", how='outer')
        pdlist.append(final)
        #result = pd.merge(result, result, how='left', on=['produced_at'])
        
    
    result = pd.concat(pdlist, axis=1)
        
        #df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
    return result

In [18]:
cdf = combine2cdf()

(43824, 2)
(78888, 2)
(52608, 2)
(78888, 3)
(78888, 3)
(35064, 2)
(78888, 6)
(78888, 5)
(78888, 3)
(78888, 3)
(61368, 4)
(78888, 4)
(26310, 14)
(78888, 6)
(78888, 3)
(78888, 8)
(78888, 4)
(26304, 3)
(26304, 3)
(78888, 10)
(78888, 3)
(78888, 9)
(78888, 4)
(78888, 2)
(78888, 2)
(78888, 6)
(61344, 5)
(78888, 2)
(35064, 4)
(61368, 6)
(35064, 2)
(78888, 2)
(78888, 2)
(78888, 4)
(78888, 10)
(35064, 3)
(78888, 3)
(78888, 2)
(78888, 4)
(78888, 7)
(78888, 7)
(78888, 4)
(78888, 4)
(78888, 4)
(78888, 4)
(78888, 4)
(78888, 3)
(78888, 3)
(78888, 2)
(78888, 3)
(78888, 2)
(78888, 3)
(78888, 2)
(78888, 3)
(78888, 3)
(78897, 2)
(78888, 6)
(78888, 7)
(78888, 3)
(78888, 3)
(78888, 2)
(78888, 5)
(78888, 3)
(61368, 2)
(78888, 2)
(35068, 2)
(78888, 2)
(78897, 2)
(43824, 2)
(78888, 2)
(78888, 2)
(78888, 2)
(61368, 3)

In [39]:
#cdf = combine2cdf()

In [40]:
cdf = cdf.loc[:, ~cdf.columns.str.contains('^Unnamed')]
cdfa = cdf.dropna(subset=['produced_at'])
cdf2 = cdfa.fillna(0)

In [41]:
cdf2

,produced_at,BNA0526,SEE904194792843,BNA0439,SEE959000487536,SEE917432813484,SEE987633796220,SEE932928232242,SEE970425279599,SEE929022761297,...,SEE974201537415,SEE940475173918,SEE913556136355,SEE967194778880,BNA0802,SEE943690268513,SEE944567587799,SEE985577062814,SEE950675787617,SEE983645175053
0,2015-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78884,2023-12-31 20:00:00,0.0,0.0,0.0,0.0,60.0,0.0,102.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78885,2023-12-31 21:00:00,0.0,0.0,0.0,0.0,60.0,0.0,74.0,0.0,0.0,...,0.0,0.0,23.0,70,0.0,0.0,0.0,0.0,0.0,0.0
78886,2023-12-31 22:00:00,0.0,0.0,0.0,0.0,61.0,0.0,70.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78887,2023-12-31 23:00:00,0.0,0.0,0.0,0.0,59.0,0.0,65.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78888,2024-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,69,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
cdf2

,produced_at,BNA0526,SEE904194792843,BNA0439,SEE959000487536,SEE917432813484,SEE987633796220,SEE932928232242,SEE970425279599,SEE929022761297,...,SEE974201537415,SEE940475173918,SEE913556136355,SEE967194778880,BNA0802,SEE943690268513,SEE944567587799,SEE985577062814,SEE950675787617,SEE983645175053
0,2015-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78884,2023-12-31 20:00:00,0.0,0.0,0.0,0.0,60.0,0.0,102.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78885,2023-12-31 21:00:00,0.0,0.0,0.0,0.0,60.0,0.0,74.0,0.0,0.0,...,0.0,0.0,23.0,70,0.0,0.0,0.0,0.0,0.0,0.0
78886,2023-12-31 22:00:00,0.0,0.0,0.0,0.0,61.0,0.0,70.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78887,2023-12-31 23:00:00,0.0,0.0,0.0,0.0,59.0,0.0,65.0,0.0,0.0,...,0.0,0.0,23.0,69,0.0,0.0,0.0,0.0,0.0,0.0
78888,2024-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,69,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
#cdf['produced_at'] = cdf['produced_at'].astype(pd.datetime64)
cdf2['produced_at'] = pd.to_datetime(cdf2['produced_at'])

In [48]:
gm = cdf2.resample('1M', on='produced_at').sum()

In [51]:
gm

,BNA0526,SEE904194792843,BNA0439,SEE959000487536,SEE917432813484,SEE987633796220,SEE932928232242,SEE970425279599,SEE929022761297,SEE921098709050,...,SEE974201537415,SEE940475173918,SEE913556136355,SEE967194778880,BNA0802,SEE943690268513,SEE944567587799,SEE985577062814,SEE950675787617,SEE983645175053
produced_at,,,,,,,,,,,,,,,,,,,,,
2015-01-31,132621.0,278158.0,182138.0,0.0,0.0,78439.0,63897.0,0.0,47093.0,0.0,...,240.0,0.0,0.0,122485,889930.0,883681.0,458074.0,836593.0,73996.0,72103.0
2015-02-28,131921.0,346784.0,210148.0,0.0,0.0,73054.0,65748.0,0.0,0.0,0.0,...,225.0,0.0,0.0,110421,920764.0,923687.0,0.0,879641.0,71212.0,86218.0
2015-03-31,134722.0,294466.0,224275.0,0.0,0.0,87045.0,70111.0,0.0,0.0,0.0,...,80.0,36011.0,0.0,120447,1013132.0,1003662.0,0.0,973302.0,69547.0,24021.0
2015-04-30,131559.0,236791.0,225999.0,41552.0,42472.0,77176.0,63893.0,0.0,0.0,0.0,...,360.0,70286.0,0.0,107108,982784.0,972242.0,0.0,935811.0,6169.0,8583.0
2015-05-31,112542.0,147674.0,120824.0,75254.0,77180.0,68508.0,64659.0,0.0,212.0,0.0,...,0.0,44905.0,0.0,69942,868371.0,999559.0,12343.0,830791.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-30,0.0,22695.0,0.0,56975.0,51691.0,59112.0,22210.0,0.0,317805.0,0.0,...,1221.0,0.0,36024.0,50158,0.0,0.0,0.0,0.0,0.0,0.0
2023-10-31,0.0,90053.0,0.0,48438.0,54033.0,43471.0,50490.0,0.0,174644.0,0.0,...,2120.0,0.0,17090.0,74850,0.0,0.0,0.0,0.0,0.0,0.0
2023-11-30,0.0,69294.0,0.0,6636.0,8983.0,38790.0,61324.0,0.0,185384.0,0.0,...,1740.0,0.0,24022.0,126746,0.0,0.0,0.0,0.0,0.0,0.0
2023-12-31,0.0,160846.0,0.0,35303.0,39755.0,47116.0,63829.0,0.0,238516.0,0.0,...,610.0,0.0,21745.0,130051,0.0,0.0,0.0,0.0,0.0,0.0
2024-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,69,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
gm2 = gm.reset_index()
#gm2['year'] = gm2['produced_at2']
#gm2['month'] = gm2['produced_at3']

In [55]:
def gen_power3(files):
    result = COMPLETE
    for plant, files in FILES_DICT.items():
        final = pd.DataFrame()
        for idx, f in enumerate(files):
            f = "fix/" + f
            df = pd.read_csv(f, parse_dates=["produced_at"])
            df2 = df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
            if final.empty:
                final = df2
            else:
                final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [119]:
gm2

,produced_at,BNA0526,SEE904194792843,BNA0439,SEE959000487536,SEE917432813484,SEE987633796220,SEE932928232242,SEE970425279599,SEE929022761297,...,SEE974201537415,SEE940475173918,SEE913556136355,SEE967194778880,BNA0802,SEE943690268513,SEE944567587799,SEE985577062814,SEE950675787617,SEE983645175053
0,2015-01-31,132621.0,278158.0,182138.0,0.0,0.0,78439.0,63897.0,0.0,47093.0,...,240.0,0.0,0.0,122485.0,889930.0,883681.0,458074.0,836593.0,73996.0,72103.0
1,2015-02-28,131921.0,346784.0,210148.0,0.0,0.0,73054.0,65748.0,0.0,0.0,...,225.0,0.0,0.0,110421.0,920764.0,923687.0,0.0,879641.0,71212.0,86218.0
2,2015-03-31,134722.0,294466.0,224275.0,0.0,0.0,87045.0,70111.0,0.0,0.0,...,80.0,36011.0,0.0,120447.0,1013132.0,1003662.0,0.0,973302.0,69547.0,24021.0
3,2015-04-30,131559.0,236791.0,225999.0,41552.0,42472.0,77176.0,63893.0,0.0,0.0,...,360.0,70286.0,0.0,107108.0,982784.0,972242.0,0.0,935811.0,6169.0,8583.0
4,2015-05-31,112542.0,147674.0,120824.0,75254.0,77180.0,68508.0,64659.0,0.0,212.0,...,0.0,44905.0,0.0,69942.0,868371.0,999559.0,12343.0,830791.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2023-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105,2023-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
106,2023-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107,2023-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
108,2024-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0