In [1]:
import pandas as pd
#from pandas.io.parsers import ParserError
import numpy as np
from helper import get_mapper
import json
import os
import re
import datetime

In [2]:
from os import listdir, stat
from os.path import isfile, join
BASE_DIR = "."
MIN_SIZE = 512

In [3]:
hours = (365 * 10 + 3) * 24
base = datetime.datetime(2015, 1, 1)
date_list = [base + datetime.timedelta(hours=x) for x in range(0, hours)]
COMPLETE = pd.DataFrame(data={'produced_at': date_list})
COMPLETE.produced_at = pd.to_datetime(COMPLETE.produced_at)

In [4]:
COMPLETE

              produced_at
0     2015-01-01 00:00:00
1     2015-01-01 01:00:00
2     2015-01-01 02:00:00
3     2015-01-01 03:00:00
4     2015-01-01 04:00:00
...                   ...
87667 2024-12-31 19:00:00
87668 2024-12-31 20:00:00
87669 2024-12-31 21:00:00
87670 2024-12-31 22:00:00
87671 2024-12-31 23:00:00

[87672 rows x 1 columns]

In [5]:
base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2025-01-01', freq='1h')})

In [6]:
base_df.dtypes

produced_at    datetime64[ns]
dtype: object

In [7]:
files = [f for f in os.listdir("combined")]

In [8]:
#files

In [9]:
COMPLETE.dtypes

produced_at    datetime64[ns]
dtype: object

In [10]:
def gen_power3(files):
    zero = pd.DataFrame()
    result = COMPLETE
    for f in files[0:6]:
        final = pd.DataFrame()
        df = pd.read_csv("./combined/" + f, parse_dates=["produced_at"])
        #print(f)
        df2 = pd.DataFrame()
        try:
            df2 = df.merge(COMPLETE, on='produced_at', how='right')
        except ValueError:
            print(f)
        if final.empty:
            final = df2
        else:
            final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [11]:
start = datetime.datetime.now()

In [12]:
#cdf = gen_power3(files)

In [13]:
end = datetime.datetime.now()

In [14]:
duration = end - start
duration_in_s = duration.total_seconds()

In [15]:
duration_in_s

0.32264

In [16]:
#cdf

In [17]:
def combine2cdf():
    base_df = pd.DataFrame({'produced_at': pd.date_range(start='2015-01-01', end='2025-01-01', freq='1h')})
    #base_df['produced_at'] = base_df['produced_at'].astype(str)
    pdlist = [base_df]
    for f in os.listdir("combined"):
        #final = pd.DataFrame()
        tmp = pd.read_csv("combined/" + f, na_values='-')
        final = tmp.drop(columns=['produced_at'], axis=1)
        print(tmp.shape)
        #if final.empty:
        #    final = result
        #else:
        #    print("DEBUG!")
        #df['produced_at'] = df['produced_at'].astype(str)
        #df = pd.merge(base_df, df, on="produced_at", how='outer')
        pdlist.append(final)
        #result = pd.merge(result, result, how='left', on=['produced_at'])
        
    
    result = pd.concat(pdlist, axis=1)
        
        #df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
    return result

In [18]:
cdf = combine2cdf()

(87672, 3)
(87672, 3)
(87672, 2)
(87672, 2)
(87671, 4)
(87672, 3)
(43824, 2)
(35064, 3)
(87672, 5)
(87672, 3)
(87672, 4)
(87672, 2)
(78888, 2)
(87672, 7)
(61368, 2)
(87672, 8)
(87672, 10)
(87672, 4)
(87682, 2)
(78912, 3)
(78912, 3)
(35064, 2)
(87672, 3)
(78888, 2)
(43824, 2)
(43805, 2)
(87672, 2)
(26311, 14)
(87672, 9)
(87672, 4)

IsADirectoryError: [Errno 21] Is a directory: 'combined/.ipynb_checkpoints'

In [ ]:
#cdf = combine2cdf()

In [ ]:
cdf = cdf.loc[:, ~cdf.columns.str.contains('^Unnamed')]
cdfa = cdf.dropna(subset=['produced_at'])
cdf2 = cdfa.fillna(0)

In [ ]:
cdf2

In [ ]:
cdf2

In [ ]:
#cdf['produced_at'] = cdf['produced_at'].astype(pd.datetime64)
cdf2['produced_at'] = pd.to_datetime(cdf2['produced_at'])

In [ ]:
gm = cdf2.resample('1ME', on='produced_at').sum()

In [19]:
gm

NameError: name 'gm' is not defined

In [20]:
gm2 = gm.reset_index()
#gm2['year'] = gm2['produced_at2']
#gm2['month'] = gm2['produced_at3']

NameError: name 'gm' is not defined

In [21]:
def gen_power3(files):
    result = COMPLETE
    for plant, files in FILES_DICT.items():
        final = pd.DataFrame()
        for idx, f in enumerate(files):
            f = "fix/" + f
            df = pd.read_csv(f, parse_dates=["produced_at"])
            df2 = df.merge(DATEDF_LIST[idx], on='produced_at', how='right')
            if final.empty:
                final = df2
            else:
                final = final.append(df2, sort=False)
        result = pd.merge(result, final, how='left', on=['produced_at'])
    return result.sort_values(by=['produced_at'])

In [89]:
gm2

,produced_at,SEE987970110314,SEE900628853036,SEE919393178787,SEE987838157994,SEE937052769589,SEE943427876363,SEE949509046600,SEE918648599230,SEE958847865460,...,SEE988182827533,SEE929161243203,SEE975556152230,SEE971282697380,SEE963975943188,SEE904161631090,SEE965782597448,SEE944503176377,SEE922477386435,SEE911764038249
0,2015-01-31,16557.0,17765.0,0.0,0.0,0.0,201631.0,0.0,0.0,195508.0,...,0.0,122919.0,0.0,0.0,0.0,0.0,66408.0,150420.0,36495.0,16028.0
1,2015-02-28,0.0,0.0,0.0,0.0,257545.0,298096.0,0.0,0.0,231268.0,...,0.0,246846.0,0.0,0.0,0.0,0.0,0.0,190413.0,43751.0,18569.0
2,2015-03-31,0.0,0.0,0.0,0.0,232749.0,279299.0,0.0,0.0,229859.0,...,245.0,177934.0,0.0,0.0,0.0,0.0,0.0,144682.0,43611.0,29428.0
3,2015-04-30,0.0,0.0,0.0,0.0,315718.0,290197.0,0.0,0.0,166837.0,...,0.0,187975.0,0.0,0.0,0.0,0.0,0.0,69839.0,2228.0,0.0
4,2015-05-31,0.0,8367.0,10233.0,23441.0,207605.0,181962.0,0.0,0.0,66588.0,...,0.0,148969.0,0.0,0.0,0.0,0.0,0.0,10535.0,135.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,2024-09-30,25684.0,79966.0,0.0,0.0,0.0,2191.0,0.0,0.0,118469.0,...,0.0,0.0,0.0,0.0,0.0,0.0,36885.0,0.0,0.0,1830.0
117,2024-10-31,73939.0,99139.0,0.0,0.0,0.0,182311.0,0.0,0.0,166841.0,...,0.0,0.0,0.0,0.0,0.0,0.0,44777.0,0.0,2962.0,1355.0
118,2024-11-30,178935.0,181673.0,0.0,0.0,0.0,234848.0,0.0,0.0,175325.0,...,0.0,0.0,0.0,0.0,0.0,0.0,144691.0,0.0,35939.0,11654.0
119,2024-12-31,115511.0,94011.0,0.0,0.0,0.0,81599.0,0.0,0.0,92015.0,...,0.0,0.0,0.0,0.0,0.0,0.0,127229.0,0.0,27298.0,23103.0
120,2025-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0