In [68]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [69]:
PRTR_YEAR = 2025
POWER_YEAR = 2025

In [70]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production-v2/yearly-direct.csv")

In [71]:
power2 = pd.read_csv("../production-v2/yearly-direct.csv")

In [72]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [73]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [74]:
#power.to_csv("powertest.csv")
#power2.to_csv("powertest2.csv")

In [75]:
#power2.sort_values(by=["year", "plantid"], ascending=False)

In [76]:
power.sort_values(by=["year", "plantid"], ascending=False)

     year                    plantid  yearpower
243  2025                   ST100125    3014208
250  2025                 SN80011277    7394435
238  2025                 SN70015796   11570712
240  2025                  RP5000671    2014484
249  2025              NW900-9141660    2785686
..    ...                        ...        ...
3    2015  BWpf-450-1020129-00000000    3204832
6    2015                   BE172654    1584856
21   2015                   BE166928    2731236
15   2015                 BB45025564   19543224
8    2015                 BB23020490    1627332

[252 rows x 3 columns]

In [77]:
powers = power.pivot(index='plantid', columns='year')

In [78]:
powers

                            yearpower                                      \
year                             2015        2016        2017        2018
plantid
BB23020490                  1627332.0   1504256.0   1549496.0   1436196.0
BB45025564                 19543224.0  19875248.0  19548452.0  18843136.0
BE166928                    2731236.0   2336720.0   2238404.0   1992748.0
BE172654                    1584856.0   1753812.0   1987748.0   1914420.0
BWpf-450-1020129-00000000   3204832.0   2383176.0   2380380.0   2853200.0
BWpf-450-1195689-00000000    219108.0    257684.0    251276.0    271868.0
BWpf-450-1741292-00000000   1690564.0   1929436.0   1188996.0   1114768.0
BWpf-450-2142201-00000000     24352.0     17500.0     30180.0     22864.0
BWpf-450-2797933-00000000   2794752.0   1515432.0   3288248.0   3079384.0
BYS00044                     449220.0   1493424.0   1906472.0   1703184.0
BYS00048                     558740.0    203920.0    132924.0     23752.0
MV30000226                  2777260.0   3213676.0   2837044.0   2172112.0
NI06060316030               1633784.0   1541236.0   1439252.0   1492884.0
NW100-0167182                 91444.0   2695108.0   2869088.0   3054844.0
NW300-0326774              13119760.0  14990560.0  19417880.0  18217840.0
NW300-0923949                 42292.0    178632.0    201888.0    114900.0
NW300-9002708               1374592.0   1282264.0    941228.0    616672.0
NW500-0915123                     NaN         NaN         0.0         0.0
NW900-0327252                     NaN         NaN         NaN         NaN
NW900-9141660               1105296.0   3954880.0   3276384.0   4009084.0
RP5000671                   1986588.0   2625948.0   2784520.0   2893800.0
SN70015796                 17826832.0  16894712.0  17386284.0  17240584.0
SN80011277                 10796120.0  11434684.0  11882612.0  12033784.0
ST100125                    4149940.0   4249672.0   4293476.0   4881816.0

                                                                           \
year                             2019        2020        2021        2022
plantid
BB23020490                  1329840.0   1365616.0   1246744.0   1333068.0
BB45025564                 15048744.0  11641976.0  12904452.0  12459672.0
BE166928                    1356084.0   1389700.0   1295848.0   1348240.0
BE172654                    1913568.0   1741200.0   1679640.0   1193904.0
BWpf-450-1020129-00000000   1259868.0    498248.0   2168912.0   1785460.0
BWpf-450-1195689-00000000    242956.0    236540.0    228812.0    206120.0
BWpf-450-1741292-00000000    807496.0    560536.0    978964.0   1139968.0
BWpf-450-2142201-00000000     15528.0     15048.0     32004.0     30556.0
BWpf-450-2797933-00000000   2541252.0   1577648.0   3317404.0   3815972.0
BYS00044                    1771396.0   1975700.0   1104972.0   1035520.0
BYS00048                      37352.0   1729480.0   4176096.0   2491108.0
MV30000226                  2068008.0   1118284.0   2477180.0   1993512.0
NI06060316030               1035072.0    871896.0   1158188.0   1527728.0
NW100-0167182               3165184.0   3841716.0   2916120.0   2374336.0
NW300-0326774              12799528.0   8126980.0  12600084.0  15112584.0
NW300-0923949                   576.0     21756.0     42288.0         0.0
NW300-9002708                840396.0    722044.0    519668.0    385884.0
NW500-0915123                  1480.0   2268820.0   4685680.0   4548976.0
NW900-0327252                     NaN         NaN         NaN         NaN
NW900-9141660               3334960.0   1633040.0   3824400.0   3822648.0
RP5000671                   2734852.0   2788124.0   2930100.0   2365348.0
SN70015796                 16920860.0  13789128.0  14118688.0  17330468.0
SN80011277                  9265552.0   8355832.0  11260748.0  12106732.0
ST100125                    2887728.0   2068748.0   3247748.0   3166692.0


year                             2023        2024        2025
plantid
BB23020490                  1163264.0   1376356.0   1010196.0
BB45025564                 11579420.0   9559692.0   7695952.0
BE166928                    1269720.0   1171444.0    902848.0
BE172654                    1365724.0   1297500.0   1151580.0
BWpf-450-1020129-00000000    306092.0    593836.0   1219912.0
BWpf-450-1195689-00000000    186372.0    205404.0    135760.0
BWpf-450-1741292-00000000    540072.0    487424.0    889536.0
BWpf-450-2142201-00000000     13692.0     20988.0     13772.0
BWpf-450-2797933-00000000   2548124.0   2077640.0   3411620.0
BYS00044                     799936.0   1077596.0   1150004.0
BYS00048                    2846692.0   3458496.0   3832952.0
MV30000226                  1141292.0    641708.0   1817952.0
NI06060316030               1117000.0    934480.0    901136.0
NW100-0167182               2384732.0   2640068.0   2625048.0
NW300-0326774              11693868.0  10407684.0   9912028.0
NW300-0923949                     0.0         0.0     32056.0
NW300-9002708                902660.0   1401460.0    510124.0
NW500-0915123               3397300.0   1999908.0   3071756.0
NW900-0327252                     NaN         NaN   1311904.0
NW900-9141660               2579020.0   2557468.0   2785686.0
RP5000671                   2143988.0   1868040.0   2014484.0
SN70015796                 11807604.0  12664780.0  11570712.0
SN80011277                  7719272.0   5887252.0   7394435.0
ST100125                    3047500.0   3309088.0   3014208.0

In [79]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [80]:
df2 = df.reset_index()

In [81]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,BB23020490,1627332.0,1504256.0,1549496.0,1436196.0,1329840.0,1365616.0,1246744.0,1333068.0,1163264.0,1376356.0,1010196.0
1,BB45025564,19543224.0,19875248.0,19548452.0,18843136.0,15048744.0,11641976.0,12904452.0,12459672.0,11579420.0,9559692.0,7695952.0
2,BE166928,2731236.0,2336720.0,2238404.0,1992748.0,1356084.0,1389700.0,1295848.0,1348240.0,1269720.0,1171444.0,902848.0
3,BE172654,1584856.0,1753812.0,1987748.0,1914420.0,1913568.0,1741200.0,1679640.0,1193904.0,1365724.0,1297500.0,1151580.0
4,BWpf-450-1020129-00000000,3204832.0,2383176.0,2380380.0,2853200.0,1259868.0,498248.0,2168912.0,1785460.0,306092.0,593836.0,1219912.0
5,BWpf-450-1195689-00000000,219108.0,257684.0,251276.0,271868.0,242956.0,236540.0,228812.0,206120.0,186372.0,205404.0,135760.0
6,BWpf-450-1741292-00000000,1690564.0,1929436.0,1188996.0,1114768.0,807496.0,560536.0,978964.0,1139968.0,540072.0,487424.0,889536.0
7,BWpf-450-2142201-00000000,24352.0,17500.0,30180.0,22864.0,15528.0,15048.0,32004.0,30556.0,13692.0,20988.0,13772.0
8,BWpf-450-2797933-00000000,2794752.0,1515432.0,3288248.0,3079384.0,2541252.0,1577648.0,3317404.0,3815972.0,2548124.0,2077640.0,3411620.0
9,BYS00044,449220.0,1493424.0,1906472.0,1703184.0,1771396.0,1975700.0,1104972.0,1035520.0,799936.0,1077596.0,1150004.0
10,BYS00048,558740.0,203920.0,132924.0,23752.0,37352.0,1729480.0,4176096.0,2491108.0,2846692.0,3458496.0,3832952.0
11,MV30000226,2777260.0,3213676.0,2837044.0,2172112.0,2068008.0,1118284.0,2477180.0,1993512.0,1141292.0,641708.0,1817952.0
12,NI06060316030,1633784.0,1541236.0,1439252.0,1492884.0,1035072.0,871896.0,1158188.0,1527728.0,1117000.0,934480.0,901136.0
13,NW100-0167182,91444.0,2695108.0,2869088.0,3054844.0,3165184.0,3841716.0,2916120.0,2374336.0,2384732.0,2640068.0,2625048.0
14,NW300-0326774,13119760.0,14990560.0,19417880.0,18217840.0,12799528.0,8126980.0,12600084.0,15112584.0,11693868.0,10407684.0,9912028.0
15,NW300-0923949,42292.0,178632.0,201888.0,114900.0,576.0,21756.0,42288.0,0.0,0.0,0.0,32056.0
16,NW300-9002708,1374592.0,1282264.0,941228.0,616672.0,840396.0,722044.0,519668.0,385884.0,902660.0,1401460.0,510124.0
17,NW500-0915123,NaN,NaN,0.0,0.0,1480.0,2268820.0,4685680.0,4548976.0,3397300.0,1999908.0,3071756.0
18,NW900-0327252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1311904.0
19,NW900-9141660,1105296.0,3954880.0,3276384.0,4009084.0,3334960.0,1633040.0,3824400.0,3822648.0,2579020.0,2557468.0,2785686.0
20,RP5000671,1986588.0,2625948.0,2784520.0,2893800.0,2734852.0,2788124.0,2930100.0,2365348.0,2143988.0,1868040.0,2014484.0
21,SN70015796,17826832.0,16894712.0,17386284.0,17240584.0,16920860.0,13789128.0,14118688.0,17330468.0,11807604.0,12664780.0,11570712.0
22,SN80011277,10796120.0,11434684.0,11882612.0,12033784.0,9265552.0,8355832.0,11260748.0,12106732.0,7719272.0,5887252.0,7394435.0
23,ST100125,4149940.0,4249672.0,4293476.0,4881816.0,2887728.0,2068748.0,3247748.0,3166692.0,3047500.0,3309088.0,3014208.0

In [82]:
#df

In [83]:
#powers.unstack('plantid')

In [84]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [85]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,SN60018636,BHKW-G66-KWK-klein,Sachsen,Erdgas,Ja,43067,43067,3.736,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SD661-97,BHKW-G66-KWK-groß,Sachsen,Erdgas,Ja,41683,41683,12.747,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NW100-0046639,0065 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,Ja,2024,2024,7.257,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SD662-99,bnBm Gaskraftwerk Leipheim,Bayern,Erdgas,Nein,2023,2023,310.000,bnBm,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SD662-98,bnBm GasKW BIB GT1,Hessen,Erdgas,Nein,2023,2023,378.400,bnBm,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
230,SN70015796,Boxberg Block N,Sachsen,Braunkohle,Ja,2012,1979,2470.000,in Betrieb,4,...,16894712.0,17386284.0,17240584.0,16920860.0,13789128.0,14118688.0,17330468.0,11807604.0,12664780.0,11570712.0
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19875248.0,19548452.0,18843136.0,15048744.0,11641976.0,12904452.0,12459672.0,11579420.0,9559692.0,7695952.0
322,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,14990560.0,19417880.0,18217840.0,12799528.0,8126980.0,12600084.0,15112584.0,11693868.0,10407684.0,9912028.0
97,SN80011277,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,Ja,2000,1999,1782.000,in Betrieb,2,...,11434684.0,11882612.0,12033784.0,9265552.0,8355832.0,11260748.0,12106732.0,7719272.0,5887252.0,7394435.0
39,NW900-9141660,Trianel Kohlekraftwerk Lünen,Nordrhein-Westfalen,Steinkohle,Ja,2013,2013,746.000,in Betrieb,1,...,3954880.0,3276384.0,4009084.0,3334960.0,1633040.0,3824400.0,3822648.0,2579020.0,2557468.0,2785686.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
#np

In [88]:
co2dict2 = {}
for j in range(2007, PRTR_YEAR):
    co2dict2[j] = 'co2_' + str(j)

In [89]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023',
 2024: 'co2_2024'}

In [90]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2025):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, PRTR_YEAR):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [91]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022',
 ('amount', 2023): 'co2_2023',
 ('amount', 2024): 'co2_2024'}

In [92]:
np2 = np.rename(columns=rdict)

In [93]:
np3 = np2.fillna(value=ddict)

In [94]:
np4 = np3.sort_values(2020, ascending=False)

In [95]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
230,SN70015796,Boxberg Block N,Sachsen,Braunkohle,Ja,2012,1979,2470.000,in Betrieb,4,...,16894712.0,17386284.0,17240584.0,16920860.0,13789128.0,14118688.0,17330468.0,11807604.0,12664780.0,11570712.0
217,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19875248.0,19548452.0,18843136.0,15048744.0,11641976.0,12904452.0,12459672.0,11579420.0,9559692.0,7695952.0
97,SN80011277,Kraftwerk Lippendorf Block R,Sachsen,Braunkohle,Ja,2000,1999,1782.000,in Betrieb,2,...,11434684.0,11882612.0,12033784.0,9265552.0,8355832.0,11260748.0,12106732.0,7719272.0,5887252.0,7394435.0
322,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,14990560.0,19417880.0,18217840.0,12799528.0,8126980.0,12600084.0,15112584.0,11693868.0,10407684.0,9912028.0
278,NW100-0167182,SWD KWF GTKW,Nordrhein-Westfalen,Erdgas,Ja,2016,1972,1205.600,in Betrieb,6,...,2695108.0,2869088.0,3054844.0,3165184.0,3841716.0,2916120.0,2374336.0,2384732.0,2640068.0,2625048.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,BYS00334,Turbine 2,Bayern,Erdgas,Ja,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,SD664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,SD664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,60.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [97]:
#np4

In [98]:
#np3.sort_values("2015", ascending=False)

In [99]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [100]:
pols

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
0,2024,BB16012651,NO2,Air,745000.0,6,Tsd. t,0.745000,NO2 [Tsd. t]
1,2024,BB16012651,PM10,Air,51300.0,6,Tsd. t,0.051300,PM10 [Tsd. t]
2,2024,BB16012651,NMVOC,Air,2119000.0,3,t,2119.000000,NMVOC [t]
3,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
4,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
16412,2010,TH86012942,NO2,Air,104000.0,6,Tsd. t,0.104000,NO2 [Tsd. t]
16413,2009,TH86012942,NO2,Air,136000.0,6,Tsd. t,0.136000,NO2 [Tsd. t]
16414,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
16415,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
16416,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [101]:
#pols2

In [102]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [103]:
#pols1

In [104]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [105]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [106]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [107]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [108]:
pols2a

       year     plantid       amount
55     2024  BB16018798  233000000.0
56     2023  BB16018798  285000000.0
57     2022  BB16018798  247000000.0
59     2021  BB16018798  247000000.0
61     2020  BB16018798  268000000.0
...     ...         ...          ...
16408  2020  TH86012942  122000000.0
16409  2019  TH86012942  119000000.0
16410  2018  TH86012942  126000000.0
16411  2010  TH86012942  141000000.0
16415  2007  TH86012942  166000000.0

[3036 rows x 3 columns]

In [109]:
pols4 = pols3.reset_index()

In [110]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022',
 2023: 'co2_2023',
 2024: 'co2_2024'}

In [111]:
pols5 = pols4.rename(columns=co2dict2)

In [112]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023,co2_2024
0,BB16018798,2.420000e+08,2.670000e+08,2.350000e+08,2.790000e+08,2.370000e+08,2.200000e+08,2.210000e+08,2.200000e+08,2.730000e+08,3.000000e+08,2.430000e+08,2.520000e+08,2.980000e+08,2.680000e+08,2.470000e+08,2.470000e+08,2.850000e+08,2.330000e+08
1,BB23020389,1.640000e+08,1.660000e+08,1.620000e+08,1.110000e+08,1.040000e+08,3.620000e+08,4.440000e+08,4.520000e+08,3.650000e+08,4.080000e+08,4.130000e+08,4.640000e+08,4.440000e+08,4.250000e+08,4.170000e+08,4.240000e+08,4.340000e+08,3.250000e+08
2,BB23020490,4.110000e+09,4.470000e+09,4.490000e+09,4.080000e+09,4.120000e+09,3.400000e+09,3.570000e+09,3.710000e+09,4.020000e+09,3.750000e+09,3.850000e+09,3.810000e+09,3.340000e+09,3.500000e+09,3.390000e+09,3.550000e+09,3.015000e+09,3.277000e+09
3,BB23022811,1.920000e+08,1.820000e+08,1.840000e+08,1.920000e+08,1.770000e+08,1.800000e+08,1.780000e+08,1.610000e+08,1.680000e+08,1.750000e+08,1.650000e+08,1.680000e+08,1.470000e+08,1.610000e+08,1.710000e+08,1.660000e+08,1.500000e+08,1.210000e+08
4,BB45025564,2.420000e+10,2.350000e+10,2.360000e+10,2.380000e+10,2.430000e+10,2.480000e+10,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10,1.413400e+10,1.225700e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,ST18046,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,2.440000e+08,2.500000e+08,2.290000e+08,2.250000e+08,2.210000e+08,2.210000e+08
215,TH30013152,NaN,2.710333e+08,2.490000e+08,2.650000e+08,2.570000e+08,2.450000e+08,2.500000e+08,2.560000e+08,2.600000e+08,2.960000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.980000e+08,2.930000e+08,2.620000e+08,2.540000e+08
216,TH62013494,1.770000e+08,1.807979e+08,1.030000e+08,1.510000e+08,1.700000e+08,1.630000e+08,1.350000e+08,1.500000e+08,1.420000e+08,1.210000e+08,1.500000e+08,1.420000e+08,1.440000e+08,1.470000e+08,1.420000e+08,1.310000e+08,1.290000e+08,1.270000e+08
217,TH72012874,3.430000e+08,3.454339e+08,3.670000e+08,3.850000e+08,3.530000e+08,3.010000e+08,2.230000e+08,1.880000e+08,1.880000e+08,2.250000e+08,2.430000e+08,2.620000e+08,2.100000e+08,2.230000e+08,2.640000e+08,1.790000e+08,1.770000e+08,1.850000e+08
218,TH86012942,1.660000e+08,NaN,NaN,1.410000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.260000e+08,1.190000e+08,1.220000e+08,1.210000e+08,1.170000e+08,1.110000e+08,1.070000e+08

In [113]:
#final

In [114]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [115]:
final.to_csv("test.csv")
final2 = final.copy()

In [116]:
#final2 = final.rename(columns=co2dict)

In [117]:
#list(final4)

In [118]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, co2_2023, co2_2024]
Index: []

[0 rows x 49 columns]

In [119]:
final3 = final2.dropna(subset=["plantid"])

In [120]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [121]:
col_arr = list(final4)

In [122]:
len(col_arr)

47

In [123]:
#final4.rename(columns={"2023_x": 2023}, inplace=True)

In [124]:
#final4.drop(columns="2023_y", inplace=True)

In [125]:
#final3.sort_values('plantid').reset_index(drop=True)

In [126]:
def make_to_int(df, column):
    #df[column] = df[column]
    df[column] = df[column].round().astype('Int64')

In [127]:
list(final4)[45:]

['co2_2023', 'co2_2024']

In [128]:
for i in range(17, 47):
    make_to_int(final4, col_arr[i])

In [129]:
final4.to_csv('plants_newest_nh.csv', header=False, index=False)

In [130]:
final4.loc[final4.plantid == "SN80011277"][2025]

2    7394435
Name: 2025, dtype: Int64

In [131]:
final3.loc[final3.plantid == "BYS00041"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,co2_2023,co2_2024
217,BYS00041,SWM HKW Nord 1 T10,Bayern,Erdgas,Ja,1991,1984,373.0,in Betrieb,3,...,2.570000e+09,2.520000e+09,2.380000e+09,2.040000e+09,2.040000e+09,1.580000e+09,1.640000e+09,1.810000e+09,2.090000e+09,1.460000e+09

In [132]:
a = int(2.990000e+10 )

In [133]:
a

29900000000

In [134]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 'co2_2023',
 'co2_2024']

In [135]:
#final2.sort_values('endop')

In [136]:
final4.columns

Index([       'plantid',      'plantname',   'federalstate',   'energysource',
                  'chp', 'latestexpanded',      'initialop',     'totalpower',
                'state',     'blockcount',        'company',            'plz',
                  'ort',        'strasse',         'hausnr',  'geo_lat_wgs84',
       'geo_long_wgs84',    'activepower',             2015,             2016,
                   2017,             2018,             2019,             2020,
                   2021,             2022,             2023,             2024,
                   2025,       'co2_2007',       'co2_2008',       'co2_2009',
             'co2_2010',       'co2_2011',       'co2_2012',       'co2_2013',
             'co2_2014',       'co2_2015',       'co2_2016',       'co2_2017',
             'co2_2018',       'co2_2019',       'co2_2020',       'co2_2021',
             'co2_2022',       'co2_2023',       'co2_2024'],
      dtype='object')

In [137]:
profit = pd.read_csv("../money/profit.csv")

In [138]:
final5 = final4.merge(profit, on="plantid", how="left")

In [139]:
final6 = final5.drop(columns=['plantname_y'])

In [140]:
final6.to_csv("plants_with_profit_v2.csv", index=False, header=False)

In [141]:
final6.columns

Index([       'plantid',    'plantname_x',   'federalstate',   'energysource',
                  'chp', 'latestexpanded',      'initialop',     'totalpower',
                'state',     'blockcount',        'company',            'plz',
                  'ort',        'strasse',         'hausnr',  'geo_lat_wgs84',
       'geo_long_wgs84',    'activepower',             2015,             2016,
                   2017,             2018,             2019,             2020,
                   2021,             2022,             2023,             2024,
                   2025,       'co2_2007',       'co2_2008',       'co2_2009',
             'co2_2010',       'co2_2011',       'co2_2012',       'co2_2013',
             'co2_2014',       'co2_2015',       'co2_2016',       'co2_2017',
             'co2_2018',       'co2_2019',       'co2_2020',       'co2_2021',
             'co2_2022',       'co2_2023',       'co2_2024',        'revenue',
               'profit'],
      dtype='object')