In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re

In [2]:
plants = pd.read_csv("plants_2.csv")
power = pd.read_csv("../production/yearly.csv")

In [3]:
#power.melt(id_vars=['plantid'], value_vars=['yearpower', 'year'])

In [4]:
#power.loc[power.plantid == "06-05-100-0248923"]

In [5]:
power

     year        plantid  yearpower
0    2015  NW100-0365906    1501479
1    2015  NW100-0167182     115006
2    2015  NW500-0342658    2306293
3    2015     HE30001045    2528577
4    2015  NW900-0079017          0
..    ...            ...        ...
533  2024       BE166928    1171226
534  2024    SL0105352-G     137404
535  2024       BYS00044    1075551
536  2024  NW300-9002708    1403116
537  2024       BE169709     361995

[538 rows x 3 columns]

In [6]:
powers = power.pivot(index='plantid', columns='year')

In [7]:
powers

                            yearpower                                      \
year                             2015        2016        2017        2018
plantid
06-02-B10117A007            1108161.0   1306733.0   1249523.0    936518.0
06-05-100-0431554           3725774.0   4348854.0   1140029.0         NaN
06-05-100-0853075           1014369.0    765838.0    262118.0         NaN
BB23020490                  1652899.0   1527903.0   1575791.0   1460799.0
BB45025564                 19612604.0  19947623.0  19621573.0  18910299.0
BB45025611                 10917280.0  10906473.0  10095854.0  11030178.0
BE166928                    2753140.0   2355394.0   2258525.0   2010088.0
BE169709                     510413.0    572838.0    624739.0    608642.0
BE172654                    1596689.0   1763179.0   1998532.0   1925704.0
BE172656                          NaN         NaN         NaN         NaN
BWpf-450-1020129-00000000   3212801.0   2389285.0   2386609.0   2860319.0
BWpf-450-1195689-00000000    231782.0    270947.0    264097.0    284857.0
BWpf-450-1741292-00000000   1700051.0   1942227.0   1197633.0   1123239.0
BWpf-450-2142201-00000000     24818.0     17861.0     30564.0     23211.0
BWpf-450-2797933-00000000   2800466.0   1519549.0   3295438.0   3086148.0
BYS00044                     433898.0   1324992.0   1710838.0   1527573.0
BYS00048                     560921.0    204765.0    133508.0     24090.0
BYS00114                     957779.0    573483.0    231240.0    232099.0
BYS00727                     397997.0    230663.0    434355.0    225065.0
HE30001045                  2528577.0   2800714.0   2189196.0   1838748.0
HE50001960                   554069.0   1525406.0   1686259.0   1172314.0
MV30000226                  2786977.0   3224251.0   2846041.0   2179318.0
NI01010098080               2858036.0   1988560.0   2187603.0   2607831.0
NI01012110180               2102990.0   1710289.0         0.0         0.0
NI01241117210               1103769.0   1687429.0   1620072.0   1588253.0
NI06060316030               1658160.0   1564526.0   1463060.0   1517609.0
NI09000237910                585754.0   1344793.0   2718408.0    158483.0
NI10257673950               1069694.0   3799083.0   4304629.0   3044703.0
NW100-0167182                115006.0   2708069.0   2880797.0   3065409.0
NW100-0229264                151568.0    927166.0    994624.0    816489.0
NW100-0248923              15386816.0  21812847.0  22611486.0  25507220.0
NW100-0365906               1501479.0   3485338.0   2307098.0   2528065.0
NW300-0326774              13154280.0  15033694.0  19473733.0  18266049.0
NW300-0370387                 33875.0   2492568.0   3223712.0   2691455.0
NW300-0877384               7538467.0  11099158.0  13066618.0  10807558.0
NW300-0923949                 43038.0    182025.0    205947.0    117470.0
NW300-9002708               1383067.0   1290593.0    947435.0    621111.0
NW300-9046030                140770.0    921266.0    887609.0    437028.0
NW500-0342658               2306293.0   2886165.0   3224127.0   3113060.0
NW500-0915123                     NaN         NaN         1.0         0.0
NW700-0105516               3084626.0   3368833.0   2221875.0   1914212.0
NW900-0045033                355075.0    325740.0    206013.0    127330.0
NW900-0079017                     0.0    235033.0         0.0         0.0
NW900-0080266                 87183.0       145.0       265.0         0.0
NW900-0125939                 18363.0    425797.0    490275.0    461604.0
NW900-0205103               1723045.0   2796586.0   1796226.0   1741338.0
NW900-0327252               1561425.0   1858450.0   1466341.0   1245644.0
NW900-0865327               1484406.0   2943263.0   1979838.0   2010055.0
NW900-0884101                240575.0    245967.0    556310.0    748995.0
NW900-9140178                461540.0   1274850.0   1155555.0    884834.0
NW900-9141660               1108280.0   3964382.0   3283987.0   4018489.0
SH50080412                  1370270.0   1121635.0   1047315.0   1159172.0
SL0100999-G                 1659688.0   1779348.0    489391.0     31504.0
SL0101000-G                  907431.0   1170116.0    962461.0    898700.0
SL0101003-G                 1091640.0   1179029.0    411538.0     17208.0
SL0105352-G                   33579.0    156589.0    218460.0    205599.0
SN70015796                 17872558.0  16940828.0  17432468.0  17284829.0
SN80011256                   298386.0    574814.0    441036.0    337447.0
SN80011277                 10815349.0  11455412.0  11905299.0  12054987.0
ST100125                    4170448.0   4270624.0   4314039.0   4904878.0

                                                                           \
year                             2019        2020        2021        2022
plantid
06-02-B10117A007             790997.0    798187.0    842285.0    952563.0
06-05-100-0431554                 NaN         NaN         NaN         NaN
06-05-100-0853075                 NaN         NaN         NaN         NaN
BB23020490                  1352131.0   1391578.0   1272081.0   1356360.0
BB45025564                 15104005.0  11684991.0  12948900.0  12505492.0
BB45025611                  9346499.0   9051706.0  10371571.0   8093328.0
BE166928                    1369313.0   1402576.0   1308676.0   1360306.0
BE169709                     642157.0    549960.0    446420.0    374627.0
BE172654                    1925509.0   1750721.0   1688659.0   1200657.0
BE172656                          NaN         NaN   1044618.0   1277506.0
BWpf-450-1020129-00000000   1263654.0    500508.0   2174574.0   1790164.0
BWpf-450-1195689-00000000    256256.0    249767.0    241906.0    218516.0
BWpf-450-1741292-00000000    814085.0    565414.0    986100.0   1147426.0
BWpf-450-2142201-00000000     15808.0     15315.0     32512.0     30997.0
BWpf-450-2797933-00000000   2546913.0   1582216.0   3324923.0   3824201.0
BYS00044                    1538426.0   1398076.0    660768.0   1028191.0
BYS00048                      37682.0   1734818.0   4187402.0   2498555.0
BYS00114                     130502.0    145279.0    205230.0    184002.0
BYS00727                     160377.0    186995.0    152501.0    167409.0
HE30001045                  1291073.0   1036335.0   1126562.0   2320683.0
HE50001960                  1978930.0   2124117.0   1213444.0   1460862.0
MV30000226                  2075087.0   1122191.0   2485147.0   2000279.0
NI01010098080                760756.0    919152.0    964026.0   1058804.0
NI01012110180                     0.0         0.0         NaN         NaN
NI01241117210               1529038.0   1404615.0   1359363.0   1086121.0
NI06060316030               1056340.0    891176.0   1177983.0   1550712.0
NI09000237910                     NaN         NaN         NaN         NaN
NI10257673950               4916220.0   5232317.0   3676568.0   3638322.0
NW100-0167182               3178536.0   3856165.0   2926674.0   2382175.0
NW100-0229264                999802.0   1144278.0    833933.0    543233.0
NW100-0248923              17881538.0  14625468.0  16554636.0  21857955.0
NW100-0365906               2509842.0   1392609.0   2387357.0   3198339.0
NW300-0326774              12827830.0   8145901.0  12626436.0  15147355.0
NW300-0370387               3671407.0   2641045.0   2863256.0   1983144.0
NW300-0877384               8834396.0   8554457.0   9636584.0  12110914.0
NW300-0923949                   597.0     22135.0     42957.0         0.0
NW300-9002708                846733.0    727081.0    523880.0    389290.0
NW300-9046030               2513194.0   2708622.0   1116959.0    673046.0
NW500-0342658               2862632.0   2257520.0   1899375.0   1937650.0
NW500-0915123                  1495.0   2275756.0   4696684.0   4558132.0
NW700-0105516                667080.0    948088.0    110031.0    692524.0
NW900-0045033                     NaN         NaN         NaN         NaN
NW900-0079017                     0.0         0.0         0.0         NaN
NW900-0080266                     NaN         NaN         NaN         NaN
NW900-0125939                991632.0   1332487.0   1110705.0    877719.0
NW900-0205103                740499.0    374569.0    914717.0   2025901.0
NW900-0327252               1005968.0    730048.0   1148183.0   1549229.0
NW900-0865327                470336.0    279376.0     12182.0     10529.0
NW900-0884101                     NaN         NaN         NaN         NaN
NW900-9140178               1753710.0   2455782.0   1405754.0   1357174.0
NW900-9141660               3343561.0   1637333.0   3832813.0   3830324.0
SH50080412                   366425.0         NaN         NaN         NaN
SL0100999-G                   58183.0    138061.0    227437.0    727205.0
SL0101000-G                  503529.0    472461.0    636096.0   1030594.0
SL0101003-G                   37646.0     63099.0     74852.0    328566.0
SL0105352-G                  285545.0    235451.0    252929.0    172319.0
SN70015796                 16966904.0  13829348.0  14156333.0  17375485.0
SN80011256                   421516.0    516161.0    220020.0         NaN
SN80011277                  9284046.0   8374593.0  11280826.0  12129746.0
ST100125                    2904120.0   2083204.0   3265733.0   3184684.0


year                             2023        2024
plantid
06-02-B10117A007             707521.0    637327.0
06-05-100-0431554                 NaN         NaN
06-05-100-0853075                 NaN         NaN
BB23020490                  1182522.0   1386106.0
BB45025564                 11628593.0   9538243.0
BB45025611                  8442791.0   7006971.0
BE166928                    1284397.0   1171226.0
BE169709                     347614.0    361995.0
BE172654                    1375565.0   1292139.0
BE172656                    1135131.0    962802.0
BWpf-450-1020129-00000000    306853.0    573237.0
BWpf-450-1195689-00000000    199563.0    216405.0
BWpf-450-1741292-00000000    543854.0    485074.0
BWpf-450-2142201-00000000     13956.0     21430.0
BWpf-450-2797933-00000000   2553799.0   2062393.0
BYS00044                     806060.0   1075551.0
BYS00048                    2856627.0   3445690.0
BYS00114                     167721.0    141668.0
BYS00727                      60018.0    154566.0
HE30001045                  1018041.0    291623.0
HE50001960                   357840.0         NaN
MV30000226                  1145693.0    638004.0
NI01010098080                609549.0    498280.0
NI01012110180                     NaN         NaN
NI01241117210               1191623.0    467977.0
NI06060316030               1136891.0    942371.0
NI09000237910                     NaN         NaN
NI10257673950               3820255.0   2981610.0
NW100-0167182               2392763.0   2628734.0
NW100-0229264                395406.0    336060.0
NW100-0248923              15021992.0  12629202.0
NW100-0365906               1229773.0    392952.0
NW300-0326774              11725739.0  10337723.0
NW300-0370387               1999677.0   2247544.0
NW300-0877384               7312086.0   8192538.0
NW300-0923949                     0.0         0.0
NW300-9002708                907665.0   1403116.0
NW300-9046030                587200.0   1136896.0
NW500-0342658               1197970.0    353192.0
NW500-0915123               3406179.0   2005753.0
NW700-0105516               1116943.0    212496.0
NW900-0045033                     NaN         NaN
NW900-0079017                     NaN         NaN
NW900-0080266                     NaN         NaN
NW900-0125939                565667.0    782046.0
NW900-0205103                834744.0    232316.0
NW900-0327252                584248.0    143684.0
NW900-0865327                 10623.0      8569.0
NW900-0884101                     NaN         NaN
NW900-9140178                918998.0   1287514.0
NW900-9141660               2585237.0   2562505.0
SH50080412                        NaN         NaN
SL0100999-G                  833290.0    262692.0
SL0101000-G                  111729.0     17196.0
SL0101003-G                  634532.0    160123.0
SL0105352-G                  141928.0    137404.0
SN70015796                 11844322.0  12617201.0
SN80011256                        NaN         NaN
SN80011277                  7736932.0   5843144.0
ST100125                    3064202.0   3312948.0

In [8]:
df = powers.xs(('yearpower'), axis=1, drop_level=True)

In [9]:
df2 = df.reset_index()

In [10]:
df2

year,plantid,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,06-02-B10117A007,1108161.0,1306733.0,1249523.0,936518.0,790997.0,798187.0,842285.0,952563.0,707521.0,637327.0
1,06-05-100-0431554,3725774.0,4348854.0,1140029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06-05-100-0853075,1014369.0,765838.0,262118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BB23020490,1652899.0,1527903.0,1575791.0,1460799.0,1352131.0,1391578.0,1272081.0,1356360.0,1182522.0,1386106.0
4,BB45025564,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
5,BB45025611,10917280.0,10906473.0,10095854.0,11030178.0,9346499.0,9051706.0,10371571.0,8093328.0,8442791.0,7006971.0
6,BE166928,2753140.0,2355394.0,2258525.0,2010088.0,1369313.0,1402576.0,1308676.0,1360306.0,1284397.0,1171226.0
7,BE169709,510413.0,572838.0,624739.0,608642.0,642157.0,549960.0,446420.0,374627.0,347614.0,361995.0
8,BE172654,1596689.0,1763179.0,1998532.0,1925704.0,1925509.0,1750721.0,1688659.0,1200657.0,1375565.0,1292139.0
9,BE172656,NaN,NaN,NaN,NaN,NaN,NaN,1044618.0,1277506.0,1135131.0,962802.0
10,BWpf-450-1020129-00000000,3212801.0,2389285.0,2386609.0,2860319.0,1263654.0,500508.0,2174574.0,1790164.0,306853.0,573237.0
11,BWpf-450-1195689-00000000,231782.0,270947.0,264097.0,284857.0,256256.0,249767.0,241906.0,218516.0,199563.0,216405.0
12,BWpf-450-1741292-00000000,1700051.0,1942227.0,1197633.0,1123239.0,814085.0,565414.0,986100.0,1147426.0,543854.0,485074.0
13,BWpf-450-2142201-00000000,24818.0,17861.0,30564.0,23211.0,15808.0,15315.0,32512.0,30997.0,13956.0,21430.0
14,BWpf-450-2797933-00000000,2800466.0,1519549.0,3295438.0,3086148.0,2546913.0,1582216.0,3324923.0,3824201.0,2553799.0,2062393.0
15,BYS00044,433898.0,1324992.0,1710838.0,1527573.0,1538426.0,1398076.0,660768.0,1028191.0,806060.0,1075551.0
16,BYS00048,560921.0,204765.0,133508.0,24090.0,37682.0,1734818.0,4187402.0,2498555.0,2856627.0,3445690.0
17,BYS00114,957779.0,573483.0,231240.0,232099.0,130502.0,145279.0,205230.0,184002.0,167721.0,141668.0
18,BYS00727,397997.0,230663.0,434355.0,225065.0,160377.0,186995.0,152501.0,167409.0,60018.0,154566.0
19,HE30001045,2528577.0,2800714.0,2189196.0,1838748.0,1291073.0,1036335.0,1126562.0,2320683.0,1018041.0,291623.0
20,HE50001960,554069.0,1525406.0,1686259.0,1172314.0,1978930.0,2124117.0,1213444.0,1460862.0,357840.0,NaN
21,MV30000226,2786977.0,3224251.0,2846041.0,2179318.0,2075087.0,1122191.0,2485147.0,2000279.0,1145693.0,638004.0
22,NI01010098080,2858036.0,1988560.0,2187603.0,2607831.0,760756.0,919152.0,964026.0,1058804.0,609549.0,498280.0
23,NI01012110180,2102990.0,1710289.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
24,NI01241117210,1103769.0,1687429.0,1620072.0,1588253.0,1529038.0,1404615.0,1359363.0,1086121.0,1191623.0,467977.0
25,NI06060316030,1658160.0,1564526.0,1463060.0,1517609.0,1056340.0,891176.0,1177983.0,1550712.0,1136891.0,942371.0
26,NI09000237910,585754.0,1344793.0,2718408.0,158483.0,NaN,NaN,NaN,NaN,NaN,NaN
27,NI10257673950,1069694.0,3799083.0,4304629.0,3044703.0,4916220.0,5232317.0,3676568.0,3638322.0,3820255.0,2981610.0
28,NW100-0167182,115006.0,2708069.0,2880797.0,3065409.0,3178536.0,3856165.0,2926674.0,2382175.0,2392763.0,2628734.0
29,NW100-0229264,151568.0,927166.0,994624.0,816489.0,999802.0,1144278.0,833933.0,543233.0,395406.0,336060.0
30,NW100-0248923,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
31,NW100-0365906,1501479.0,3485338.0,2307098.0,2528065.0,2509842.0,1392609.0,2387357.0,3198339.0,1229773.0,392952.0
32,NW300-0326774,13154280.0,15033694.0,19473733.0,18266049.0,12827830.0,8145901.0,12626436.0,15147355.0,11725739.0,10337723.0
33,NW300-0370387,33875.0,2492568.0,3223712.0,2691455.0,3671407.0,2641045.0,2863256.0,1983144.0,1999677.0,2247544.0
34,NW300-0877384,7538467.0,11099158.0,13066618.0,10807558.0,8834396.0,8554457.0,9636584.0,12110914.0,7312086.0,8192538.0
35,NW300-0923949,43038.0,182025.0,205947.0,117470.0,597.0,22135.0,42957.0,0.0,0.0,0.0
36,NW300-9002708,1383067.0,1290593.0,947435.0,621111.0,846733.0,727081.0,523880.0,389290.0,907665.0,1403116.0
37,NW300-9046030,140770.0,921266.0,887609.0,437028.0,2513194.0,2708622.0,1116959.0,673046.0,587200.0,1136896.0
38,NW500-0342658,2306293.0,2886165.0,3224127.0,3113060.0,2862632.0,2257520.0,1899375.0,1937650.0,1197970.0,353192.0
39,NW500-0915123,NaN,NaN,1.0,0.0,1495.0,2275756.0,4696684.0,4558132.0,3406179.0,2005753.0
40,NW700-0105516,3084626.0,3368833.0,2221875.0,1914212.0,667080.0,948088.0,110031.0,692524.0,1116943.0,212496.0
41,NW900-0045033,355075.0,325740.0,206013.0,127330.0,NaN,NaN,NaN,NaN,NaN,NaN
42,NW900-0079017,0.0,235033.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
43,NW900-0080266,87183.0,145.0,265.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
44,NW900-0125939,18363.0,425797.0,490275.0,461604.0,991632.0,1332487.0,1110705.0,877719.0,565667.0,782046.0
45,NW900-0205103,1723045.0,2796586.0,1796226.0,1741338.0,740499.0,374569.0,914717.0,2025901.0,834744.0,232316.0
46,NW900-0327252,1561425.0,1858450.0,1466341.0,1245644.0,1005968.0,730048.0,1148183.0,1549229.0,584248.0,143684.0
47,NW900-0865327,1484406.0,2943263.0,1979838.0,2010055.0,470336.0,279376.0,12182.0,10529.0,10623.0,8569.0
48,NW900-0884101,240575.0,245967.0,556310.0,748995.0,NaN,NaN,NaN,NaN,NaN,NaN
49,NW900-9140178,461540.0,1274850.0,1155555.0,884834.0,1753710.0,2455782.0,1405754.0,1357174.0,918998.0,1287514.0
50,NW900-9141660,1108280.0,3964382.0,3283987.0,4018489.0,3343561.0,1637333.0,3832813.0,3830324.0,2585237.0,2562505.0
51,SH50080412,1370270.0,1121635.0,1047315.0,1159172.0,366425.0,NaN,NaN,NaN,NaN,NaN
52,SL0100999-G,1659688.0,1779348.0,489391.0,31504.0,58183.0,138061.0,227437.0,727205.0,833290.0,262692.0
53,SL0101000-G,907431.0,1170116.0,962461.0,898700.0,503529.0,472461.0,636096.0,1030594.0,111729.0,17196.0
54,SL0101003-G,1091640.0,1179029.0,411538.0,17208.0,37646.0,63099.0,74852.0,328566.0,634532.0,160123.0
55,SL0105352-G,33579.0,156589.0,218460.0,205599.0,285545.0,235451.0,252929.0,172319.0,141928.0,137404.0
56,SN70015796,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
57,SN80011256,298386.0,574814.0,441036.0,337447.0,421516.0,516161.0,220020.0,NaN,NaN,NaN
58,SN80011277,10815349.0,11455412.0,11905299.0,12054987.0,9284046.0,8374593.0,11280826.0,12129746.0,7736932.0,5843144.0
59,ST100125,4170448.0,4270624.0,4314039.0,4904878.0,2904120.0,2083204.0,3265733.0,3184684.0,3064202.0,3312948.0

In [11]:
#df

In [12]:
#powers.unstack('plantid')

In [13]:
np = pd.merge(plants, df2, how='left', on="plantid")

In [14]:
np

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,NW100-0046639,0065 - STW - BHKW - KWK,Nordrhein-Westfalen,Erdgas,NaN,2024,2024,7.257,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TH72012874,Gasmotor 1 Jena,Thüringen,Erdgas,NaN,2022,2022,60.875,in Betrieb,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NW500-0875785,"Kraftwerk VI, Block 61, DT610",Nordrhein-Westfalen,Erdgas,NaN,2022,2022,273.994,in Betrieb,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SN70015917,Gasmotoren-Heizkraftwerk Dresden-Reick - Aggre...,Sachsen,Erdgas,NaN,2022,2022,92.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NI04247180070,Nordland GuD-Anlage Gasturbine,Niedersachsen,Erdgas,NaN,2022,2022,85.286,in Betrieb,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,NW300-9046797,LEV KWG G02,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,7538467.0,11099158.0,13066618.0,10807558.0,8834396.0,8554457.0,9636584.0,12110914.0,7312086.0,8192538.0
258,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
np.sort_values(by=[2019], ascending=False)

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
192,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
162,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
152,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
229,NW300-0326774,Niederaußem,Nordrhein-Westfalen,Braunkohle,Ja,2003,1963,3359.000,in Betrieb,8,...,13154280.0,15033694.0,19473733.0,18266049.0,12827830.0,8145901.0,12626436.0,15147355.0,11725739.0,10337723.0
72,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,10917280.0,10906473.0,10095854.0,11030178.0,9346499.0,9051706.0,10371571.0,8093328.0,8442791.0,7006971.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,HE30000163,IPH Strom GT4,Hessen,Erdgas,NaN,2022,1956,426.118,in Betrieb,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NW300-9046797,LEV KWG G02,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#np

In [17]:
co2dict2 = {}
for j in range(2007, 2023):
    co2dict2[j] = 'co2_' + str(j)

In [18]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [19]:
rdict = {}
ddict = {}
co2dict = {}

for i in range(2015, 2025):
    rdict[('yearpower', i)] = 'energy_' + str(i)
    ddict[str(i)] = 0

for j in range(2007, 2023):
    co2dict[('amount', j)] = 'co2_' + str(j)

In [20]:
co2dict

{('amount', 2007): 'co2_2007',
 ('amount', 2008): 'co2_2008',
 ('amount', 2009): 'co2_2009',
 ('amount', 2010): 'co2_2010',
 ('amount', 2011): 'co2_2011',
 ('amount', 2012): 'co2_2012',
 ('amount', 2013): 'co2_2013',
 ('amount', 2014): 'co2_2014',
 ('amount', 2015): 'co2_2015',
 ('amount', 2016): 'co2_2016',
 ('amount', 2017): 'co2_2017',
 ('amount', 2018): 'co2_2018',
 ('amount', 2019): 'co2_2019',
 ('amount', 2020): 'co2_2020',
 ('amount', 2021): 'co2_2021',
 ('amount', 2022): 'co2_2022'}

In [21]:
np2 = np.rename(columns=rdict)

In [22]:
np3 = np2.fillna(value=ddict)

In [23]:
np4 = np3.sort_values(2020, ascending=False)

In [24]:
np4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
192,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,15386816.0,21812847.0,22611486.0,25507220.0,17881538.0,14625468.0,16554636.0,21857955.0,15021992.0,12629202.0
162,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,17872558.0,16940828.0,17432468.0,17284829.0,16966904.0,13829348.0,14156333.0,17375485.0,11844322.0,12617201.0
152,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,19612604.0,19947623.0,19621573.0,18910299.0,15104005.0,11684991.0,12948900.0,12505492.0,11628593.0,9538243.0
72,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,10917280.0,10906473.0,10095854.0,11030178.0,9346499.0,9051706.0,10371571.0,8093328.0,8442791.0,7006971.0
257,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,7538467.0,11099158.0,13066618.0,10807558.0,8834396.0,8554457.0,9636584.0,12110914.0,7312086.0,8192538.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,HE30000163,IPH Strom GT4,Hessen,Erdgas,NaN,2022,1956,426.118,in Betrieb,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NW300-9046797,LEV KWG G02,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#with pd.option_context('mode.use_inf_as_null', True):
np4 = np3.sort_values(2020, ascending=False)

In [26]:
#np4

In [27]:
#np3.sort_values("2015", ascending=False)

In [28]:
pols = pd.read_csv('../pollution/pollutants.csv')

In [29]:
pols

,year,plantid,pollutant,releases_to,amount,potency,unit_2,amount_2,pollutant2
0,2023,BB16012651,NO2,Air,554000.0,6,Tsd. t,0.554000,NO2 [Tsd. t]
1,2023,BB16012651,PM10,Air,83100.0,6,Tsd. t,0.083100,PM10 [Tsd. t]
2,2023,BB16012651,NMVOC,Air,2580000.0,3,t,2580.000000,NMVOC [t]
3,2022,BB16012651,NO2,Air,671000.0,6,Tsd. t,0.671000,NO2 [Tsd. t]
4,2022,BB16012651,PM10,Air,88800.0,6,Tsd. t,0.088800,PM10 [Tsd. t]
...,...,...,...,...,...,...,...,...,...
65140,2008,TH86012942,NO2,Air,150652.9,6,Tsd. t,0.150653,NO2 [Tsd. t]
65141,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
65142,2007,TH86012942,CO2,Air,166000000.0,9,Mio. t,0.166000,CO2 [Mio. t]
65143,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]
65144,2007,TH86012942,NO2,Air,176000.0,6,Tsd. t,0.176000,NO2 [Tsd. t]

In [30]:
#pols2

In [31]:
pols1 = pols.loc[pols['releases_to'] == "Air"].loc[pols['pollutant'] == "CO2"]

In [32]:
#pols1

In [33]:
pols2 = pols1.drop(columns=['pollutant', 'releases_to', 'potency', 'unit_2', 'amount_2', 'pollutant2'])

In [34]:
pols2a = pols2.drop_duplicates(subset=['plantid', 'year'])

In [35]:
#pols2[pols2.duplicated(['plantid', 'year'], keep=False)].sort_values("year", ascending=False)

In [36]:
pols3 = pols2a.pivot(index='plantid', columns='year', values='amount')

In [37]:
pols2a

       year     plantid       amount
52     2023  BB16018798  285000000.0
55     2022  BB16018798  247000000.0
61     2021  BB16018798  247000000.0
67     2020  BB16018798  268000000.0
73     2019  BB16018798  298000000.0
...     ...         ...          ...
65127  2020  TH86012942  122000000.0
65129  2019  TH86012942  119000000.0
65131  2018  TH86012942  126000000.0
65133  2010  TH86012942  141000000.0
65141  2007  TH86012942  166000000.0

[2926 rows x 3 columns]

In [38]:
pols4 = pols3.reset_index()

In [39]:
co2dict2

{2007: 'co2_2007',
 2008: 'co2_2008',
 2009: 'co2_2009',
 2010: 'co2_2010',
 2011: 'co2_2011',
 2012: 'co2_2012',
 2013: 'co2_2013',
 2014: 'co2_2014',
 2015: 'co2_2015',
 2016: 'co2_2016',
 2017: 'co2_2017',
 2018: 'co2_2018',
 2019: 'co2_2019',
 2020: 'co2_2020',
 2021: 'co2_2021',
 2022: 'co2_2022'}

In [40]:
pols5 = pols4.rename(columns=co2dict2)

In [41]:
pols5

year,plantid,co2_2007,co2_2008,co2_2009,co2_2010,co2_2011,co2_2012,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022,2023
0,BB16018798,2.420000e+08,2.670000e+08,2.350000e+08,2.790000e+08,2.370000e+08,2.200000e+08,2.210000e+08,2.200000e+08,2.730000e+08,3.000000e+08,2.430000e+08,2.520000e+08,2.980000e+08,2.680000e+08,2.470000e+08,2.470000e+08,2.850000e+08
1,BB23020389,1.640000e+08,1.660000e+08,1.620000e+08,1.110000e+08,1.040000e+08,3.620000e+08,4.440000e+08,4.520000e+08,3.650000e+08,4.080000e+08,4.130000e+08,4.640000e+08,4.440000e+08,4.250000e+08,4.170000e+08,4.240000e+08,4.340000e+08
2,BB23020490,4.110000e+09,4.470000e+09,4.490000e+09,4.080000e+09,4.120000e+09,3.400000e+09,3.570000e+09,3.710000e+09,4.020000e+09,3.750000e+09,3.850000e+09,3.810000e+09,3.340000e+09,3.500000e+09,3.390000e+09,3.550000e+09,3.015000e+09
3,BB23022811,1.920000e+08,1.820000e+08,1.840000e+08,1.920000e+08,1.770000e+08,1.800000e+08,1.780000e+08,1.610000e+08,1.680000e+08,1.750000e+08,1.650000e+08,1.680000e+08,1.470000e+08,1.610000e+08,1.710000e+08,1.660000e+08,1.500000e+08
4,BB45025564,2.420000e+10,2.350000e+10,2.360000e+10,2.380000e+10,2.430000e+10,2.480000e+10,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10,1.413400e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,ST18046,NaN,1.680000e+08,1.720000e+08,2.270000e+08,2.400000e+08,2.390000e+08,2.420000e+08,2.370000e+08,2.550000e+08,2.570000e+08,2.500000e+08,2.500000e+08,2.440000e+08,2.500000e+08,2.290000e+08,2.250000e+08,2.210000e+08
217,TH30013152,NaN,2.710333e+08,2.490000e+08,2.650000e+08,2.570000e+08,2.450000e+08,2.500000e+08,2.560000e+08,2.600000e+08,2.960000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.900000e+08,2.980000e+08,2.930000e+08,2.620000e+08
218,TH62013494,1.770000e+08,1.807979e+08,1.030000e+08,1.510000e+08,1.700000e+08,1.630000e+08,1.350000e+08,1.500000e+08,1.420000e+08,1.210000e+08,1.500000e+08,1.420000e+08,1.440000e+08,1.470000e+08,1.420000e+08,1.310000e+08,1.290000e+08
219,TH72012874,3.430000e+08,3.454339e+08,3.670000e+08,3.850000e+08,3.530000e+08,3.010000e+08,2.230000e+08,1.880000e+08,1.880000e+08,2.250000e+08,2.430000e+08,2.620000e+08,2.100000e+08,2.230000e+08,2.640000e+08,1.790000e+08,1.770000e+08
220,TH86012942,1.660000e+08,NaN,NaN,1.410000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.260000e+08,1.190000e+08,1.220000e+08,1.210000e+08,1.170000e+08,1.110000e+08

In [42]:
#final

In [43]:
final = pd.merge(np4, pols5, how='left', on="plantid")

In [44]:
final.to_csv("test.csv")
final2 = final.copy()

In [45]:
#final2 = final.rename(columns=co2dict)

In [46]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 '2023_x',
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 '2023_y']

In [47]:
final2[pd.isnull(final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023_x, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, 2023_y]
Index: []

[0 rows x 47 columns]

In [48]:
final3 = final2.dropna(subset=["plantid"])

In [49]:
final4 = final3.drop(["betreiber", "eigentuemer"], axis=1)

In [50]:
list(final4)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 '2023_x',
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 '2023_y']

In [51]:
final4.rename(columns={"2023_x": 2023}, inplace=True)

In [52]:
final4.drop(columns="2023_y", inplace=True)

In [53]:
#final3.sort_values('plantid').reset_index(drop=True)

In [54]:
final4.to_csv('plants_new_nh.csv', header=False, index=False)

In [55]:
final4.loc[final4.plantid == "BE172654"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
16,BE172654,HKW Mitte Dampfturbine,Berlin,Erdgas,NaN,1997,1997,444.0,in Betrieb,3,...,924000000.0,796000000.0,831000000.0,872000000.0,974000000.0,936000000.0,935000000.0,825000000.0,832000000.0,627000000.0

In [56]:
final3.loc[final3.plantid == "06-05-100-0248923"]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023_x, 2024, co2_2007, co2_2008, co2_2009, co2_2010, co2_2011, co2_2012, co2_2013, co2_2014, co2_2015, co2_2016, co2_2017, co2_2018, co2_2019, co2_2020, co2_2021, co2_2022, 2023_y]
Index: []

[0 rows x 47 columns]

In [57]:
a = int(2.990000e+10 )

In [58]:
a

29900000000

In [59]:
list(final2)

['plantid',
 'plantname',
 'federalstate',
 'energysource',
 'chp',
 'latestexpanded',
 'initialop',
 'totalpower',
 'state',
 'blockcount',
 'company',
 'betreiber',
 'eigentuemer',
 'plz',
 'ort',
 'strasse',
 'hausnr',
 'geo_lat_wgs84',
 'geo_long_wgs84',
 'activepower',
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 '2023_x',
 2024,
 'co2_2007',
 'co2_2008',
 'co2_2009',
 'co2_2010',
 'co2_2011',
 'co2_2012',
 'co2_2013',
 'co2_2014',
 'co2_2015',
 'co2_2016',
 'co2_2017',
 'co2_2018',
 'co2_2019',
 'co2_2020',
 'co2_2021',
 'co2_2022',
 '2023_y']

In [60]:
#final2.sort_values('endop')

In [61]:
final4

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,...,co2_2013,co2_2014,co2_2015,co2_2016,co2_2017,co2_2018,co2_2019,co2_2020,co2_2021,co2_2022
0,NW100-0248923,Neurath F,Nordrhein-Westfalen,Braunkohle,Ja,2012,1972,4211.000,in Betrieb,7,...,3.330000e+10,3.240000e+10,3.210000e+10,3.130000e+10,2.990000e+10,3.220000e+10,2.260000e+10,1.870000e+10,2.210000e+10,2.420000e+10
1,SN70015796,Boxberg Block N,Sachsen,Braunkohle,NaN,2012,1979,2470.000,in Betrieb,4,...,1.920000e+10,1.870000e+10,1.950000e+10,1.860000e+10,1.910000e+10,1.910000e+10,1.870000e+10,1.540000e+10,1.560000e+10,1.910000e+10
2,BB45025564,Kraftwerk Jänschwalde Block A,Brandenburg,Braunkohle,Ja,1989,1981,3000.000,in Betrieb,6,...,2.570000e+10,2.450000e+10,2.370000e+10,2.410000e+10,2.400000e+10,2.310000e+10,1.790000e+10,1.390000e+10,1.540000e+10,1.550000e+10
3,BB45025611,Kraftwerk Schwarze Pumpe Block A,Brandenburg,Braunkohle,NaN,1998,1997,1510.000,in Betrieb,2,...,1.140000e+10,1.170000e+10,1.230000e+10,1.230000e+10,1.150000e+10,1.250000e+10,1.060000e+10,1.040000e+10,1.190000e+10,9.640000e+09
4,NW300-0877384,Weisweiler,Nordrhein-Westfalen,Braunkohle,Ja,2006,1955,2619.000,in Betrieb,8,...,1.880000e+10,1.880000e+10,1.830000e+10,1.890000e+10,1.910000e+10,1.690000e+10,1.340000e+10,1.160000e+10,1.460000e+10,1.500000e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,HE30000163,IPH Strom GT4,Hessen,Erdgas,NaN,2022,1956,426.118,in Betrieb,11,...,1.190000e+09,1.160000e+09,1.150000e+09,1.240000e+09,1.140000e+09,1.210000e+09,1.070000e+09,8.610000e+08,9.580000e+08,9.470000e+08
257,NW300-9046797,LEV KWG G02,Nordrhein-Westfalen,Steinkohle,NaN,1999,1955,128.000,in Betrieb,8,...,8.930000e+08,8.360000e+08,8.260000e+08,8.030000e+08,7.930000e+08,7.320000e+08,7.430000e+08,6.750000e+08,8.230000e+08,7.950000e+08
258,BYS00334,Turbine 2,Bayern,Erdgas,NaN,2014,1952,54.795,in Betrieb,4,...,1.590000e+08,1.570000e+08,1.530000e+08,1.510000e+08,1.600000e+08,1.460000e+08,1.270000e+08,1.350000e+08,1.380000e+08,1.160000e+08
259,NW100-0990908,T/G 15,Nordrhein-Westfalen,Erdgas,Ja,1996,1949,48.525,in Betrieb,4,...,1.800000e+08,1.850000e+08,1.710000e+08,1.780000e+08,1.810000e+08,1.800000e+08,1.820000e+08,1.570000e+08,1.710000e+08,1.520000e+08
260,RP5000031,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,NaN,1900,1900,59.800,in Betrieb,1,...,1.610000e+08,1.420000e+08,1.480000e+08,1.320000e+08,1.330000e+08,1.240000e+08,1.260000e+08,1.070000e+08,1.170000e+08,1.030000e+08