In [74]:
import numpy as np
import pandas as pd

In [75]:
#pl0

In [76]:
bpm = pd.read_csv("plant_sse_mapper.csv")
pl0 = pd.read_excel("../data/Kraftwerksliste.xlsx", skiprows=11)



pl1 = pl0.loc[np.logical_or(pl0.Energieträger == "Kernenergie", np.logical_or(pl0.Energieträger == "Erdgas", np.logical_or(pl0.Energieträger == "Steinkohle", np.logical_or(pl0.Energieträger == "Braunkohle", pl0.Energieträger == "Mineralölprodukte")))), :]
pl2 = pl1.rename(columns={ pl1.columns[1]: "sseid"})
pl3 = bpm.merge(pl2, how="outer", on="sseid")
pl4 = pl3.loc[pl3['plantid'].isnull()]


#pl4[test] = pl4[test].apply(lambda x: x.replace(",", "."))
#pl4[test] = pd.to_numeric(pl4[test])

In [77]:
test = "Netto-Nennleistung (elektrische Wirkleistung) in MW"

In [78]:
#pl5 = pl4.loc[pl4[test]]

In [79]:
pl4.loc[pl4['Energieträger'] == "Braunkohle"].sort_values("Bundesland der Einheit")

,plantid,sseid,Unnamed: 0,Anlagenbetreiber,Anzeige-Name der Stromerzeugungseinheit,PLZ der Einheit,Ort der Einheit,Straße der Einheit,Hausnummer der Einheit,Bundesland der Einheit,...,Auswertung Energieträger,Wärmeauskopplung (KWK)\n(ja/nein),Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?,Bruttoleistung in MW,Nettonennleistung (elektrische Wirkleistung) in MW,Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?: ja \nNettonennleistung der Einspeisung in ein deutsches Netz:,Technologie der Stromerzeugung,Volleinspeisung oder Teileinspeisung?,Anschlussnetzbetreiber,Spannungsebene
112,NaN,SEE9-Dummy-nicht_EEG,NaN,Nicht-EEG-Anlagen < 10 MW,NaN,NaN,NaN,NaN,NaN,ohne Zuordnung,...,Braunkohle,NaN,NaN,50.0,50.0,NaN,NaN,NaN,NaN,NaN

In [80]:
pl4.groupby("Energieträger").count()

,plantid,sseid,Unnamed: 0,Anlagenbetreiber,Anzeige-Name der Stromerzeugungseinheit,PLZ der Einheit,Ort der Einheit,Straße der Einheit,Hausnummer der Einheit,Bundesland der Einheit,...,Auswertung Energieträger,Wärmeauskopplung (KWK)\n(ja/nein),Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?,Bruttoleistung in MW,Nettonennleistung (elektrische Wirkleistung) in MW,Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?: ja \nNettonennleistung der Einspeisung in ein deutsches Netz:,Technologie der Stromerzeugung,Volleinspeisung oder Teileinspeisung?,Anschlussnetzbetreiber,Spannungsebene
Energieträger,,,,,,,,,,,,,,,,,,,,,
Braunkohle,0,1,0,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,0,0,0
Erdgas,0,206,0,206,205,205,205,200,199,206,...,206,205,205,206,206,0,205,198,205,205
Mineralölprodukte,0,16,0,16,15,15,15,15,15,16,...,16,15,15,16,16,0,15,15,15,15
Steinkohle,0,1,0,1,0,0,0,0,0,1,...,1,0,0,1,1,0,0,0,0,0

In [81]:
pl5 = pl4.sort_values("PLZ der Einheit")

In [82]:
pl5.to_csv("no_plantid.csv", index=False)