In [1]:
import pandas as pd

In [28]:
df = pd.read_csv("plant_sse_mapper.csv")
inspr = pd.read_csv("inspire_prtr_mapper_old.csv")

In [29]:
df2 = df.sort_values("plantid", ascending=False)

In [30]:
df3 = df2[0:203]

In [31]:
df3["plantid_new"] = df3["plantid"].apply(lambda x: "SD" + str(x))

/tmp/ipykernel_3335953/527706781.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["plantid_new"] = df3["plantid"].apply(lambda x: "SD" + str(x))

In [40]:
df4 = df3[["plantid_new", "plantid", "sseid"]]
df5 = df4.rename(columns={"plantid_new": "InspireID_Betrieb", "plantid": "PRTR_Kennnummer"})

In [41]:
inspr

          InspireID_Betrieb       PRTR_Kennnummer            sseid
0          06-02-B10117A007      06-02-B10117A007  SEE987197130805
1          06-02-B10117A007      06-02-B10117A007  SEE913896693631
2         06-05-100-0030723     06-05-100-0030723          BNA1084
3         06-05-100-0431554     06-05-100-0431554          BNA0992
4         06-05-100-0431554     06-05-100-0431554          BNA0991
..                      ...                   ...              ...
888              TH72012874     16-72-73595430000  SEE969004747543
889              TH72012874     16-72-73595430000  SEE951160693116
890              TH86012942     16-86-00300070000  SEE925388069183
891              TH86012942     16-86-00300070000  SEE962906846994
892  HB06-04-11/2000122/0/0  06-04-11/2001178/8/2  SEE989202977269

[893 rows x 3 columns]

In [42]:
df5

    InspireID_Betrieb PRTR_Kennnummer            sseid
764          SD669-01          669-01  SEE950675787617
739          SD669-01          669-01  SEE983645175053
573          SD666-18          666-18  SEE985577062814
584          SD666-17          666-17  SEE944567587799
586          SD666-16          666-16  SEE943690268513
..                ...             ...              ...
57          SD661-101         661-101  SEE964073339897
493         SD661-100         661-100  SEE918407219966
495         SD661-100         661-100  SEE970401548961
839          SD661-09          661-09          BNA0099
695          SD661-06          661-06  SEE974201537415

[203 rows x 3 columns]

In [43]:
final = pd.concat([inspr, df5])

In [47]:
#final.to_csv("inspire_prtr_mapper.csv", index=False)