In [1]:
import pandas as pd
from scipy import stats
import numpy as np
from pandas.api.types import CategoricalDtype
import re
from helpers import get_renamed_blocks, get_renamed_blocks3

In [2]:
pd.options.mode.chained_assignment = None  # default='warn'

In [3]:
prtr = pd.read_excel("../data/2023-12-08_PRTR-Deutschland_Freisetzungen.xlsx")

In [4]:
#STATES = ['in Betrieb', 'Gesetzlich an Stilllegung gehindert', 'Netzreserve',  'Sicherheitsbereitschaft', 'Sonderfall', 'vorläufig stillgelegt', 'stillgelegt', 'Kohlestromvermarktungsverbot']
STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
ACTIVE_STATES = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt']
ENERGIES = ["Kernenergie", "Braunkohle", "Steinkohle", "Erdgas", "Mineralölprodukte", "Abfall", "Biomasse", ""]

In [5]:
plr = pd.read_excel("../data/Kraftwerksliste_2024.xlsx", sheet_name=1, skiprows=9)

In [6]:
pl0 = pd.read_excel("../data/Kraftwerksliste_2024.xlsx", skiprows=10)

In [7]:
#list(plr)

In [8]:
#list(pl0_bak)

In [9]:
pl0_bak = pl0.copy()
plr_bak = plr.copy()

In [10]:
list(pl0_bak)

['MaStR-Nr. der Stromerzeugungseinheit',
 'Anlagenbetreiber',
 'Anzeige-Name der Stromerzeugungseinheit',
 'PLZ der Einheit',
 'Ort der Einheit',
 'Straße der Einheit',
 'Hausnummer der Einheit',
 'Bundesland der Einheit',
 'Datum der erstmaligen Inbetriebnahme der Einheit',
 'Jahr der Inbetriebnahme der Einheit',
 'Kraftwerksstatus der Einheit',
 'Energieträger',
 'Hauptbrennstoff',
 'Auswertung Energieträger',
 'Wärmeauskopplung (KWK)\n(ja/nein)',
 'Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?',
 'Bruttoleistung in MW',
 'Nettonennleistung (elektrische Wirkleistung) in MW',
 'Ist die Stromerzeugungseinheit ein Bestandteil eines Grenzkraftwerkes?: ja \nNettonennleistung der Einspeisung in ein deutsches Netz:',
 'Technologie der Stromerzeugung',
 'Volleinspeisung oder Teileinspeisung?',
 'Anschlussnetzbetreiber',
 'Spannungsebene']

In [11]:
list(plr_bak)

['MaStR-Nr. der Stromerzeugungseinheit',
 'Anzeige-Name der Stromerzeugungseinheit',
 'PLZ der Einheit',
 'Ort der Einheit',
 'Straße der Einheit',
 'Hausnummer der Einheit',
 'Bundesland der Einheit',
 'Datum der erstmaligen Inbetriebnahme der Einheit (Datum/Jahr)',
 'Datum der endgültigen Stilllegung der Einheit (Datum/Jahr)',
 'Kraftwerksstatus der Einheit',
 'Energieträger',
 'Hauptbrennstoff',
 'Auswertung Energieträger',
 'Wärmeauskopplung (KWK)\n(ja/nein)',
 'Bruttoleistung in MW',
 'Nettonennleistung (elektrische Wirkleistung) in MW',
 'Technologie der Stromerzeugung',
 'Volleinspeisung oder Teileinspeisung?',
 'Anschlussnetzbetreiber',
 'Spannungsebene',
 'Unnamed: 20']

In [12]:
cols = [9,11,12,15,16,18,19,20]
plt = get_renamed_blocks(pl0)
plq = plt.drop(plt.columns[cols],axis=1)

In [13]:
cols2 = [10,11,14,16,17,20]
plr0a = get_renamed_blocks3(plr)
plr0b = plr0a.drop(plr0a.columns[cols2],axis=1)

In [14]:
list(plq)

['blockid',
 'company',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'state',
 'energysource',
 'chp',
 'power',
 'TSO',
 'voltagelevel']

In [15]:
list(plr0b)

['blockid',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'endop',
 'state',
 'energysource',
 'chp',
 'power',
 'TSO',
 'voltagelevel']

In [16]:
plq0a = plq[~plq['blockid'].isin(["SEE9-Dummy-nicht_EEG", "SEE9-Dummy-EEG"])]

In [17]:
plq0b = plq0a.sort_values(['power'], ascending=False)

In [18]:
#plq0b.groupby("energysource").count()

In [19]:
#plq0b.loc[pl0.energysource == "Abfall"]

In [141]:
#pl0 = pd.read_csv("../Kraftwerksliste_2020.csv", error_bad_lines=False, engine="python", encoding="latin1", sep=";", skiprows=9)
#prtr = pd.read_csv("../data/2019-11-25_PRTR-Deutschland_Freisetzungen.csv", error_bad_lines=False, engine="python", encoding="latin1", sep=";", skiprows=0)
#pl0 = pd.read_csv("Kraftwerksliste_CSV.csv", error_bad_lines=False, engine="python")
bm = pd.read_csv("../basic/plant_sse_mapper.csv", engine="python")

In [21]:
#bm

In [22]:
bm['plantid'] = bm['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [22]:
bm.loc[bm.plantid.str.contains("_")]

                  plantid            sseid
114  06-04-11_2001178_8_0          BNA0140
115  06-04-11_2001178_8_0  SEE968950464368
116  06-04-11_2001178_8_1  SEE958310939391
117  06-04-11_2001178_8_1          BNA0146
118  06-04-11_2001178_8_1          BNA0145
119  06-04-11_2001178_8_2          BNA0143
120  06-04-11_2001178_8_2  SEE989202977269
121  06-04-11_2001178_8_2  SEE924172977710
122  06-04-11_2039669_2_0  SEE904968236689

In [23]:
#prtr.describe()

In [23]:
plq0a.insert(10, "endop", np.nan)
plr0b.insert(2, "company", np.nan)

In [24]:
plq0a.shape

(1861, 16)

In [25]:
plr0b.shape

(262, 16)

In [26]:
pl_combined = pd.concat([plq0a, plr0b])

In [27]:
pl_combined['energysource'] = pl_combined['energysource'].apply(lambda x: str(x).replace('Wärme', 'Erdgas'))

In [28]:
pl_combined.loc[pl_combined.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,Endgültig Stillgelegt 2012 (ohne StA),2012,Braunkohle,Nein,125.0,Amprion GmbH,Höchstspannung (HöS)

In [69]:
pl_combined.shape

(2123, 16)

In [70]:
#list(plq0a)

In [71]:
#list(plr0b)

In [72]:
#list(pl_combined)

In [73]:
#list(plr0b)

In [74]:
#list(plq0a)

In [75]:
pl0 = pl_combined.copy()

In [76]:
pl0.loc[pl0["blockid"] == "BNA0645"]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, state, endop, energysource, chp, power, TSO, voltagelevel]
Index: []

In [77]:
#pl0.groupby("energysource").count()

In [78]:
#pl0.groupby("state").count()

In [79]:
pl1 = pl0.loc[pl0["energysource"].isin(ENERGIES)]

In [80]:
#pl0.loc[pl0.energysource == "Wärme"]

In [81]:
pl_debug = pl0.copy()
pl_debug['initialop'] = pd.to_datetime(pl_debug['initialop'], errors='coerce')
pl_debug2 = pl_debug.copy()

In [82]:
pl_debug2.loc[pl_debug2.initialop == pd.NaT ]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, state, endop, energysource, chp, power, TSO, voltagelevel]
Index: []

In [83]:
pl_debug2['initialop'] = pd.DatetimeIndex(pl_debug2.initialop).year
#pl_debug2['initialop'] = pl_debug.initialop.dt.year

In [84]:
#pl_debug2['initialop'] = pl_debug.initialop.dt.year

In [85]:
#pl_debug['initialop'] = pl_debug['initialop'].to_datetime()

In [86]:
pl_debug2.groupby("initialop").count()

,blockid,company,plantname,plz,place,street,streetnum,federalstate,state,endop,energysource,chp,power,TSO,voltagelevel
initialop,,,,,,,,,,,,,,,
1900.0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1
1905.0,2,2,2,2,2,2,0,2,2,0,2,2,2,2,2
1912.0,5,5,5,5,5,5,0,5,5,0,5,5,5,5,5
1915.0,2,2,2,2,2,2,0,2,2,0,2,2,2,2,2
1918.0,7,7,7,7,7,7,7,7,7,0,7,7,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020.0,31,31,31,31,31,30,29,31,31,0,31,31,31,31,31
2021.0,40,40,40,40,40,39,39,40,40,0,40,40,40,40,40
2022.0,87,87,87,87,87,74,73,87,87,0,87,87,87,87,87
2023.0,65,65,65,65,65,46,44,65,65,0,65,65,65,65,65
2024.0,11,11,11,11,11,11,10,11,11,0,11,11,11,11,11

In [87]:
#pl0.rename(columns={ pl0.columns[10]: "Energieträger_old", pl0.columns[13]: "Energieträger"}, inplace=True)

In [88]:
#pl0

In [89]:
#bm

In [90]:
#pl0.groupby("Energieträger").count()

In [91]:
#list(plt)

In [92]:
pl1

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
0,SEE915851127786,Stadtwerke Aachen AG,BHKW Schwarzer Weg,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,2023-04-05 00:00:00,In Betrieb,NaN,Erdgas,Ja,21.505,Regionetz GmbH (SNB911641710114),Mittelspannung
1,SEE946736241334,Palm Power GmbH & Co. KG,HKW Aalen,73432,Aalen,Palm Allee,1,Baden-Württemberg,2021-11-03 00:00:00,In Betrieb,NaN,Erdgas,Ja,78.302,Netze BW GmbH (SNB948311994307),Hochspannung; Hochspannung
2,SEE930596800480,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT A,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990-12-22 00:00:00,Kapazitätsreserve aufgrund von § 13e EnWG,NaN,Erdgas,Nein,37.104,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
3,SEE929797382345,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT B,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1990-12-10 00:00:00,Kapazitätsreserve aufgrund von § 13e EnWG,NaN,Erdgas,Nein,37.104,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
4,SEE988046628214,Lausitz Energie Kraftwerke AG,Gasturbinenkraftwerk Ahrensfelde GT C,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,1991-03-26 00:00:00,Kapazitätsreserve aufgrund von § 13e EnWG,NaN,Erdgas,Nein,37.104,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,SEE993836152862,NaN,"Kraftwerk I, KT7",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1941-11-04 00:00:00,endgültig stillgelegt 2024 (nach KVBG),2024-04-01 00:00:00,Steinkohle,Ja,17.572,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
258,SEE938923083674,NaN,"Kraftwerk I, T14",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1971-06-01 00:00:00,endgültig stillgelegt 2024 (nach KVBG),2024-04-01 00:00:00,Steinkohle,Ja,55.560,CPM Netz GmbH (SNB956923775696),Hochspannung
259,SEE985047526785,NaN,Kraftwerk Jänschwalde Block E,3185.0,Teichland,Am Kraftwerk,NaN,Brandenburg,1987-10-06 00:00:00,endgültig stillgelegt 2024 (ohne § 13b EnWG od...,2024-04-01 00:00:00,Braunkohle,Ja,500.000,50Hertz Transmission GmbH (SNB982046657236),Höchstspannung
260,SEE964729462818,NaN,Kraftwerk Jänschwalde Block F,3185.0,Teichland,Am Kraftwerk,NaN,Brandenburg,1989-03-09 00:00:00,endgültig stillgelegt 2024 (ohne § 13b EnWG od...,2024-04-01 00:00:00,Braunkohle,Ja,500.000,50Hertz Transmission GmbH (SNB982046657236),Höchstspannung
261,SEE985331675700,NaN,HKW Magirusstraße,89077.0,Ulm,Magirusstraße,21,Baden-Württemberg,1992-11-09 00:00:00,endgültig stillgelegt 2024 (nach KVBG),2024-04-01 00:00:00,Steinkohle,Ja,12.600,Stadtwerke Ulm/Neu-Ulm Netze GmbH (SNB93406863...,Mittelspannung

In [53]:
pl1.loc[pl1.blockid == "BNA0221c"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
108,BNA0221c,NaN,Gasblock,40221.0,Düsseldorf,Auf der Lausward,75,Nordrhein-Westfalen,1977-03-28 00:00:00,Endgültig Stillgelegt 2019 (mit StA),2019,Erdgas,Ja,293.0,Netzgesellschaft Düsseldorf mbH,Hochspannung (HS)

In [54]:
plt.loc[plt.blockid == "BNA0711"]

Empty DataFrame
Columns: [blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, Jahr der Inbetriebnahme der Einheit, state, e1, e2, energysource, chp, border, grosspower, power, gerpower, tech, fullsupply, TSO, voltagelevel]
Index: []

[0 rows x 23 columns]

In [55]:
plt = pl1.dropna(subset=["blockid"])

In [56]:
plt = plt.astype({"energysource": 'category'})

In [210]:
plt.loc[plt.blockid == "BNA0711"]

,blockid,bnaid,company,plantname,plz,place,street,streetnum,federalstate,initialop,endop,state,energysource,chp,power,tech
8,BNA0711,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1963,2012,Endgültig Stillgelegt 2012 (ohne StA),Braunkohle,Nein,125.0,NaN

In [57]:
# remove duplicates blocks in berlin, TODO: remove, because BNetzA switched to SEE ids no longer neccessary
#idxs = plt.index[plt["blockid"].isin(["BNA0083", "BNA0085b"]) & ~plt["state"].isin(["in Betrieb"])].tolist()
#plt2 = plt.loc[~plt.index.isin(idxs)]

In [58]:
#plt.loc[plt.index.isin(idxs)]#

In [59]:
#plt["Energieträger"] = plt["Energieträger"].astype('category')
#plt["Energieträger"] = plt["Energieträger"].cat.set_categories(["Kernenergie", "Braunkohle", "Steinkohle", "Erdgas", "Mineralölprodukte"], ordered=True)

In [60]:
#plt["Energieträger"] = plt["Energieträger"].astype('category')

In [61]:
#plt.groupby('Energieträger').count()

In [93]:
pl2 = pl1.copy()

In [94]:
#pl2.groupby("Energieträger").count()

In [95]:
# plt.dtypes

In [96]:
#pl2 = plt.rename(columns={ pl1.columns[0]: "blockid", pl1.columns[3]: "PLZ", pl1.columns[4]: "Ort", pl1.columns[8]: "Inbetriebnahme", pl1.columns[9]: "Status", pl1.columns[15]: "KWK", pl1.columns[16]: "Nettoleistung"})
#pl3 = pl2.rename(columns={ pl1.columns[1]: "BlockID" })

In [97]:
'''
def to_year(x):
    if type(x) == type(4):
        return x
    elif type(x) == type(2.5):
        return 0 # handle nans
    return int(x[-4:])
'''

'\ndef to_year(x):\n    if type(x) == type(4):\n        return x\n    elif type(x) == type(2.5):\n        return 0 # handle nans\n    return int(x[-4:])\n'

In [98]:
def to_year(x):
    dt = pd.to_datetime(x)
    return dt.year

In [99]:
#blocks.loc[blocks.Energieträger == "Kernenergie"]

In [100]:
#pl2

In [101]:
'''
pl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012
pl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002
pl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970
pl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951
pl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990
pl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953
pl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013
pl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006
pl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012



pl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D

pl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld
'''

#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace('\n','')
#pl2['Nettoleistung'] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
#pl2['Nettoleistung'] = pl2['Nettoleistung'].str.replace(';','.')

"\npl2.loc[pl2.blockid == 'BNA0861a', 'initialop'] = 2012\npl2.loc[pl2.blockid == 'BNA1334', 'initialop'] = 2002\npl2.loc[pl2.blockid == 'BNA1141', 'initialop'] = 1970\npl2.loc[pl2.blockid == 'BNA0418', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1499', 'initialop'] = 1951\npl2.loc[pl2.blockid == 'BNA1502', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1500', 'initialop'] = 1990\npl2.loc[pl2.blockid == 'BNA1498', 'initialop'] = 1953\npl2.loc[pl2.blockid == 'BNA1260', 'initialop'] = 2013\npl2.loc[pl2.blockid == 'BNA1056', 'initialop'] = 2006\npl2.loc[pl2.blockid == 'BNA1114', 'initialop'] = 2012\n\n\n\npl2.loc[pl2.blockid == 'BNA0413b', 'initialop'] = 2014 # Westfalen D\n\npl2.loc[pl2.blockid == 'BNA0355', 'initialop'] = 1981 # Grafenrheinfeld\n"

In [102]:
#pl2[] = pl2[pd.to_numeric(pl2["Nettoleistung"])]
pl2['initialop'] = pl2['initialop'].apply(to_year)
#pl2['endop'] = pl2['endop'].apply(to_year)
pl2['power'] = pl2['power'].apply(pd.to_numeric)

In [103]:
pl2.loc[pl2.blockid == "BNA0711"]

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
8,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1970.0,Endgültig Stillgelegt 2012 (ohne StA),2012,Braunkohle,Nein,125.0,Amprion GmbH,Höchstspannung (HöS)

In [104]:
#bm[pl2.duplicated(['BlockID'], keep=False)].sort_values("BlockID", ascending=False)

In [105]:
#pl2[pl2.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [106]:
#cols = [10,11,12,14,17,18,19]
#pl3 = pl2.drop(pl2.columns[cols],axis=1)

In [107]:
#pl3.groupby('Unternehmen').max()

In [108]:
#pl3

In [109]:
def fix_company(company):
    #print(company)
    company_dict = {"RWE": "RWE AG", "Vattenfall": "Vattenfall GmbH", "Uniper": "Uniper SE", "EnBW": "EnBW AG", "Steag": "Steag GmbH", "Nordzucker": "Nordzucker AG", "Lausitz Energie": "LEAG"}
    for key, value in company_dict.items():
        if key in str(company):
            return value
    return company

In [110]:
def extract_still(x):
    match = re.findall("[0-9]{4}",x)
    return match[0] if match else np.nan

In [111]:
def fix_kwk(x):
    return "Nein" if x == "nein" else "Ja" if x == "ja" else x

In [112]:
pl4 = pl2.copy()

In [113]:
sq = 'Endgültig Stillgelegt 2013 (mit StA)'

In [114]:
list(pl2.groupby("state").count().reset_index()['state'])

['Endgültig Stillgelegt 2011 (ohne StA)',
 'Endgültig Stillgelegt 2012 (ohne StA)',
 'Endgültig Stillgelegt 2013 (mit StA)',
 'Endgültig Stillgelegt 2013 (ohne StA)',
 'Endgültig Stillgelegt 2014 (mit StA)',
 'Endgültig Stillgelegt 2014 (ohne StA)',
 'Endgültig Stillgelegt 2015 (mit StA)',
 'Endgültig Stillgelegt 2015 (ohne StA)',
 'Endgültig Stillgelegt 2016 (mit StA)',
 'Endgültig Stillgelegt 2016 (ohne StA)',
 'Endgültig Stillgelegt 2017 (mit StA)',
 'Endgültig Stillgelegt 2017 (ohne StA)',
 'Endgültig Stillgelegt 2018 (mit StA)',
 'Endgültig Stillgelegt 2018 (ohne StA)',
 'Endgültig Stillgelegt 2019 (mit StA)',
 'Endgültig Stillgelegt 2019 (ohne StA)',
 'In Betrieb',
 'Kapazitätsreserve aufgrund von § 13e EnWG',
 'Netzreserve aufgrund von KVBG',
 'Netzreserve aufgrund § 13b EnWG',
 'besonderes netztechnisches Betriebsmittel',
 'endgültig stillgelegt 2017 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2018 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2020 (nach KVBG)',
 'endgültig stillgelegt 2020 (nach § 13b EnWG)',
 'endgültig stillgelegt 2020 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2021 (nach KVBG)',
 'endgültig stillgelegt 2021 (nach § 13b EnWG)',
 'endgültig stillgelegt 2021 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2022 (nach KVBG)',
 'endgültig stillgelegt 2022 (nach § 13b EnWG)',
 'endgültig stillgelegt 2022 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2023 (nach KVBG)',
 'endgültig stillgelegt 2023 (nach § 13b EnWG)',
 'endgültig stillgelegt 2023 (ohne § 13b EnWG oder KVBG)',
 'endgültig stillgelegt 2024 (nach KVBG)',
 'endgültig stillgelegt 2024 (nach § 13b EnWG)',
 'endgültig stillgelegt 2024 (ohne § 13b EnWG oder KVBG)',
 'in Betrieb',
 'vorläufig stillgelegt nach § 13b EnWG',
 'vorläufig stillgelegt ohne § 13b EnWG']

In [115]:
z = "endgültig stillgelegt 2022 (ohne § 13b EnWG oder KVBG)"

In [116]:
def extract_state(state):
    if state == "In Betrieb":
        return "in Betrieb"
    elif "Endgültig Stillgelegt" in state:
        return "stillgelegt"
    elif "Vorläufig Stillgelegt" in state:
        return "vorläufig stillgelegt"
    elif "an Stilllegung gehindert" in state:
        return "Gesetzlich an Stilllegung gehindert"
    else:
        return state

In [117]:
def extract_state2(state):
    
    states = ['in Betrieb', 'Kapazitätsreserve', 'Netzreserve', 'Strommarktrückkehr', 'vorläufig stillgelegt', 'stillgelegt §13b EnWG', 'stillgelegt KVBG', 'stillgelegt']
    matches = ['In Betrieb', 'Kapazitätsreserve aufgrund von § 13e EnWG', 'Netzreserve aufgrund § 13b EnWG', 'befristete Strommarktrückkehr', 'vorläufig stillgelegt', 'endgültig stillgelegt 20[0-9]{2} \(nach § 13b EnWG\)', 'endgültig stillgelegt 20[0-9]{2} \(nach KVBG\)', '[E|e]ndgültig [S|s]tillgelegt 20[0-9]{2} \([ohne]|[mit].']
    
    for s, m in list(zip(states, matches)):
        if re.search(m, state):
            return s
    
    return state

In [118]:
extract_state2(sq)

'stillgelegt'

In [119]:
pl4['company'] = pl4['company'].apply(lambda x: fix_company(x))
#pl4['endop'] = pl4['state'].apply(lambda x: extract_still(x))
pl4['state'] = pl4['state'].apply(lambda x: extract_state2(x))
pl4['chp'] = pl4['chp'].apply(lambda x: fix_kwk(x))

In [120]:
list(pl4.groupby("state").count().reset_index()['state'])

['Kapazitätsreserve',
 'Netzreserve',
 'in Betrieb',
 'stillgelegt',
 'stillgelegt KVBG',
 'stillgelegt §13b EnWG',
 'vorläufig stillgelegt']

In [121]:
atest = pl4.groupby("state").count()

In [122]:
def myf():
    return 0 if "test" == "test" else 1

In [123]:
atest

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,endop,energysource,chp,power,TSO,voltagelevel
state,,,,,,,,,,,,,,,
Kapazitätsreserve,15,15,15,15,15,15,14,15,15,0,15,15,15,15,15
Netzreserve,24,24,24,24,24,24,23,24,24,0,24,24,24,24,24
in Betrieb,1233,1233,1233,1233,1233,1157,1134,1233,1233,0,1233,1233,1233,1233,1233
stillgelegt,196,17,193,196,196,132,115,196,195,179,196,195,196,154,186
stillgelegt KVBG,33,0,33,32,33,31,29,33,33,33,33,33,33,19,30
stillgelegt §13b EnWG,28,0,28,28,28,28,28,28,28,28,28,28,28,12,24
vorläufig stillgelegt,16,16,16,16,16,16,15,16,16,0,16,16,16,16,16

In [124]:
newdf = pl4.copy()

In [125]:
#newdf.dtypes

In [126]:
newdf["state"] = newdf["state"].astype('category')
newdf["state"] = newdf["state"].cat.set_categories(STATES, ordered=True)

In [127]:
newdf["chp"] = newdf["chp"].astype('category')
newdf["chp"] = newdf["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)

In [128]:
#list(atest.reset_index()['state'])

In [129]:
#newdf.groupby("energysource").count()

In [130]:
atest

,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,endop,energysource,chp,power,TSO,voltagelevel
state,,,,,,,,,,,,,,,
Kapazitätsreserve,15,15,15,15,15,15,14,15,15,0,15,15,15,15,15
Netzreserve,24,24,24,24,24,24,23,24,24,0,24,24,24,24,24
in Betrieb,1233,1233,1233,1233,1233,1157,1134,1233,1233,0,1233,1233,1233,1233,1233
stillgelegt,196,17,193,196,196,132,115,196,195,179,196,195,196,154,186
stillgelegt KVBG,33,0,33,32,33,31,29,33,33,33,33,33,33,19,30
stillgelegt §13b EnWG,28,0,28,28,28,28,28,28,28,28,28,28,28,12,24
vorläufig stillgelegt,16,16,16,16,16,16,15,16,16,0,16,16,16,16,16

In [131]:
pl3 = newdf

In [132]:
atest = newdf.groupby(["power"]).count()
atest.sort_values("initialop", inplace=True, ascending=False)

In [133]:
#print(atest)

In [134]:
atest = pl3.groupby(["state"]).count()
# atest

C:\Users\dietz\AppData\Local\Temp\ipykernel_16288\4069360528.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  atest = pl3.groupby(["state"]).count()

In [135]:
# pl3.rename(columns={ pl3.columns[10]: "Energieträger"}, inplace=True)

In [136]:
#bm[bm.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

In [137]:
#bm2 = bm.drop_duplicates()

In [138]:
#pl3

In [140]:
bm

                 plantid          blockid
0         12-30532000000  SEE969511682320
1      06-05-900-0327252  SEE948351715917
2      14-80-55047380000  SEE986249505394
3      14-80-55047380000  SEE955310827123
4         12-30532000000  SEE939848582457
..                   ...              ...
936    06-05-300-9046797  SEE976489828827
937               664-07  SEE906830618081
938               664-02  SEE999977738880
939        07-05-8030815  SEE957723162266
940  06-09-661-0020-0001         BNA1337a

[941 rows x 2 columns]

In [142]:
pl4 = bm.merge(pl3, how="right", left_on="sseid", right_on="blockid")

In [143]:
pl4.sort_values(by=['plantid'])

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
312,01-50-01000004838,SEE999539592561,SEE999539592561,Stadtwerke Flensburg,Dampfturbine 12,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,2016.0,in Betrieb,NaN,Erdgas,Ja,27.200,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung
315,01-50-01000004838,SEE990438768378,SEE990438768378,Stadtwerke Flensburg,Dampfturbine 8,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,1985.0,in Betrieb,NaN,Steinkohle,Ja,32.900,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung
316,01-50-01000004838,SEE957285549260,SEE957285549260,Stadtwerke Flensburg,Dampfturbine 9,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,1988.0,in Betrieb,NaN,Steinkohle,Ja,32.900,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung
317,01-50-01000004838,SEE966920434281,SEE966920434281,Stadtwerke Flensburg,Gasturbine 12,24939,Flensburg,Batteriestraße,48,Schleswig-Holstein,2016.0,in Betrieb,NaN,Erdgas,Ja,50.100,Stadtwerke Flensburg GmbH (SNB922220582657),Mittelspannung
1318,01-50-01000004838,BNA0269,BNA0269,NaN,HKW Flensburg,24939.0,Flensburg,Batteriestr.,48,Schleswig-Holstein,1970.0,stillgelegt,2012,Mineralölprodukte,Ja,30.000,Stadtwerke Flensburg GmbH,Mittelspannung (MS)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,NaN,NaN,SEE901120268069,NaN,"Kraftwerk I, GT11",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1942.0,stillgelegt KVBG,2024-04-01 00:00:00,Steinkohle,Ja,18.400,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
1537,NaN,NaN,SEE953373967701,NaN,"Kraftwerk I, GT9",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1941.0,stillgelegt KVBG,2024-04-01 00:00:00,Steinkohle,Ja,15.750,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
1538,NaN,NaN,SEE952266131625,NaN,"Kraftwerk I, KT13",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1949.0,stillgelegt KVBG,2024-04-01 00:00:00,Steinkohle,Ja,20.514,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
1539,NaN,NaN,SEE991559435767,NaN,"Kraftwerk I, KT5",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1940.0,stillgelegt KVBG,2024-04-01 00:00:00,Steinkohle,Ja,15.638,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
1540,NaN,NaN,SEE993836152862,NaN,"Kraftwerk I, KT7",45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,1941.0,stillgelegt KVBG,2024-04-01 00:00:00,Steinkohle,Ja,17.572,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung

In [144]:
#pl4.sort_values(by=['power'], ascending=False)

In [145]:
#pl4.sort_values(by=['power'], ascending=False)

In [146]:
#pl4[pl4.duplicated(['BlocID'], keep=False)].sort_values("BlockID", ascending=False)

In [147]:
pl5 = pl4[pd.notnull(pl4['blockid'])]
#pl5 = pl4
pl5a = pl5[pd.notnull(pl5['power'])]

In [148]:
#pl4[pl4['plantid'].isnull()].sort_values(by=["power"])

In [149]:
#pl6['plantid'] = pl6['plantid'].apply(lambda x: str(x).replace('/', '_'))

In [150]:
# pl7 = pl6.replace("/", "_")

In [151]:
#pl7 = pl6.apply(str.replace("/", "_"))

In [152]:
#pl6.loc[pl6.Kraftwerksname == "KW Mittelsbüren"]

In [153]:
pl6 =  pl5a.copy() #[pd.notnull(pl5a['plantid'])]

In [154]:
pl6.dtypes

plantid           object
sseid             object
blockid           object
company           object
plantname         object
plz               object
place             object
street            object
streetnum         object
federalstate      object
initialop        float64
state           category
endop             object
energysource      object
chp             category
power            float64
TSO               object
voltagelevel      object
dtype: object

In [155]:
pl6.loc[pl6.blockid == "BNA0711"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
1313,06-05-300-0326774,BNA0711,BNA0711,NaN,Niederaußem,50129.0,Bergheim,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2012,Braunkohle,Nein,125.0,Amprion GmbH,Höchstspannung (HöS)

In [156]:
def to_year2(x):
    if pd.isna(x):
        return x
    elif isinstance(x, float):
        return x
    elif isinstance(x, int):
        return x
    else:
        ts = pd.Timestamp(ts_input=x)
        #print(ts)
        return int(ts.year)

In [157]:
pl6['initialop'] = pl6['initialop'].apply(pd.to_numeric)
pl6['endop'] = pl6['endop'].apply(lambda x: to_year2(x))

In [158]:
pl6.loc[pl6.blockid == "BNA0711"].dtypes

plantid           object
sseid             object
blockid           object
company           object
plantname         object
plz               object
place             object
street            object
streetnum         object
federalstate      object
initialop        float64
state           category
endop            float64
energysource      object
chp             category
power            float64
TSO               object
voltagelevel      object
dtype: object

In [159]:
pl6.loc[pl6.blockid == "SEE999977738880"]

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
1435,664-02,SEE999977738880,SEE999977738880,NaN,IKW Deuben,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,1936.0,stillgelegt KVBG,2021.0,Braunkohle,Ja,67.0,NaN,Hochspannung

In [160]:
blocks = pl6.copy()
stammdaten = pl6.copy()

In [161]:
#TODO: fill based on endop and state

In [162]:
blocks['state'] = blocks['state'].fillna(value='stillgelegt')

In [163]:
blocks.loc[blocks['state'].isnull()]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, state, endop, energysource, chp, power, TSO, voltagelevel]
Index: []

In [164]:
blocks.loc[blocks['state'] == 'stillgelegt'].sort_values(['endop'])

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
1305,06-05-100-0081105,BNA0302,BNA0302,NaN,Frimmersdorf,41517.0,Frimmersdorf,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2011.0,Braunkohle,Nein,129.0,Westnetz GmbH,Hochspannung (HS)
1306,06-05-100-0081105,BNA0303,BNA0303,NaN,Frimmersdorf,41517.0,Frimmersdorf,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2011.0,Braunkohle,Nein,130.0,Westnetz GmbH,Hochspannung (HS)
1307,06-05-100-0081105,BNA0304,BNA0304,NaN,Frimmersdorf,41517.0,Frimmersdorf,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2011.0,Braunkohle,Nein,124.0,Amprion GmbH,Höchstspannung (HöS)
1308,06-05-900-0079017,BNA0414,BNA0414,NaN,Westfalen,59071.0,Hamm-Uentrop,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2011.0,Steinkohle,Nein,152.0,Westnetz GmbH,Hochspannung (HS)
1309,06-05-900-0079017,BNA0415,BNA0415,NaN,Westfalen,59071.0,Hamm-Uentrop,NaN,NaN,Nordrhein-Westfalen,1970.0,stillgelegt,2011.0,Steinkohle,Nein,152.0,Westnetz GmbH,Hochspannung (HS)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,06-00176010435,SEE929161243203,SEE929161243203,Uniper SE,Staudinger 5,63538,Großkrotzenburg,Hanauer Landstraße,150,Hessen,1992.0,stillgelegt,NaN,Steinkohle,Ja,522.0,TenneT TSO GmbH (SNB970033313272),Höchstspannung
704,NaN,NaN,SEE916274994887,Gaskraftwerk Leipheim GmbH & Co. KG,bnBm Gaskraftwerk Leipheim,89340,Leipheim,Am Tower,5,Bayern,2023.0,stillgelegt,NaN,Erdgas,Nein,310.0,Amprion GmbH (SNB976890256486),Höchstspannung
924,06-09-500-0368-0001,SEE911764038249,SEE911764038249,Uniper SE,Franken DT1,90449,Nürnberg,Felsenstraße,14,Bayern,1973.0,stillgelegt,NaN,Erdgas,Ja,383.0,Bayernwerk Netz GmbH (SNB940352624434),Hochspannung
925,06-09-500-0368-0001,SEE922477386435,SEE922477386435,Uniper SE,Franken DT2,90449,Nürnberg,Felsenstraße,14,Bayern,1975.0,stillgelegt,NaN,Erdgas,Ja,387.0,Bayernwerk Netz GmbH (SNB940352624434),Hochspannung
1174,NaN,NaN,SEE915432109163,Uniper SE,Irsching 6,85088,Vohburg,Paarstraße,30,Bayern,2023.0,stillgelegt,NaN,Erdgas,Nein,300.0,TenneT TSO GmbH (SNB970033313272),Höchstspannung

In [165]:
blocks.sort_values("initialop", inplace=True, ascending=False)
# blocks

In [166]:
plants = blocks.copy()
plants = plants.dropna(subset=["plantid", "initialop"]) #TODO: remove initialop from here

In [167]:
#pl4[pl4.loc]
pl4.loc[pl4.plantid == "nan"]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, state, endop, energysource, chp, power, TSO, voltagelevel]
Index: []

In [168]:
plants.loc[plants.state == np.nan]

Empty DataFrame
Columns: [plantid, sseid, blockid, company, plantname, plz, place, street, streetnum, federalstate, initialop, state, endop, energysource, chp, power, TSO, voltagelevel]
Index: []

In [169]:
plants

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
140,03-01-01010157480,SEE920992144554,SEE920992144554,Braunschweiger Versorgungs-AG & Co. KG,HKW Mitte GuD BMHKW,38114,Braunschweig,Reiherstraße,3,Niedersachsen,2023.0,in Betrieb,NaN,Erdgas,Ja,98.100,Braunschweiger Netz GmbH (SNB926644622999),Hochspannung
708,14-80-55047380000,SEE986249505394,SEE986249505394,Stadtwerke Leipzig GmbH,Heizkraftwerk Leipzig Nord DT8C,4105,Leipzig,Eutritzscher Straße,14b,Sachsen,2022.0,in Betrieb,NaN,Erdgas,Ja,25.609,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Hochspannung
707,14-80-55047380000,SEE955310827123,SEE955310827123,Stadtwerke Leipzig GmbH,Heizkraftwerk Leipzig Nord DT8B,4105,Leipzig,Eutritzscher Straße,14b,Sachsen,2022.0,in Betrieb,NaN,Erdgas,Ja,25.249,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Hochspannung
349,12-30532000000,SEE939848582457,SEE939848582457,Stadtwerke Frankfurt (Oder) GmbH,HKW FFO GM5,15236,Frankfurt,Am Hohen Feld,4,Brandenburg,2022.0,in Betrieb,NaN,Erdgas,Ja,10.100,Netzgesellschaft Frankfurt (Oder) mbH (SNB9548...,Umspannebene Hochspannung/Mittelspannung
348,12-30532000000,SEE900549498521,SEE900549498521,Stadtwerke Frankfurt (Oder) GmbH,HKW FFO GM4,15236,Frankfurt,Am Hohen Feld,4,Brandenburg,2022.0,in Betrieb,NaN,Erdgas,Ja,10.100,Netzgesellschaft Frankfurt (Oder) mbH (SNB9548...,Umspannebene Hochspannung/Mittelspannung
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,06-09-676-2101-0002,SEE919296928137,SEE919296928137,Kraftwerk Obernburg,Sammelschienen-Kraftwerk Gas- und Dampfturbinen,63906,Erlenbach,Glanzstoffstr.,1,Bayern,1956.0,in Betrieb,NaN,Erdgas,Ja,112.719,Mainsite GmbH & Co. KG (SNB974647435931),Mittelspannung
728,06-05-300-9046797,SEE976489828827,SEE976489828827,Currenta GmbH & Co. OHG,LEV KWG G11,51373,Leverkusen,Kaiser-Wilhelm-Allee,80,Nordrhein-Westfalen,1955.0,in Betrieb,NaN,Steinkohle,Ja,19.235,NETCUR GmbH (SNB974711150357),Umspannebene Hochspannung/Mittelspannung
53,664-07,SEE906830618081,SEE906830618081,RWE AG,Fab Fortuna,50129,Bergheim,Auenheimer Straße,NaN,Nordrhein-Westfalen,1948.0,in Betrieb,NaN,Braunkohle,Ja,15.000,Amprion GmbH (SNB976890256486),Höchstspannung
1435,664-02,SEE999977738880,SEE999977738880,NaN,IKW Deuben,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,1936.0,stillgelegt KVBG,2021.0,Braunkohle,Ja,67.000,NaN,Hochspannung
541,07-05-8030815,SEE957723162266,SEE957723162266,SWK Stadtwerke Kaiserslautern Versorgungs-AG,HKW Karcherstraße,67655,Kaiserslautern,Karcherstraße,28,Rheinland-Pfalz,1900.0,in Betrieb,NaN,Erdgas,Ja,59.800,SWK Stadtwerke Kaiserslautern Versorgungs-AG (...,Mittelspannung; Mittelspannung

In [170]:
#plants_d = plants.loc[plants.duplicated("KraftwerkID", keep=False)]
# plants_d

In [171]:
#plants_c = plants_d.groupby(["KraftwerkID"]).sum()
#plants_count = plants_d.groupby(["KraftwerkID"]).count()

In [172]:
#plants_f = plants_c.reset_index()

In [173]:
#plants_count = plants_count.loc[:, ["blockid"]]

In [174]:
#plants_count = plants_count.reset_index()
# plants_count

In [175]:
#plants_f = plants_f.merge(plants_count, on="KraftwerkID", how="inner")
# plants_f

In [176]:
#plants[plants.duplicated(['KraftwerkID'], keep=False)].sort_values("BlockID", ascending=False)

In [177]:
plants["energysource"] = plants["energysource"].astype('category')
plants["energysource"] = plants["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants["state"] = plants["state"].astype('category')
plants["state"] = plants["state"].cat.set_categories(STATES, ordered=True)
plants["chp"] = plants["chp"].astype('category')
plants["chp"] = plants["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants["federalstate"] = plants["federalstate"].astype('category')
plants["federalstate"] = plants["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [178]:
pl1 = pl0.loc[pl0["energysource"].isin(["Kernenergie", "Erdgas", "Steinkohle", "Braunkohle", "Steinkohle"])]

In [179]:
p_grp = plants.groupby("plantid")

In [180]:
#plants.groupby("Energip_subgrper").max()

In [181]:
p_subgrp = plants.loc[plants['state'].isin(ACTIVE_STATES)].groupby('plantid') # TODO: add

In [183]:
plants_act = pd.DataFrame()
for plantid, group in p_subgrp:
    entry = {}
    entry["plantid"] = plantid
    entry["activepower"] = group["power"].sum()
    #plants_act = plants_act.append(entry, ignore_index=True)
    plants_act = pd.concat([plants_act, pd.DataFrame([entry])], ignore_index=True)

In [184]:
plants_act

               plantid  activepower
0    01-50-01000004838      143.100
1    01-50-04000082392       30.896
2    01-50-56050192711      253.000
3    03-01-01010157480      162.600
4    03-01-01010356620       10.400
..                 ...          ...
252             662-18       11.400
253             662-22       24.810
254             662-28       17.100
255             664-07       15.000
256             669-01      772.000

[257 rows x 2 columns]

In [677]:
#plants_act.sort_values('activepower', ascending=False)

In [678]:
#ap = plants.loc[plants.state == "in Betrieb" | plants.state == "Gesetzlich an Stilllegung gehindert"]

In [186]:
plants_a.dtypes

Series([], dtype: object)

In [187]:
plants_a = pd.DataFrame()
for plantid, group in p_grp:
    #if not plantid == "06-05-300-9046797":
    #    continue
    entry = {}
    #print(entry)
    entry["plantid"] = plantid
    # entry["BlockID"] = group
    try:
        entry["plantname"] = group["plantname"].value_counts().index[0]
    except IndexError:
        entry["plantname"] = np.NaN
    entry["federalstate"] = group["federalstate"].value_counts().index[0]
    entry["energysource"] = group["energysource"].min()
    try:
        entry["chp"] = group["chp"].min()
    except TypeError:
        #print("aneror")
        #print(plantid)
        #print(group['KWK'].count())
        entry["chp"] = ""
    entry["latestexpanded"] = group["initialop"].max()
    entry["initialop"] = group["initialop"].min()
    entry["totalpower"] = group["power"].sum()
    entry["state"] = group["state"].min()
    entry["blockcount"] = group["blockid"].count()
    try:
        entry["company"] = group["company"].value_counts().index[0]
    except IndexError:
        ;
    #print(entry)
    #break
    plants_a = pd.concat([plants_a, pd.DataFrame([entry])], ignore_index=True)

In [188]:
#plants_a

In [681]:
#TODO: fix this

In [682]:
#plants_a[pd.isnull(plants_a)]

In [190]:
int_list = ['blockcount', 'initialop', 'latestexpanded']
for column in int_list:
    plants_a[column] = plants_a[column].astype(int)
#plant['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)
#pl2['blockcount'] = pl2['blockcount'].apply(pd.to_numeric)

In [191]:
plants_a.dtypes

plantid            object
plantname          object
federalstate       object
energysource       object
chp                object
latestexpanded      int32
initialop           int32
totalpower        float64
state              object
blockcount          int32
company            object
dtype: object

In [192]:
plants_a["energysource"] = plants_a["energysource"].astype('category')
plants_a["energysource"] = plants_a["energysource"].cat.set_categories(ENERGIES, ordered=True)
plants_a["state"] = plants_a["state"].astype('category')
plants_a["state"] = plants_a["state"].cat.set_categories(STATES, ordered=True)
plants_a["chp"] = plants_a["chp"].astype('category')
plants_a["chp"] = plants_a["chp"].cat.set_categories(['Ja', 'Nein'], ordered=True)
plants_a["federalstate"] = plants_a["federalstate"].astype('category')
plants_a["federalstate"] = plants_a["federalstate"].cat.set_categories(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'])

In [193]:
plants_a.dtypes

plantid             object
plantname           object
federalstate      category
energysource      category
chp               category
latestexpanded       int32
initialop            int32
totalpower         float64
state             category
blockcount           int32
company             object
dtype: object

In [194]:
plants_a.loc[plants_a.plantid == "666-999"]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company]
Index: []

In [195]:
plants_a.loc[plants_a.plantid == "06-00176010435"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
35,06-00176010435,Staudinger,Hessen,Steinkohle,Ja,1992,1970,1644.0,Netzreserve,4,Uniper SE

In [196]:
plants_a.loc[plants_a.plantid == "06-05-900-0865327"]

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company
106,06-05-900-0865327,Gersteinwerk,Nordrhein-Westfalen,Steinkohle,Nein,1984,1972,2011.0,in Betrieb,9,RWE AG

In [197]:
#plants_a = plants.drop_duplicates(subset="KraftwerkID")

In [198]:
column_titles = ['plantid', 'plantname', 'federalstate','energysource', 'chp', 'latestexpanded', 'initialop', 'totalpower', 'state', 'blockcount', 'company']
plants_b = plants_a.reindex(columns=column_titles)

In [199]:
#plants_b

In [200]:
list(blocks)

['plantid',
 'sseid',
 'blockid',
 'company',
 'plantname',
 'plz',
 'place',
 'street',
 'streetnum',
 'federalstate',
 'initialop',
 'state',
 'endop',
 'energysource',
 'chp',
 'power',
 'TSO',
 'voltagelevel']

In [201]:
#blocks.drop(['place', 'plz', 'street'], axis=1, inplace=True)

In [202]:
blocks[blocks.duplicated(['blockid'], keep=False)].sort_values("blockid", ascending=False)

,plantid,sseid,blockid,company,plantname,plz,place,street,streetnum,federalstate,initialop,state,endop,energysource,chp,power,TSO,voltagelevel
797,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,in Betrieb,NaN,Erdgas,Nein,1.553,MVV Netze GmbH (SNB985472799266),Mittelspannung
796,NaN,NaN,SEE988996320985,Caterpillar Energy Solutions,P31,68167,Mannheim,Carl-Benz-Straße,1,Baden-Württemberg,1994.0,in Betrieb,NaN,Erdgas,Nein,1.553,MVV Netze GmbH (SNB985472799266),Mittelspannung
1499,NaN,NaN,SEE960058020569,NaN,Spitzenstromerzeuger 3 (Diesel 3 HKW-West),76189.0,Karlsruhe,Honsellstraße,35,Baden-Württemberg,1981.0,stillgelegt,2023.0,Mineralölprodukte,Nein,3.300,Stadtwerke Karlsruhe Netzservice GmbH (SNB9710...,Mittelspannung
1509,NaN,NaN,SEE960058020569,NaN,Spitzenstromerzeuger 3 (Diesel 3 HKW-West),76189.0,Karlsruhe,Honsellstraße,35,Baden-Württemberg,1981.0,stillgelegt,2023.0,Mineralölprodukte,Nein,3.300,NaN,Umspannebene Hochspannung/Mittelspannung
1515,661-95,SEE944995057840,SEE944995057840,NaN,Gasturbine,9648.0,Kriebstein,Bauhofstraße,1,Sachsen,1993.0,stillgelegt,2023.0,Erdgas,Ja,9.800,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Mittelspannung
1501,661-95,SEE944995057840,SEE944995057840,NaN,Gasturbine,9648.0,Kriebstein,Bauhofstraße,1,Sachsen,1993.0,stillgelegt,2023.0,Erdgas,Ja,9.800,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Mittelspannung
1500,NaN,NaN,SEE910806335483,NaN,Spitzenstromerzeuger 4 (Diesel 4 HKW-West),76189.0,Karlsruhe,Honsellstraße,35,Baden-Württemberg,1981.0,stillgelegt,2023.0,Mineralölprodukte,Nein,3.300,Stadtwerke Karlsruhe Netzservice GmbH (SNB9710...,Umspannebene Hochspannung/Mittelspannung
1510,NaN,NaN,SEE910806335483,NaN,Spitzenstromerzeuger 4 (Diesel 4 HKW-West),76189.0,Karlsruhe,Honsellstraße,35,Baden-Württemberg,1981.0,stillgelegt,2023.0,Mineralölprodukte,Nein,3.300,NaN,Umspannebene Hochspannung/Mittelspannung
1516,661-95,SEE906722372718,SEE906722372718,NaN,Gegendruckturbine 3 MW,9648.0,Kriebstein,Bauhofstraße,1,Sachsen,1993.0,stillgelegt,2023.0,Erdgas,Ja,2.975,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Mittelspannung
1502,661-95,SEE906722372718,SEE906722372718,NaN,Gegendruckturbine 3 MW,9648.0,Kriebstein,Bauhofstraße,1,Sachsen,1993.0,stillgelegt,2023.0,Erdgas,Ja,2.975,Mitteldeutsche Netzgesellschaft Strom mbH (SNB...,Mittelspannung

In [203]:
#blocks

In [204]:
plants_b.sort_values("initialop", ascending=False, inplace=True)

In [205]:
#drop_list = ['Blockname', 'KWK', 'Nettoleistung', 'Stilllegung', 'Straße und Hausnummer (Standort Kraftwerk)', 'PLZ', 'Ort', 'Nettoleistung']
#plants_g = plants_f.drop(drop_list, axis=1)

In [206]:
#plants_h = plants_g.rename(columns={"KraftwerkID": "plantid", "Gesamtleistung": "totalpower", "Blockzahl": "blockcount", "BlockID": "blockid", "Bundesland": "federalstate", "Energieträger": "energysource", "Inbetriebnahme": "latestexpanded", "Kraftwerksname": "plantname", "Status": "state", "Unternehmen": "company"})

In [207]:
plants_final = plants_b.loc[:]

In [208]:
plants_final.dtypes

plantid             object
plantname           object
federalstate      category
energysource      category
chp               category
latestexpanded       int32
initialop            int32
totalpower         float64
state             category
blockcount           int32
company             object
dtype: object

In [209]:
# plants_final

In [210]:
# stammdaten

In [211]:
#stammdaten

In [213]:
# cols = [0,2,3,9,10,11,12]
stammdaten = pl6.copy()
drop_list = ['plantid', 'energysource', 'initialop', 'chp', 'plantname', 'power', 'state', 'endop', 'company', 'sseid']
stammdaten_dafuq = stammdaten.drop(drop_list, axis=1)
stammdaten = stammdaten_dafuq.copy()

In [214]:
stammdaten_dafuq.sort_values(['blockid'])

,blockid,plz,place,street,streetnum,federalstate,TSO,voltagelevel
1310,BNA0011,79774.0,Albbruck,NaN,NaN,Baden-Württemberg,ED Netze GmbH,Hochspannung (HS)
1405,BNA0012d,31061.0,Alfeld,Mühlenmarsch,1,Niedersachsen,NaN,NaN
1332,BNA0059a,34225.0,Baunatal,NaN,NaN,Hessen,VW Kraftwerk GmbH,Mittelspannung (MS)
1408,BNA0075,12207.0,Berlin,Ostpreußendamm,61,Berlin,Stromnetz Berlin GmbH,Hochspannung (HS)
1391,BNA0076,12207.0,Berlin,Ostpreußendamm,61,Berlin,Stromnetz Berlin GmbH,Hochspannung (HS)
...,...,...,...,...,...,...,...,...
772,SEE999819576335,39126,Magdeburg,Kraftwerk-Privatweg,7,Sachsen-Anhalt,Netze Magdeburg GmbH (SNB933459598975),Umspannebene Hochspannung/Mittelspannung
261,SEE999839188105,40476,Düsseldorf,Rather Straße,51,Nordrhein-Westfalen,Netzgesellschaft Düsseldorf mbH (SNB933956506145),Mittelspannung
1432,SEE999848168525,21079.0,Hamburg,Moorburger Schanze,2,Hamburg,NaN,Hochspannung
983,SEE999966551940,14478,Potsdam,Zum Heizwerk,20,Brandenburg,Netzgesellschaft Potsdam GmbH (SNB929027950139),Hochspannung
1435,SEE999977738880,6682.0,Teuchern,Industriestraße,1,Sachsen-Anhalt,NaN,Hochspannung

In [215]:
stmp = pl6.copy()
stammdaten2 = stmp.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [216]:
#stammdaten2.loc[stammdaten2.blockid == "BNA0221c"]

In [217]:
#stammdaten.to_csv("stammdaten.csv", index=False)

In [218]:
#plants_final.to_csv("plants.csv", index=False)

In [219]:
#blocks.to_csv("blocks_3.csv", index=False)

In [220]:
#stammdaten2

In [221]:
DROP_ST = ['blockid', 'jahr', 'kennnummer','betriebsname','betriebsname_2','plz_x','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST2 = ['jahr', 'kennnummer','betriebsname','betriebsname_2','plz','ort','strasse','hausnr','bundesland','flusseinzugsgebiet','taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']
DROP_ST3 = ['jahr', 'kennnummer', 'bundesland', 'flusseinzugsgebiet', "betriebsname", "betriebsname_2", 'taet_nr','taetigkeit','activity','haupttaetigkeit','branche','sector','nace_id','nace_wirtschaftszweig','nace_sector','stoffgruppe','substances_group','schadstoff','pollutant','umweltkompartiment','releases_to','jahresfracht_freisetzung','versehentliche_freisetzung','schadstoff_schwellenwert','einheit','unit','bestimmungsmethode','determination_method','schutzgrund_fracht','confidential_reason_release','schutzgrund_betrieb','confidential_reason_facility']

In [222]:
#DROP_ST = ['jahr']

In [223]:
plants_d1 = plants_final.merge(prtr, how="left", left_on="plantid", right_on="kennnummer")

In [224]:
#plants_d1.dtypes

In [225]:
pld2 = plants_d1.drop_duplicates(['plantid'])

In [226]:
pld3 = pld2.drop(DROP_ST3, axis=1)
plants_final1 = pld3

In [227]:
plants_final2 = plants_final1.merge(plants_act, on="plantid", how='left')

In [228]:
plants_final3 = plants_final2.dropna(subset=["plantid"])

In [229]:
plants_final3.groupby("energysource").count()

C:\Users\dietz\AppData\Local\Temp\ipykernel_16288\2887887728.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  plants_final3.groupby("energysource").count()

,plantid,plantname,federalstate,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
energysource,,,,,,,,,,,,,,,,,,,
Kernenergie,8,8,8,8,8,8,8,8,8,0,0,0,0,0,0,0,0,0,0
Braunkohle,29,29,29,29,29,29,29,29,29,23,27,27,27,27,27,27,27,27,23
Steinkohle,69,69,69,69,69,69,69,69,69,47,66,66,66,66,66,66,66,66,47
Erdgas,196,194,196,196,196,196,196,196,196,174,126,126,126,126,126,126,126,126,174
Mineralölprodukte,19,19,19,19,19,19,19,19,19,12,6,6,6,6,6,6,6,6,12
Abfall,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Biomasse,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [231]:
plants_final2

,plantid,plantname,federalstate,energysource,chp,latestexpanded,initialop,totalpower,state,blockcount,company,betreiber,eigentuemer,plz,ort,strasse,hausnr,geo_lat_wgs84,geo_long_wgs84,activepower
0,06-11-01-1105502,GuD Marzahn Dampfturbine,Berlin,Erdgas,Ja,2020,2020,258.800,in Betrieb,2,Vattenfall GmbH,Vattenfall Europe Wärme AG,Vattenfall Europe Wärme AG,12681,Berlin,Rhinstr.,70,52.523389,13.522089,258.800
1,06-09-162-0025-0001,Werk 1.1 KWK 2,Bayern,Erdgas,Ja,2019,2019,26.940,in Betrieb,7,BMW AG,Bayerische Motorenwerke AG,Bayerische Motorenwerke AG,80788,München,Lerchenauer Str.,76,48.179175,11.561502,26.940
2,661-107,70001313.01,Thüringen,Erdgas,Ja,2018,2018,22.360,in Betrieb,5,ENGIE Deutschland GmbH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.360
3,661-93,HKW Dresden-Nord,Sachsen,Erdgas,Ja,2018,2018,11.500,in Betrieb,1,DREWAG - Stadtwerke Dresden GmbH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.500
4,661-111,Gasmotor Bad Salzungen,Thüringen,Erdgas,Ja,2018,2018,10.003,in Betrieb,1,TEAG Thüringer Energie AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,06-09-676-2101-0002,Sammelschienen-Kraftwerk Gas- und Dampfturbinen,Bayern,Erdgas,Ja,1956,1956,112.719,in Betrieb,1,Kraftwerk Obernburg,Kraftwerk Obernburg GmbH,Kraftwerk Obernburg GmbH,63906,Erlenbach a.Main,Glanzstoffstr.,1,49.827408,9.148631,112.719
318,06-05-300-9046797,LEV KWG G23,Nordrhein-Westfalen,Steinkohle,Ja,1999,1955,128.000,in Betrieb,8,Currenta GmbH & Co. OHG,-,-,51368,Leverkusen,CHEMPARK Leverkusen,Gebäude D 8,51.022209,6.985901,128.000
319,664-07,Fab Fortuna,Nordrhein-Westfalen,Braunkohle,Ja,1948,1948,15.000,in Betrieb,1,RWE AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000
320,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,Ja,1936,1936,67.000,stillgelegt KVBG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,07-05-8030815,HKW Karcherstraße,Rheinland-Pfalz,Erdgas,Ja,1900,1900,59.800,in Betrieb,1,SWK Stadtwerke Kaiserslautern Versorgungs-AG,-,-,67655,Kaiserslautern,Karcherstr.,28,49.434939,7.760927,59.800

In [232]:
plants_final2[pd.isnull(plants_final2['plantid'])]

Empty DataFrame
Columns: [plantid, plantname, federalstate, energysource, chp, latestexpanded, initialop, totalpower, state, blockcount, company, betreiber, eigentuemer, plz, ort, strasse, hausnr, geo_lat_wgs84, geo_long_wgs84, activepower]
Index: []

In [233]:
stammdaten

,blockid,plz,place,street,streetnum,federalstate,TSO,voltagelevel
0,SEE915851127786,52070,Aachen,Schwarzer Weg,19 b,Nordrhein-Westfalen,Regionetz GmbH (SNB911641710114),Mittelspannung
1,SEE946736241334,73432,Aalen,Palm Allee,1,Baden-Württemberg,Netze BW GmbH (SNB948311994307),Hochspannung; Hochspannung
2,SEE930596800480,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
3,SEE929797382345,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
4,SEE988046628214,16356,Ahrensfelde,Lindenberger Straße,12,Brandenburg,50Hertz Transmission GmbH (SNB982046657236),Hochspannung
...,...,...,...,...,...,...,...,...
1540,SEE993836152862,45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,CPM Netz GmbH (SNB956923775696),Umspannebene Hochspannung/Mittelspannung
1541,SEE938923083674,45772.0,Marl,Paul-Baumann-Straße,1,Nordrhein-Westfalen,CPM Netz GmbH (SNB956923775696),Hochspannung
1542,SEE985047526785,3185.0,Teichland,Am Kraftwerk,NaN,Brandenburg,50Hertz Transmission GmbH (SNB982046657236),Höchstspannung
1543,SEE964729462818,3185.0,Teichland,Am Kraftwerk,NaN,Brandenburg,50Hertz Transmission GmbH (SNB982046657236),Höchstspannung
1544,SEE985331675700,89077.0,Ulm,Magirusstraße,21,Baden-Württemberg,Stadtwerke Ulm/Neu-Ulm Netze GmbH (SNB93406863...,Mittelspannung

In [234]:
#plants_final2.sort_values("activepower", ascending=False)

In [235]:
#stammdaten2.dtypes

In [236]:
#stammdaten3.sort_values(by=['plantid'], ascending=True)

In [237]:
#stammdaten3 = stammdaten2.drop(DROP_ST, axis=1)

In [238]:
#stammdaten4 = stammdaten3.drop_duplicates(['bnaid'])

In [239]:
#stammdaten4

In [240]:
#list(stammdaten2)

In [241]:
'''


"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,
blockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"
662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201

'''

'\n\n\n"CREATE TABLE blocks(plantid TEXT, blockid TEXT NOT NULL PRIMARY KEY, blockdescription TEXT, federalstate TEXT, energysource TEXT, initialop INTEGER, chp TEXT,\nblockname TEXT, netpower REAL, state TEXT, endop TEXT, company TEXT, FOREIGN KEY (blockid) REFERENCES addresses(blockid) ON DELETE CASCADE);"\n662-01|BNA0164|Vattenfall GmbH|Brunsbüttel|Schleswig-Holstein|GT D|0.0|stillgelegt|Mineralölprodukte|Nein|63.5|201\n\n'

In [242]:
#|664-02|IKW

In [243]:
blocks2 = blocks[['blockid', 'plantid', 'plantname', 'federalstate', 'energysource', 'initialop', 'chp', 'power', 'state', 'endop', 'company']]

In [244]:
blocks2.loc[blocks2.blockid == "SEE999977738880"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
1435,SEE999977738880,664-02,IKW Deuben,Sachsen-Anhalt,Braunkohle,1936.0,Ja,67.0,stillgelegt KVBG,2021.0,NaN

In [245]:
blocks2.loc[blocks2.blockid == "SEE982928435068"]

,blockid,plantid,plantname,federalstate,energysource,initialop,chp,power,state,endop,company
78,SEE982928435068,06-11-01-1105502,GuD Marzahn Dampfturbine,Berlin,Erdgas,2020.0,Ja,69.3,in Betrieb,NaN,Vattenfall GmbH

In [ ]:
list(blocks2)

In [ ]:
#blocks2.loc['C', 'x'] = "BNA1949"

In [246]:
stammdaten.to_csv("stammdaten_nh_new_2.csv", index=False, header=False)
blocks2.to_csv("blocks_nh_2.csv", index=False, header=False)
plants_final2.to_csv("plants_nh_2.csv", index=False, header=False)
stammdaten.to_csv("stammdaten_2.csv", index=False)
blocks2.to_csv("blocks_2.csv", index=False)
plants_final2.to_csv("plants_2.csv", index=False)

In [ ]:
#sqlite3 plantwatch.db  "CREATE TABLE plants(plantid TEXT NOT NULL PRIMARY KEY, plantname TEXT, federalstate TEXT, energysource TEXT, chp TEXT, latestexpanded INT, initialop INT, totalpower REAL, state TEXT, blockcount INT,  company TEXT, plz TEXT, place TEXT, street TEXT, number TEXT, latitude REAL, longitude REAL, activepower REAL, energy_2015 INTEGER,  energy_2016 INTEGER,  energy_2017 INTEGER,  energy_2018 INTEGER,  energy_2019 INTEGER, energy_2020 INTEGER, energy_2021 INTEGER, co2_2007 INTEGER,  co2_2008 INTEGER,  co2_2009 INTEGER,  co2_2010 INTEGER,  co2_2011 INTEGER,  co2_2012 INTEGER,  co2_2013 INTEGER,  co2_2014 INTEGER,  co2_2015 INTEGER,  co2_2016 INTEGER,  co2_2017 INTEGER,  co2_2018 INTEGER, co2_2019 INTEGER, co2_2020 INTEGER, FOREIGN KEY (plantid) REFERENCES blocks(plantid) ON DELETE CASCADE);"

In [ ]:
blocks2.dropna(subset=['plantid'])

In [ ]:
blocks2.shape

In [ ]:
blocks2.dropna(subset=['plantid']).shape

In [ ]:
stammdaten.dropna(subset=['sseid', 'bnaid']).sort_values(by=['sseid'], ascending=False)

In [ ]:
stammdaten

In [ ]:
blocks.loc[blocks["blockid"] == "BNA0645"]

In [ ]:
#bm2.to_csv("bpm.csv", index=False)

In [ ]:
#blocks

In [ ]:
#blocks.groupby('Energieträger').count()

In [ ]:
#pl4 = blocks.loc[blocks['Energieträger'] == "Mineralölprodukte"]

In [ ]:
#pl4

In [ ]:
#pd.set_option('display.max_rows', None)

In [ ]:
#pl4.loc[pl4['Energieträger'] == "Mineralölprodukte"].sort_values(["Bundesland", "Unternehmen", "Kraftwerksname"])

In [ ]:
#plants_final2

In [ ]:
blocks2.sort_values('power', ascending=False)[0:20]

In [ ]:
blocks2.sort_values('power', ascending=False)[0:20]